### ISSUE TITLE
How to sync the OneDrive shared file by URL

### ISSUE THREAD

**Issue by Warlib1975** [Kyrodan/KeeAnywhere#100]
Hi, 

I would like to share some file with passwords which is located on the OneDrive among several persons. O would like give access ONLY to this file, not to whole OneDrive disk. I generate URL to this file with edit permissions, but I don't know how to open the file with this URL without connecting all persons to my private OneDrive.

Thank you

**Comment by Kyrodan** [comment]
Hi @Warlib1975 ,

I think the other person has to "link" the shared file in his/her own personal OneDrive.
I haven't tried it by myself, but this should help:
* How to sync a shared file: https://support.office.com/en-us/article/Add-and-sync-shared-folders-to-OneDrive-8a63cd47-1526-4cd8-bd09-ee3f9bfc1504
* How to share: https://support.office.com/en-us/article/Share-OneDrive-files-and-folders-9fcc2f7d-de0c-4cec-93b0-a82024800c07

A little stupid thing is, that you cannot "invite" a named persons: you only have this link which you can send to someone else. Everyone who knows the link can acces this file. To circumvent a possible security hole: remove the link after all persons have linked this file to theit own OneDrive (or use new Pro-Feature of "expriring links") 

Regards,
Daniel

**Comment by Warlib1975** [comment]
Hi, 

Yes, another person have link to shared file, but I can't use this link in KeePass. The plugin wants to OneDrive auth to access file. There is no enough just the link to keepass file. :-(

Yes the security problem is big, but not critical, since the file is encrypted. Of course risk of deletion is exists., but it's not critical, since backup is exists.

Yes, really stupid things in MS OneDrive, that only link option is available. In Google drive I can make sharing for authorized persons.

**Comment by Kyrodan** [comment]
Hi,

don't use the link in KeePass/KeeAnywhere: that's not possible.
Open the link in a browser, login to your OneDrive and then "add this file to your drive".
After that, you should see and browse to this file in KeeAnywhere *within* your personal OneDrive.

**Comment by Warlib1975** [comment]
I need to solve task when several persons could open/edit KeePass file from a desktop or mobile applications. Persons  don't have login/password to my OneDrive. They have registrations to their own OneDrive, but I don't know how share KeePass file for them.

**Comment by Kyrodan** [comment]
If you share a link to them: if *they* open the link in a browser and login to *their* OneDrive: they can click on "Add to my OneDrive" - see first link I posted earlier.

If this does not work for single files it sure works for folders. Just create a folder with just one KeePass database file in it.

**Comment by Warlib1975** [comment]
Ok. Thank you. I tried with Google Drive. It seems much more secure than OneDrive, since I can specify for what google account I give the access to file with password.

**Comment by Kyrodan** [comment]
You are welcome.
