### ISSUE TITLE
unable to add google drive account

### ISSUE THREAD

**Issue by ghost** [Kyrodan/KeeAnywhere#102]
When i try to add a google drive account, it gives me "400. That's an error." and then loads a blank page. When i right click and go back, i see this. 

> 400. That’s an error.
> 
> 
> 
> Error: invalid_request
> 
> Required parameter is missing: response_type
> 
> Learn more
> 
> Request Detailsaccess_type=offline
> 
>  That’s all we know.

Trying to add a dropbox/onedrive account doesn't work either. Just returns a blank page in the popup.

**Comment by Kyrodan** [comment]
Do you use a proxy? Maybe this is not configured properly (in Internet Explorer) or KeePass itself.
See details here: https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#using-a-proxy

**Comment by rype89** [comment]
nope no proxies. Probably an issue with internet explorer. I tried it on another pc and it worked. Tried to figure out what's going on but just couldn't. Internet explorer works on it's own when trying to access drive/dropbox/etc. Have given up trying to fix it.

**Comment by Kyrodan** [comment]
If any further action is required from my side: please feel free to reopen this issue.

**Comment by zlamma** [comment]
Just in case someone still runs into this, just like I did today:

What seems to have helped is clearing Internet Explorer's history via:
Internet Explorer > Top right ⚙icon > Internet Options > General (the first tab) > under _Browsing history_ > Delete... button (I just erased everything)

Interestingly, even though all works now, the registration dialog started from KeeAnywhere still blinks a _400 That’s an error._ in the beginning.

**Comment by Kyrodan** [comment]
Hi, thanks for investigating this.
Seems to be that Google has changed the location of the "logout page" which
I use.
Will keep an eye on it.

Am Mo., 6. Mai 2019 um 15:55 Uhr schrieb Slawomir Brzezinski <
notifications@github.com>:
