### ISSUE TITLE
Caching database makes KeePass non-portable

### ISSUE THREAD

**Issue by gjf** [Kyrodan/KeeAnywhere#103]
KeeAnywhere cache is automatically created at %userprofile%\AppData\Local\KeePass\KeeAnywhereOfflineCache

But I am using KeePass on my portable HDD and I don't want to store any traces at PCs I have used.

Is it possible to add a possibility to choose path to cache in the same way it was done for Local Backup Folder?

**Comment by marekr** [comment]
http://i.imgur.com/7RB4W8E.png

You can't uncheck the cache?

**Comment by gjf** [comment]
I can, but I want to have an offline db to use when I have no Internet connection.

**Comment by Kyrodan** [comment]
Ok, I thought it should be the case you described but it is not.
Will improve this.

**Comment by gjf** [comment]
Thank you in advance.

**Comment by Kyrodan** [comment]
Released in v1.5.0
