### ISSUE TITLE
KeeAnywhere won't run on Ubuntu

### ISSUE THREAD

**Issue by JonTheNiceGuy** [Kyrodan/KeeAnywhere#104]
I have installed the keepass2 package from the Ubuntu repositories, and then (as root) added your PLGX to /usr/lib/keepass2/plugins/

On opening, I get a message telling me that "A newer .NET Framework is required"

Could you please investigate whether there's a work-around? I'm using Ubuntu 16.04, with mono 4.2.1.

Happy to help with any testing!

**Comment by Kyrodan** [comment]
That's right. KeeAnywhere is not compatible with Mono/Linux.
See #18
