### ISSUE TITLE
Update Dropbox SDK

### ISSUE THREAD

**Issue by Kyrodan** [Kyrodan/KeeAnywhere#105]
> We are reaching out to you because we have discovered an issue with the Dropbox API v2 .NET SDK that your app is currently using. Although the issue does not break any existing behavior, it limits our ability to make non-breaking changes to our API endpoints going forward.
> 
> For that reason, we ask that you update your app to the latest version of the SDK within the next two months. This bug was fixed specifically in v4.2.6.

**Comment by M-Schiller** [comment]
Is this still an open issue? It seems like the Dropbox.Api version used is 4.3.0. It is my understanding that this version would include this bug fix.

**Comment by Kyrodan** [comment]
Sorry for my late reply: Yes you are right :-) Thought that Dropbox only informed Apps which are using these "old" SDK. Closing this.
