### ISSUE TITLE
Google Drive API Request Error

### ISSUE THREAD

**Issue by Zhinjio** [Kyrodan/KeeAnywhere#107]
Just added my Google drive in. Got the popup from google asking for authentication and permission. All of that seemed to work fine. Now when I try to "Open from Cloud"... the dialog appears, I see my account at the top, and get the following error:

Exception:
  Google.Apis.Requests.RequestError
  Daily Limit for Unauthenticated Use Exceeded. Continued use requires
  signup. [403]
  Errors [
    Message[Daily Limit for Unathenticated Use Exceeded.
    Continued use requires signup.] Location [ - ]
  Reason[dailyLimitExceededUnreg] Domain[usageLimits]
  ]

If it added the account ok, shouldn't it be authenticated? Help!

**Comment by Zhinjio** [comment]
Checking proxy settings.

**Comment by Zhinjio** [comment]
It is set to use system proxy settings. I think that should be fine. I will verify this when I get home and can test WITHOUT the proxy, though.

**Comment by Kyrodan** [comment]
Hi @Zhinjio 

this seems to be a temporary problem on Google's side.
I'm investigating it and come back here.

Regards,
Daniel

**Comment by Zhinjio** [comment]
I was able to access correctly when using this at home (without the work proxy in the way). I suspect this is a proxy problem with my work network. Not sure this is your problem to fix. :)

**Comment by Ennneerrrgggyyy** [comment]
Is KeenAnywhere already compatible with Google Backup and Sync? Sorry, I didn't want to open another thread.

**Comment by Kyrodan** [comment]
Hi @Ennneerrrgggyyy ,

I think you mean to use files from "computers"? Then the answer is no, it's not supported. I added this to issue #93. You can still use and sync your files from "My Drive".

Regards,
Daniel

**Comment by Kyrodan** [comment]
Hi @Zhinjio ,

thanks for reporting back. If it is fixed for you now, I close this issue.

Regrads,
Daniel
