### ISSUE TITLE
Newer .NET Framework is required

### ISSUE THREAD

**Issue by Ddedalus** [Kyrodan/KeeAnywhere#108]
I'm using Ubuntu so no wonders there is no .NET here. What wonders me though is why I haven't seen any clear information neither [here](http://keepass.info/plugins.html#keeanywhere) (keepass.info) nor in the README file that this plugin is a Windows-only software. Did I miss something?

**Comment by Kyrodan** [comment]
Hi @Ddedalus 

in README.md (which is displayed as Project summary on GitHub) the prerequisites are clear:
> KeePass 2.35 or newer
> Windows 7 or newer
 >.Net Framework 4.5.2 or newer

There is an open issue #18 to support Mono/Linux.
