### ISSUE TITLE
Adjust account storage location

### ISSUE THREAD

**Issue by mh166** [Kyrodan/KeeAnywhere#113]
Hi,

according to [the documentation](https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#which-account-storage-location-should-i-choose) the accounts file is saved to `%LOCALAPPDATA%` in an encrypted manner.

What I'm wondering: why is it **local** appdata? Is there a way to change it to just `%APPDATA%` in order to work with roaming profiles? Either by migrating the location for everybody in general or by providing an option for this.

The reason I'm asking: I'm working in an environment where we have roaming profiles to work from different workplaces. As of now, I have two options: either copy the settings to the new machine manually or, if I forget to do that, I have two re-add my cloud provider. If it went into the normal `%APPDATA%` folder, it would move to every new workstation automatically with no need of manual adjustments.

From my perspective, I don't see any negative effects on other users or use cases:
 * Security isn't compromised as still only the logged in user can decrypt the file.
 * For people in a "normal" non-roaming environment, it works still just as well.

Could you please consider moving the location of the settings file? Or at least provide an option to override it manually?

Thanks in advance. :)

**Comment by Kyrodan** [comment]
I will take a look at this.

mh166 <notifications@github.com> schrieb am Mo., 30. Okt. 2017, 10:41:

**Comment by Kyrodan** [comment]
Take portability into account (#103).

**Comment by Kyrodan** [comment]
Released in v1.5.0
