### ISSUE TITLE
"Help me choose" help link incorrect (again)

### ISSUE THREAD

**Issue by mh166** [Kyrodan/KeeAnywhere#114]
At the moment it points to the [Getting Started](https://github.com/Kyrodan/KeeAnywhere/wiki/Getting-Started#which-account-storage-location-should-i-choose) page. Instead it should point to [Advanced Topics](https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#which-account-storage-location-should-i-choose). It probably has been moved in the past, I think. :thinking:

**Comment by mh166** [comment]
I just noticed, right after submitting this issue... there's already a PR pending (#90) :man_facepalming:

But maybe you could merge it. :upside_down_face:

**Comment by Kyrodan** [comment]
I will merge this.
