### ISSUE TITLE
KeeAnywhere not works with Temporary Access and Secret Keys

### ISSUE THREAD

**Issue by devilmind** [Kyrodan/KeeAnywhere#116]
I'm using Keepass 2.37 and KeeAnywhere 1.4.1.  I have an issue when I try to use KeeAnywhere in order to use a kdbx file stored on s3 bucket.

After Access and Secret Keys, when I click on 'Test' I obtain the following error message:

"Connection Failed"

I want give you some additional information.

The Amazon subscription where my user is connecting has an Identity Provider configured in order to allow all users to use SAML authentication method.

To generate own temporary Access and Secret Keys each Federated user using the procedure described at link

https://aws.amazon.com/it/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/

The Access and Secret keys are working fine if used with AWS SDK, the AWS CLI or Console tools but not working in the KeeAnywhere case.

Can you help me here?

**Comment by Kyrodan** [comment]
You cannot use your S3-URL in "File" "Open URL" directly. You have to create an Account for your S3-Storage in "Tools" - "KeeAnywhere Settings...".

**Comment by devilmind** [comment]
Yes, I'm talking about KeeAnywhere settings.
After clicked on Add and selected Amazon S3 I need to insert the Access and Secret keys. 
After done that, when I click on test I obtaining "Connection Failed".
(I have correct the original explanation)

**Comment by justchris1** [comment]
I have the same issue.  My account uses assume role with SAML assertion (See link: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html), with a federated login.  I login to my standard company single sign on solution, use a federation broker which contacts Amazon to exchange the SAML assertion for a temporary access token and secret access token.  They should be identical, just that the credentials should expire after a one hour timeout.  They are written to the .aws/credentials file - the same one that the AWS cli tool uses and that works just fine (including S3 access).  However, after entering them into the Access Key and Secret Access Key from "Amazon S3 Account Configuration" and selecting the correct region and pressing Test, I get "Connection failed!".  

Any ideas?  Thanks in advance.

**Comment by justchris1** [comment]
This is my first attempt to modify C# and Visual Studio, but PR #182 attempts to address this.
