### ISSUE TITLE
New Feature: Allow Tag Filtering on Cloud Push

### ISSUE THREAD

**Issue by troylar** [Kyrodan/KeeAnywhere#119]
@Kyrodan I'm about ready to submit a pull request for a new feature

**USE CASE 1** 
If something happens to me, I want my spouse/partner/parent/child, etc. to have access to key passwords, account numbers, document attachments, life insurance, etc. . . . I could save into a separate file, but unfortunately, as I add new accounts, I'm not going to remember to update the file.
I want to simply add a tag to an entry, and the cloud sync will automatically create a file with only entries containing the specified tag(s) with a customized password that I can keep in a secure location (safe deposit box).

**USE CASE 2** 
Similar to the previous use case, I want to share passwords for accounts (utilities, car insurance, DirecTV, etc.) with my spouse/partner, but I don't want her to have every single password I've ever created. 

https://github.com/troylar/KeeAnywhere

**Comment by Kyrodan** [comment]
Hi @troylar,

this sounds very promising to me and I took a look into your code. 
I wonder whether this wouldn't better fit into an own KeePass Plugin and not included in KeeAnywhere? I believe this could also be interesting for other saving locations (especially SFTP). I tried to keep KeeAnywhere free from "own" features itself and tried to improve compatibility to other plugins working on databases/content.

What do you think?

Regards,
Daniel

**Comment by troylar** [comment]
Fair enough. I would agree, thanks
