### ISSUE TITLE
Doesn't work with google drive 

### ISSUE THREAD

**Issue by dariocdj** [Kyrodan/KeeAnywhere#121]
After giving permission it returns with "Authentication failed!"

**Comment by marcorichetta** [comment]
Can you specifiy where are you receiving that error?
I followed the steps here [https://github.com/Kyrodan/KeeAnywhere/wiki/Getting-Started#usage](url) and I was able to add my Google account and save my DB in GDrive.

**Comment by dariocdj** [comment]
"In this dialog click on Add... and chose your Cloud Provider from the drop-down list"...choosing google drive, putting the right password, keepass respond (and not gdrive) auth failed...

**Comment by ucerotk** [comment]
Hi,

Look in the Plugins directory if you have a file called KeeAnywhere.dll. If you have it, close keepass, delete this file, and try again.


Saludos

**Comment by Kyrodan** [comment]
Maybe a proxy issue? If you use a proxy, please check out https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#using-a-proxy

Please also try the recently released v1.5.1 which contains a fix for better handling slow connections/long running up-/downloads.

**Comment by Kyrodan** [comment]
Hmm, interesting. I haven't change anything for Proxy-Settings in 1.5.x. If it works in 1.4.1 it should work in 1.5.0/.1, too.

Will double-check, whether Google-Api has changed (and/or KeePass itself).

**Comment by MrSnooze** [comment]
Hello I realized the same problem after updating from KeePass version 2.39.1 and KeeAnywhere-1.4.1.plgx to any newer version. Today I installed angain both mentioned versions and the opening / saving from GoogleDrive works fine again. I use the same proxy.

With KeePass-2.42 and KeeAnywhere-1.5.1 I get following msg:
Authentication failed!

Fehler beim Senden der Anforderung.
Google.Apis.Core
bei Google.Apis.Http.ConfigurableMessageHandler.d__59.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.d__35.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.d__30.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei KeeAnywhere.StorageProviders.GoogleDrive.GoogleDriveStorageConfigurator.d__c.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei KeeAnywhere.OAuth2.OAuth2Form.d__3.MoveNext()
Void MoveNext()

Please review.
Thanks René

**Comment by MrSnooze** [comment]
> 
> 
> Hmm, interesting. I haven't change anything for Proxy-Settings in 1.5.x. If it works in 1.4.1 it should work in 1.5.0/.1, too.
> 
> Will double-check, whether Google-Api has changed (and/or KeePass itself).

Hello,

did you found time for double checking?
We still got the same problem.
With the new versions it shows the Authentication failed thing.

**Comment by Kyrodan** [comment]
Maybe duplicate of #123 .
