### ISSUE TITLE
KeeAnywhere ignore KeePass Proxy configuration

### ISSUE THREAD

**Issue by ilvetz** [Kyrodan/KeeAnywhere#123]
Hi.

Probably linked to issue #55 .

I have already configured two accounts (Dropbox and Dropbox restricted).

Keepass setup:
- direct connection

Windows setup:
- system proxy script inherited by a policy

KeeAnywhere always show errors which demonstrate it is wrongly connecting to the Internet via proxy.

**Comment by Kyrodan** [comment]
KeeAnywhere uses KeePass' Proxy Configuration for everything except the visual WebBrowser part for registering an account. This is a known limitation which I can't circumvent. 

In the future I will use the system browser for registering an account. With this it is implicitly clear, the Browser has to be configured independent of KeePass.

**Comment by BobVul** [comment]
@Kyrodan As ilvetz said, this occurs everywhere, not just in the visual web browser. For example, the "Check" fails, as does loading a database or saving a database.

In my particular case, I have KeePass configured to not use a proxy ("No proxy"). However, KeeAnywhere still attempts to use the system proxy at all times, apparently ignoring the KeePass setting.

**Comment by BobVul** [comment]
Found the issue: [`UseProxy`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.useproxy) *defaults* to `true`, and KeeAnywhere never explicitly sets it to `false` when there's no proxy defined:

https://github.com/Kyrodan/KeeAnywhere/blob/1ae5539bfa9ddde0906c1296393a61f9a8df2604/KeeAnywhere/StorageProviders/ProxyTools.cs#L32-L39

With the defaults of `UseProxy = true, Proxy = null`, HttpClientHandler falls back to using the system default ... despite the explicit setting of "No proxy" in KeePass.

Quick and easy fix. I'll PR it in a minute.
