### ISSUE TITLE
Possible to programmatically pre-populate S3 access/secret key?

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [Kyrodan/KeeAnywhere#126]
Is it possible to programmatically pre-populate S3 access/secret key and region to avoid our users having to manually enter new credentials when we cycle keys?

**Comment by Kyrodan** [comment]
What do you mean with "pre-populate"? I suggest you are requesting for an automatic mechanism of populating configuration details of a certain account? If yes, you can set your account storage location to "KeePass Configuration" (see details here: https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#which-account-storage-location-should-i-choose) and share/exchange this file.
