### ISSUE TITLE
Can connect to Google Drive, but cannot open Keepass database.

### ISSUE THREAD

**Issue by jose-mason** [Kyrodan/KeeAnywhere#127]
I've successfully added my Google Drive account with KeeAnywhere and can navigate the file system.  But when I enter my Master Password, I get the following error:

> gdrive:///{USERNAME}/{DIRECTORY}/[FILENAME}
> 
> Failed to load the specified file!
> 
> An exception occurred during a WebClient request.

I haven't done extensive testing, but it would appear this is a Google Drive specific issue, as I have no issues when using Dropbox.  I should also mention that I've attempted this on two separate systems with the same software setup, with the same results.

I am using KeePass 2.38 w/ KeeAnywhere 1.4.1 on Windows 10 PC.

**Comment by 01i** [comment]
I'm getting the exact same error message with the same system specs (Win10, KeePass 2.38, KeeAnywhere1.4.1). There's no file corruption, I can still access my database stored on gdrive from my mobile using Keepass2Android, and can still open the synced version of the database from the local google folder on my PC. But I get the WebCliet request exception from the PC using KeeAnywhere

**Comment by 01i** [comment]
Just wanted to update that it's working again for me today.

**Comment by 01i** [comment]
Apologies, I completely forgot that I'd switched my PC to use the local copy of my password database.  Sorry for confusing the matter, that last update was incorrect, it's not resolved. It's still not possible to connect to my gdrive.

**Comment by Doshirae** [comment]
I have the exact same error ><

**Comment by 01i** [comment]
So is there any update on this? Anyone going to be looking into it? Or should I seek an alternative keepass plugin for googledrive storage?

**Comment by Doshirae** [comment]
I personally just use it with OneDrive and that work just fine 
It seems that only Google drive is buggy

On 13 April 2018 03:51:41 CEST, Oliver Piotrowski <notifications@github.com> wrote:
>So is there any update on this? Anyone going to be looking into it? Or
>should I seek an alternative keepass plugin for googledrive storage?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kyrodan/KeeAnywhere/issues/127#issuecomment-380996241

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kyrodan** [comment]
I will take a look into it and report back.

**Comment by githubluv** [comment]
I have this problem also on Ubuntu 18.04 with Keepass 2.38.  Keepass does not show the google drive indicated by email address in the Open Database File dialog.  Is any work being done on the problem?

**Comment by Coises** [comment]
I don't know if this helps, but I'm seeing the same error in a somewhat different context on Windows 7 using KeePass 2.39.1 and KeeAnywhere 1.4.1.  I can open my database from Google Drive fine from either the Open URL dialog or the Open from Cloud Drive dialog.

I tried to set up an entry in another database (also on Google Drive, same account, also opens normally from Open dialogs) to link to my database with this in the URL field:

cmd://keepass.exe gdrive:///Coises/RandyKee.kbdx -pw:{PASSWORD} -ioiscomplete

as suggested elsewhere, and on clicking it, I get the "failed to load" message. If I remove the password argument, I am asked for the password and then get the "failed to load" message. Removing ioiscomplete (with or without pw) doesn't change anything except that the Open URL dialog appears first.

Issuing:
"C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe" gdrive:///Coises/RandyKee.kbdx -ioiscomplete
from the command line also leads to "failed to load" after entering the password.

**Comment by Kyrodan** [comment]
I recently released v1.5.1 which contains a fix for better handling large databases.
If you have large databases (>3 MB), please reevaluate latest release and report back, if there is still an issue.

**Comment by spacewave** [comment]
I have the same issue with Dropbox.

An exception occurred during a WebClient request.  Win10

db size is 96KB.

Thank you for all your help.

**Comment by jose-mason** [comment]
I had a bit of free time where I could sit down and troubleshoot my issue with KeeAnywhere. As part of my testing, I created a database with the default filename "Database". I put one entry in that database, low and behold, KeeaAnywhere was able to save & open the file. Next, I exported my existing database and imported it into a new database. I used KeeAnywhere to save the new(wer) database and that was unsuccessful (error messages attached) . So I took a look at the files I had just created and had a bit of a eureka moment.

My 'original' database for this exercise had spaces, periods, and a single quote in it's filename. This had not been an issue using the File->Open-> Open File... dialog, so it didn't occur to me to consider the the filename syntax. However, given that we're using a URI, that single quote made the most sense to eliminate.  Afterward, the file saved and opened just fine.

Hopefully someone else will find this information useful.
![capture01](https://user-images.githubusercontent.com/37463266/51780295-70912d80-20db-11e9-8266-2dfedd7b1669.PNG)
![capture02](https://user-images.githubusercontent.com/37463266/51780296-70912d80-20db-11e9-8fa4-b720859d37bb.PNG)

**Comment by nsfan666666** [comment]
Same issue still persists. I can connect however when I try to open the backup I get the following
![image](https://user-images.githubusercontent.com/8250716/96466470-2397a800-122a-11eb-8cd6-bcf8eecfc0fe.png)

and the whole program gets stuck.

**Comment by rigveda2005** [comment]
I am also experiencing the same issue.
Running KeePass 2.50 64bit
KeeAnywhere - 2.0.3

![KeePass_Screenshot 2022-03-24 120243](https://user-images.githubusercontent.com/102313131/159959294-ba286833-2a64-4dfc-9c1c-5c7a5ae03cc5.png)
