### ISSUE TITLE
Feature Request: Nickname or Label for each account

### ISSUE THREAD

**Issue by AIVAS001** [Kyrodan/KeeAnywhere#131]
A feature that, I feel, would be very useful is a nickname or label for each account to help distinguish them from each other. This is important when multiple accounts for the same provider exist.
i.e. I have 2 Google Drive accounts: 1 for work and 1 for personal yet they appear as "My Name" and "My Name (2)". Now I have to remember which is which.
With a Nickname or Label, I can identify one as Work and the other as Personal, or anything I so chose for that matter, and it's readily apparent which one I should be working with.
Now typically the list of folders should help identify which account you are currently seeing in the dialog but that may not always be the case.
I should think this would be relatively easy to add.

Cheers.

**Comment by Kyrodan** [comment]
You already can rename an Account: Single click the Account Name - prompt
changes to an input field. I think I described it in Wiki in detail.

AIVAS001 <notifications@github.com> schrieb am Fr., 20. Apr. 2018, 14:37:
