### ISSUE TITLE
OneDrive shared folders issue

### ISSUE THREAD

**Issue by glukinho** [Kyrodan/KeeAnywhere#134]
I cannot use KeeAnywhere when kdbx file is located in a folder that someone shared to my account.
For example, Onedrive user john@example.com shares to my Onedrive account glukinho@example.com a folder. I add it to my folders and see and synchronize it among other my folders using regular Onedrive client. 
But when I try to enter this folder with KeeAnywhere, it seems unaccessible with type = Unknown, while other folders are actually Folders.
On screenshots, the folder 'papochka' was shared to me by other user, and I can't reach it with KeeAnywhere:
![image](https://user-images.githubusercontent.com/15836211/40545488-aea25a44-6034-11e8-889c-27c2c901f581.png)
![image](https://user-images.githubusercontent.com/15836211/40545498-b8ea8e04-6034-11e8-9916-35ac94284a1f.png)

**Comment by Kyrodan** [comment]
It's a known limitation of KeeAnywhere. Have to implement some code to get it working.

**Comment by aeroboy86** [comment]
Hello,
Is there any intension to solve this bug? Still present in 1.6.0.0 - thanks for a great plugin

**Comment by Kyrodan** [comment]
Will be fixed in next release.
