### ISSUE TITLE
How can I be sure my password isn't being stolen when adding a new account?

### ISSUE THREAD

**Issue by kbhutchinson** [Kyrodan/KeeAnywhere#137]
I'm a long time user of KeeAnywhere already, but when setting up a laptop today, an idea came to me. 

When adding a new account into the KeeAnywhere account manager for Dropbox, a dialog window opens that looks like a Dropbox login page. I realize that this is an embedded browser window that is actually loading the Dropbox login page, but as a user, is there any way for me to verify that? The address bar is not shown, so I can't even look at the URL. Also, even if the address bar was shown, there's no way to tell if it's a real browser window or something being mocked up by KeeAnywhere.

So I'm asking if there is any method for me to verify that the dialog box presented by KeeAnywhere is not stealing the password I type in? Is there some way to get the information needed to add an account by using my actual browser that I already trust and then provide that to KeeAnywhere separately, rather than typing into a dialog that I can't verify?

I want to be clear that I like KeeAnywhere and will continue using it anyway, but I'm curious if there is a way for me to verify its safety for myself besides pulling the source code, reading it and verifying it, and then building the plx myself. If not, that's okay, like I said, I'm just curious if there is a way.

**Comment by elvoe** [comment]
I see two possible solutions.
1) You could compile the plugin yourself.
2) You could use 2-factor auth on Dropbox.

**Comment by Kyrodan** [comment]
Currently you can't be sure, as long as you won't trust KeeAnywhere (and it's packaged distrubtion) itself.
If #89 is implemented, the default browser will be used and you can be sure (as long as you trust the browser itself ;-))

**Comment by Kyrodan** [comment]
BTW: I always use 2-Factor-Auth for every Service that offers it.
