### ISSUE TITLE
Fails to save big DB to remote [tested on GDrive & OneDrive]

### ISSUE THREAD

**Issue by freMea** [Kyrodan/KeeAnywhere#139]
KeePass | OS | plugin version
------------------ | ---- | ----
2.39.1 | Win 10 x64 pro (french) 14393 | 1.4.1

## Introduction

It seems this issue only occurs on DB which size is > 5 MB. One of my DB is used to save documents like images or pdf (ID, etc.) as attachments in several entries. This DB size is 5.06 MB. My main DB size is 0.99 MB and the sync feature works. This bug is discussed on _Keepass_ forum [here](https://sourceforge.net/p/keepass/discussion/329221/thread/3f966740/#b795).

## Steps to reproduce

1. Add _GDrive_ or _OneDrive_ account to _KeeAnywhere_
2. Test by _Open from cloud drive…_ and load you db → it works
3. _File>Synchronize>Synchronize with URL_

## Results

- No issue to read the DB from cloud.
- The sync is reported as successful but there is a warning dialog during process and my DB on the cloud has not been updated
GDrive
![Screenshot Gdrive](https://i.snag.gy/jxkoYe.jpg)
OneDrive
![Screenshot OneDrive](https://i.snag.gy/BtrURf.jpg)

**Note: Sync used to work with no issue at least until june 2018 with big DB. Plugin successfully used during at least 1 year.**

## Steps to try to solve/debug to no avail

- Delete **PluginCache** folder
- Delete/recreate GDrive account on _KeeAnywhere_
- Clear offline cache in KA settings
- Disable Windows firewall and everything I think it could affect connection

**Note: I uninstall _KeeAnywhere_ then tried the _KeePassOneDriveSync_ plugin and I had the same sync issue, it can read/download from the cloud but **not** write/upload to it.**

**Comment by Kyrodan** [comment]
Thanks for you issue report.
I will take a look to improve this. Seems to be the same limitation on both providers. Maybe others follow the same restriction.

Ressources:
* https://blogs.technet.microsoft.com/sharepointdevelopersupport/2018/02/05/uploading-large-files-using-microsoft-graph-api/

**Comment by Kyrodan** [comment]
@freMea: could you please measure the time span between hitting "save" and the occurance of this error?
