### ISSUE TITLE
Create second database on google drive fails

### ISSUE THREAD

**Issue by lgs4gh** [Kyrodan/KeeAnywhere#140]
When I do a File, New database and change the address bar to "gdrive:///myname/" it says "you can't open this location using this program". I already have one working database, but would like to create a second database on my google drive. How can I accomplish this? thank you

**Comment by Kyrodan** [comment]
Short answer: You can't directly!
Long answer: Starting in KeePass 2.37 the File-New-Function has changed to first select a local storage folder. After first saving the database locally you can select File-Save As to save to a storage location provided by KeeAnywhere.
