### ISSUE TITLE
Authentication failed when trying to authorize to Google Drive with newest KeeAnywhere 1.5

### ISSUE THREAD

**Issue by ArtyoZ** [Kyrodan/KeeAnywhere#145]
Hello! I have a problem with newest KeeAnywhere 1.5 and KeePass 2.40. With old version of KeeAnywhere everything is ok. Steps to reproduce:
1) Go to KeeAnywhere settings, "Accounts" tab;
2) Choose "Add Google Drive";
3) Choose account to go to "KeeAnywhere" app;
4) Authorize to Google Drive with a password;
5) Give a permission to my account's access for "KeeAnywhere" app;

Then I see this messagebox:
![image](https://user-images.githubusercontent.com/43533126/45941048-16754400-bfe5-11e8-96f2-6e6ca9054567.png)

Extended report:

> Authentication failed!
> 
> Произошла ошибка при отправке запроса.
> Google.Apis.Core
>    в Google.Apis.Http.ConfigurableMessageHandler.<SendAsync>d__59.MoveNext()
> --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
>    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    в Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.<ExecuteAsync>d__0.MoveNext()
> --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
>    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    в Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<FetchTokenAsync>d__35.MoveNext()
> --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
>    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    в Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<ExchangeCodeForTokenAsync>d__30.MoveNext()
> --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
>    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    в KeeAnywhere.StorageProviders.GoogleDrive.GoogleDriveStorageConfigurator.<Claim>d__c.MoveNext()
> --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
>    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    в KeeAnywhere.OAuth2.OAuth2Form.<OnNavigated>d__3.MoveNext()
> Void MoveNext()
> 
> 
> Inner:
> Удаленный сервер возвратил ошибку: (407) Требуется аутентификация посредника.
> System
>    в System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
>    в System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
> System.IO.Stream EndGetRequestStream(System.IAsyncResult, System.Net.TransportContext ByRef)

**Comment by Kyrodan** [comment]
It seems that you are using a proxy and this proxy is not configured properly in KeePass (HTTP-Status-Code 407, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407).

Please refer to https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#using-a-proxy

**Comment by ArtyoZ** [comment]
No, I've got the same error ithout using of proxy too. Also I've tried to re-configure the proxy, but it doesn't help me.
