### ISSUE TITLE
KeeAnywhere-1.5.0 plugin incompatible with Keepass 2.40 

### ISSUE THREAD

**Issue by LegoChicken** [Kyrodan/KeeAnywhere#147]
Two machines running Windows 7 professional. One works fine the other one produces:
![image](https://user-images.githubusercontent.com/2156602/46242971-92e19b80-c3c6-11e8-93f3-763ad769b7f0.png)

**Comment by LegoChicken** [comment]
I also tried deleting the PluginCache directories. It was recreated on the next run of the app.

**Comment by Antasik** [comment]
Hello,

After moving KeePass (2.40 portable) to new Windows 10 machine i've got the same Error. I solved the problem by removing KeeAnywhere.Accounts.json file from KeePass directory. It looks like "secret" is encrypted and need to be decrypted in the same machine and user account but i'm not shure.

BR,
Marcin

**Comment by eulercamposbarros** [comment]
To avoid this problem, just select **KeePass Configuration** for Storage Location and you will be able to use your settings KeeAnywhere on any machine. Be aware that your access token will be stored _unencrypted_ in KeePass.config.xml file.

**Comment by LegoChicken** [comment]
Still not working after upgrading to 1.5.1. Deleted everything in the PluginCache directory. Can you please re-open this defect.

**Comment by Kyrodan** [comment]
@LegoChicken: v1.5.1 indeed does not fix your issue because maybe this is not an issue :-) 
Please check my post https://github.com/Kyrodan/KeeAnywhere/issues/147#issuecomment-431257859:

> Topic 1:
> I double checked the documentation and can't find a problem I can fix. As @Antasik statet (#147 (comment)) the KeeAnywhere.Accounts.json is encrypted via the current users account secrets. It can't be read, if it is not the same user anymore: copied the file to another users directory; deleted the original account and recreated a new one with the same name; etc. If it's a domain user, it also works on other machines (for what I move this file to "Roaming" App Data folder.

Maybe try to save the account info to KeePass config instead of seperate KeeAnywhere.Accounts.json

**Comment by Antasik** [comment]
In my opinion plugin behavior is fine and expected (there is no needed crypto key on new/other user profile) but exception info is misleading. Information thrown should be clear (about encrypt not "plugin incompatible with Keepass 2.40")

**Comment by LegoChicken** [comment]
I finally got back to looking at this again. I deleted the KeeAnywhere.Accounts.json file from KeePass directory and set it up again and now works.
