### ISSUE TITLE
KeeAnywhere Offline Cache path

### ISSUE THREAD

**Issue by gb-velir** [Kyrodan/KeeAnywhere#148]
Environment:
Windows 10 v1809
KeePass 2.4.0 (installed)
KeeAnywhere plugin 1.5.0 stored in %PROGRAMFILES(x86)%\KeePass Password Safe 2\plugins

I am expecting the cache according to release notes to be %APPDATA%\KeePass but instead it's %PROGRAMFILES(x86)%\KeePass Password Safe 2\

![2018-10-04 14_18_22-window](https://user-images.githubusercontent.com/9115037/46494250-6e2f5e80-c7e0-11e8-850e-58328eb96771.png)

**Comment by Kyrodan** [comment]
Maybe I have to improve identification of portable installations.
In your case it seems, that the installed version is determined as portable.
Currently it is portable, if "PreferUserConfiguration" is `false`. KeePass' installer has a config set this flag to `true`.

So please checkt the content of your KeePass.config.xml in *Program Folder*:
```
<?xml version="1.0" encoding="utf-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<Meta>
		<PreferUserConfiguration>true</PreferUserConfiguration>
	</Meta>
</Configuration>
```

**Comment by Kyrodan** [comment]
Determination of portability starting with version 1.5.1 will be:
* Check Parameter "PreferUserConfiguration": yes = non-portable (only check in version 1.5.0)
* if PreferUserConfiguration is false (Config file is beside KeePass.exe): check, whether KeePass is started from ProgramX86- or Program-Folder => if yes: non-portable

**Comment by gb-velir** [comment]
That was indeed the case, because originally the setup was portable, then I switched to installed. However switching to

`<PreferUserConfiguration>true</PreferUserConfiguration>`

did not fix the issue.
