### ISSUE TITLE
keyanywhere 1.5 won't connect cloud drive

### ISSUE THREAD

**Issue by nd2kos** [Kyrodan/KeeAnywhere#149]
Installed keyanywhere 1.5 on keepass 2.40. Won't connect to access cloud drive. Get a "Can't access this page" error regardless of cloud drv selected in 'Add' dropdown.

**Comment by iliyesku** [comment]
had to downgrade

**Comment by Kyrodan** [comment]
Maybe a proxy issue? Refer to https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#using-a-proxy to properly set up proxy in KeePass *and* Internet Explorer/System proxy settings .
