### ISSUE TITLE
KeeAnywhere incompatible

### ISSUE THREAD

**Issue by spymaxx** [Kyrodan/KeeAnywhere#150]
tried installing the plugin and get this error:

![capture](https://user-images.githubusercontent.com/43915260/46574832-eaa87580-c977-11e8-9870-e39f888a2006.PNG)

**Comment by claudiuconstantin** [comment]
Are you using the latest release of the plugin + latest version of Keepass?

**Comment by Kyrodan** [comment]
Maybe duplicate of #147. Will add improved loading of Microsoft.Graph.Core-Library in version 1.5.1

Please reopen this issue, if you have a problem after upgrading to version 1.5.1 (which will be released later today).
