### ISSUE TITLE
New Provider: BackBlaze B2

### ISSUE THREAD

**Issue by AIVAS001** [Kyrodan/KeeAnywhere#154]
It would be nice to have access to BackBlaze B2 online storage.
[https://www.backblaze.com/b2/cloud-storage.html](https://www.backblaze.com/b2/cloud-storage.html)

API Docs:
[https://www.backblaze.com/b2/docs/](https://www.backblaze.com/b2/docs/)

Cheers

**Comment by Kyrodan** [comment]
Vote for this new provider, if you would like to see it implemented.

**Comment by Kyrodan** [comment]
No .NET-SDK avaialable by Backblaze itself.
Possible library that can be used: https://github.com/coryrwest/B2.NET

**Comment by vrelk** [comment]
You should be able to use the S3 SDK. Just leave things as textboxes and let people enter the info themselves, then it should work for any S3 compatible provider, not just Backblaze.

Example for MinIO:
```
RegionEndpoint = RegionEndpoint.USEast1, // MUST set this before setting ServiceURL and it should match the `MINIO_REGION` environment variable.
ServiceURL = "http://localhost:9000", // replace http://localhost:9000 with URL of your MinIO server
ForcePathStyle = true // MUST be true to work correctly with MinIO server
```

Backblaze allows you to setup an account and has a generous free tier, so you can play around with it.

New Provider: _S3 Compatible_
Options:
- _Access Key_ - nothing different from AWS
- _Secret Key_ - nothing different from AWS
- _Endpoint_ - Type: textbox
- _Region_ - Type: textbox
- _Path Style_ - Type: checkbox (probably checked by default)

If you allow any hostname to be entered, it could easily work for any S3 compatible provider, including ones you host yourself (MinIO).
https://docs.min.io/docs/how-to-use-aws-sdk-for-net-with-minio-server.html

**Comment by Kyrodan** [comment]
@AIVAS001 @vrelk 
Please test Beta-Build from https://github.com/Kyrodan/KeeAnywhere/issues/252#issuecomment-782150223

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
