### ISSUE TITLE
Settings dialog should be modal-less

### ISSUE THREAD

**Issue by finejustice** [Kyrodan/KeeAnywhere#155]
keeanywhere settings opens cloud service auth page, which need keepass main windows to retrieve credentials in turn.
however, modal of setting dialog blocks it. the dialog should be modal-less thus allow user to keepass main window.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
Using the system's default browser should fix most of the handling issues with the modal dialog.
If not, please re-open this issue and describe alittle bit more, what you are trying to do and what your proposed solution would be.
