### ISSUE TITLE
AWS S3: Method Not found

### ISSUE THREAD

**Issue by jasonmatos** [Kyrodan/KeeAnywhere#158]
I just upgrade to the latest Keepass version (2.4) and trying to use the latest KeeAnywhere plugin (1.5.1).
I did try to delete both folders C:\Users\[username]\AppData\Local and C:\Users\[username]\AppData\Roaming\KeePass.
I also uninstall keepass and re-install from strach.

As soon as I load the file (KeeAnywhere-1.5.1.plgx) in the plugin directory, I'm receiving a Method not found: 'System.Threading.Task.Task`1 <Amazon.S3.Model.ListBucketsResponse>'

I will attach the complete error message.

Running Windows 7
![keepass](https://user-images.githubusercontent.com/5994967/49895414-5a2a5d80-fe1e-11e8-997c-a7bd5621eec5.png)

Thanks

**Comment by Kyrodan** [comment]
I cannot reproduce this. 
If it still happens with KeePass 2.43 and KeeAnywhere 1.6.0 then please reopen this issue.
