### ISSUE TITLE
Proxy support (with auth) feature request

### ISSUE THREAD

**Issue by pch3** [Kyrodan/KeeAnywhere#16]
Hi

Thanks for great plugin. If you could, please add proxy authentication support (ideally NTLM auth credentials taken from OS)

**Comment by Kyrodan** [comment]
Hi,

KeePass itself has proxy support (which is currently *not* used by KeeAnywhere). You can find it under Tools - Options - Advanced - Proxy... (in lower right corner). Do these options of KeePass fit to your request?

![2016-01-14 17_27_00- keepass](https://cloud.githubusercontent.com/assets/355178/12330206/2e2ff8b4-bae4-11e5-9843-c977214a4231.png)

Regards,
Daniel

**Comment by pch3** [comment]
Hi

I haven't seen that, thx! That would do the trick.

But as you said, your plugin does not use those settings, so when I try to
add google drive account I get an error like the one below:

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (407) Proxy
Authentication Required.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult
asyncResult, TransportContext& context)
   at
System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.31.0.27913
    Win32 Version: 2.31.0.0
    CodeBase:
file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34270 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
GoogleSyncPlugin
    Assembly Version: 2.1.2.0
    Win32 Version: 2.1.2.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/eVBlotc4jzYBxkqhv5Wk/GoogleSyncPlugin.dll
----------------------------------------
KeeAgent
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/tPe1aHOCqUDqwG8svt6m/KeeAgent.dll
----------------------------------------
SshAgentLib
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/tPe1aHOCqUDqwG8svt6m/SshAgentLib.DLL
----------------------------------------
SshAgentLib.WinForms
    Assembly Version: 0.5.0.0
    Win32 Version: 0.5.0.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/tPe1aHOCqUDqwG8svt6m/SshAgentLib.WinForms.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/KeeAnywhere.dll
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/CredentialManagement.DLL
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
KeeAutoExec
    Assembly Version: 1.8.0.28640
    Win32 Version: 1.8.0.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/elxZJ3DkAgcUCOWpv00E/KeeAutoExec.dll
----------------------------------------
KeePassHttp
    Assembly Version: 2.21.0.0
    Win32 Version: 1.8.4.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/XKCj2bfw5PxgEJIa0DcM/KeePassHttp.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.31.0.27913
    Win32 Version: 2.31.0.27913
    CodeBase:
file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34252 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.10.0.1
    Win32 Version: 1.10.0.1
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.10.0.25332
    Win32 Version: 1.10.0.25332
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.10.0.25331
    Win32 Version: 1.10.0.25331
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Google.Apis.Core.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
Microsoft.Threading.Tasks
    Assembly Version: 1.0.12.0
    Win32 Version: 1.0.168.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Microsoft.Threading.Tasks.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.10.0.25333
    Win32 Version: 1.10.0.25333
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Google.Apis.Auth.PlatformServices
    Assembly Version: 1.10.0.25333
    Win32 Version: 1.10.0.25333
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Google.Apis.Auth.PlatformServices.DLL
----------------------------------------
Google.Apis.PlatformServices
    Assembly Version: 1.10.0.25332
    Win32 Version: 1.10.0.25332
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Google.Apis.PlatformServices.DLL
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Primitives/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Primitives.dll
----------------------------------------
Microsoft.Threading.Tasks.Extensions.Desktop
    Assembly Version: 1.0.168.0
    Win32 Version: 1.0.168.0
    CodeBase:
file:///C:/Users/XXX/AppData/Local/KeePass/PluginCache/32xh5nOZY6ac2CN7MhhR/Microsoft.Threading.Tasks.Extensions.Desktop.DLL
----------------------------------------
System.Net
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase:
file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


2016-01-14 17:31 GMT+01:00 Daniel Bölts <notifications@github.com>:

**Comment by Kyrodan** [comment]
Ok, I will see what I can do.

**Comment by ramateur** [comment]
There is a solution with proxy authentication:
The fix for this is to add the following <system.net /> element to keepass.exe.config

`<configuration>

    <system.net>

        <defaultProxy useDefaultCredentials="true" />

    </system.net>

</configuration>`

This sets up the internals of .NET to use the system-defined proxy, which in our case is Microsoft ISA Server. I confirm this as working in a corporate Active Directory environment.

**Comment by sanzoghenzo** [comment]
I have the same problem, and the workaround didn't work for me.
I'm behind a squid proxy.
