### ISSUE TITLE
Chocolatey: plugin installation fails

### ISSUE THREAD

**Issue by MOlavenant** [Kyrodan/KeeAnywhere#160]
Hello
I can not install the plugin "files missing"
Could you kindly tell what is missing ?
thanks
marie

![2019-01-03_16h23_00](https://user-images.githubusercontent.com/46351596/50646077-7f217480-0f75-11e9-8c63-cccce08a7c40.png)

**Comment by jotatoledo** [comment]
Similar issue trying to install using chocolateyui

Env:
- win7
- keepass 2.4 (installed with chocolatey)

**Comment by Kyrodan** [comment]
updated install script for v2.1.0
