### ISSUE TITLE
Monitor opened database for changes in cloud storage

### ISSUE THREAD

**Issue by a-polivanchuk** [Kyrodan/KeeAnywhere#161]
Hi,

I faced an issue when I keep my database opened on PC#1 and make some changes in the same database from PC#2.
When I get back to the unlocked database on PC#1 it is not updated and there is no clue about any changes.
The only way to resolve it is to reopen database, which is not convenient.
There should be some option to perform manual refreshing. The best solution would be to monitor remote database for changes and either propose to refresh it or perform it automatically.

Thanks!

**Comment by jose-mason** [comment]
I have no idea if this same mechanism will work with KeeAnywhere.  I've never actually been able to get KeeAnywhere working consistently long enough to test this.

It is possible to 'Synchronize' your database from within Keepass itself.  Under the File menu there is a pop-out menu for Synchronize or using Ctrl+R (for file) and Ctrl+Shift+R (for URL).

**Comment by a-polivanchuk** [comment]
It's possible to synchronize the opened database from the KeePass menu >> Recent files
