### ISSUE TITLE
Plugin not compatible with Keepass 2.41

### ISSUE THREAD

**Issue by kubics** [Kyrodan/KeeAnywhere#162]
After Keepass upgrade I have the following error

![image](https://user-images.githubusercontent.com/3758112/51470364-f4fa4e00-1d73-11e9-86ec-1a8d3c74c1b0.png)

Thanks for your work!

**Comment by Ve08** [comment]
Switching the storage location to keypass configuration worked for me. I don't get the error anymore.
Looks like the problem is consistent with local user secure storage option.

**Comment by kubics** [comment]
> 
> 
> Switching the storage location to keypass configuration worked for me. I don't get the error anymore.
> Looks like the problem is consistent with local user secure storage option.

Great. This worked for me too. Thanks

**Comment by kubics** [comment]
> 
> 
> Switching the storage location to keypass configuration worked for me. I don't get the error anymore.
> Looks like the problem is consistent with local user secure storage option.

Great. This worked for me too. Thanks
