### ISSUE TITLE
Access only one folder/file inside of drive

### ISSUE THREAD

**Issue by 89sundown** [Kyrodan/KeeAnywhere#165]
Is it possible to point KeyAnywhere to only open a specific file/folder inside of google drive by changing the KeeAnywhere.Accounts to look for a file ID? I'd like to only expose the single database file to keeanywhere rather than my entire drive. 

Is there a way to only access a specific folder or file rather then having KeeAnywhere access your entire drive?

**Comment by Kyrodan** [comment]
With Google Drive this is not possible. In Dropbox you can use "Dropbox Restricted" for this use case.
