### ISSUE TITLE
Slash in name of Google Drive Folder

### ISSUE THREAD

**Issue by MartinSzr** [Kyrodan/KeeAnywhere#168]
I also got an error with google drive:
![KeeAnywhere](https://user-images.githubusercontent.com/14252591/54489239-8edd0380-48aa-11e9-970e-78b4fdcfab0c.jpg)

KeePass 1.41
KeeAnywhere 1.5.1

I followed the steps: https://github.com/Kyrodan/KeeAnywhere/wiki/Getting-Started#usage
Everything worked to the point it should open the DB after putting in the master password for the DB.

I found a solution to my Problem, first I had the DB inside some folders with a "/" (i.e. folder name: "SYSTEM / MISC") and got the error above. If I place my DB in the root of google drive it works! Maybe this helps.

Could be related to the Umlaute Issue: https://github.com/Kyrodan/KeeAnywhere/issues/91

Many Thanks
Martin

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
