### ISSUE TITLE
Release 1?

### ISSUE THREAD

**Issue by alexmbaker** [Kyrodan/KeeAnywhere#17]
Your documentation suggests that KeeAnyware will be ready for a 1.0 Release once KeePass 2.31 has been released.

Since KeePass 2.31 was released on 9th January 2016 would now be a good time to review the status of the code?

**Comment by Kyrodan** [comment]
I already completed coding a few days ago but did not found time to release
:-( . Currently proper documentation is missing, too. Hopefully I can do it
this week.

By the way: latest Alpha is very stable and can be used with KeePass 2.31

Alex Baker <notifications@github.com> schrieb am Do., 28. Jan. 2016 06:06:

**Comment by Kyrodan** [comment]
Finally I released 1.0.0 today :-)

**Comment by alexmbaker** [comment]
Installed and working.. Many thanks...
