### ISSUE TITLE
Still issue with onedrive

### ISSUE THREAD

**Issue by mariusZZ51** [Kyrodan/KeeAnywhere#172]
after restarting PC always asking me to login again !! now i even can't login !!!!
![problem re](https://user-images.githubusercontent.com/36503666/55269010-223d0e00-5287-11e9-9f2e-05dfbdf464ca.PNG)

**Comment by Kyrodan** [comment]
I think, you are using it wrong:
Leave the User Name and Password blank because this is *not* required for KeeAnywhere-enabled Accounts. This is *not* the user name and password to access OneDrive.
