### ISSUE TITLE
No error or info message where it should be

### ISSUE THREAD

**Issue by ksgubanov** [Kyrodan/KeeAnywhere#177]
I'm trying to connect to Dropbox (probably doesn't actually matters to what), but after couple of seconds the same login form is displayed again. It seems like there are some network restrictions, which don't allow me to connect to Dropbox, but the plugin doesn't give any information about that. It appears the same no matter if the credentials are valid or not. It would be nice to be more informative and show an error or info message.

**Comment by Kyrodan** [comment]
Very old issue - closed for cleanup-reason. Feel free to reopen, if it is still valid in latest version 2.1.0
