### ISSUE TITLE
Database loading indefinitly in dropbox (KP 2.42.1)

### ISSUE THREAD

**Issue by sebigut** [Kyrodan/KeeAnywhere#178]
When trying to load my database using dropbox it just stays trying to load forever. IF I load first a local database and then try to load the Dropbox one then it does opens. This behavior did not happen before using the last version of KP
![keepass](https://user-images.githubusercontent.com/14024884/58472905-b4de1a00-811d-11e9-924b-e266035f7d0e.jpg)

**Comment by opeeba** [comment]
I have been experiencing this issue also.

**Comment by Kyrodan** [comment]
I cannot reproduce this on KeePass 2.43 => closing.
If this ss this still reproducable by someone, then please reopen this issue.
