### ISSUE TITLE
[Dropbox] [Google Drive] Open from Cloud Drive only list partial content

### ISSUE THREAD

**Issue by stbxxl** [Kyrodan/KeeAnywhere#179]
Hi, 

I'm trying to open a file with the command "Open from Cloud Drive" from my Dropbox. This used to work just fine, but now the popup window only lists 2 folders (out of 13 total) in my Dropbox. My KeePass file is in one of the not listed folders. I already tried clearing the plugin cache and restarting KeePass and removing and re-adding my Dropbox account (with full access). Both did not work. Is there anything else I could try?

I'm using KeeAnywhere 1.5.1.0 on KeePass 2.42.1 on a Windows 7 and on a Windows 10 laptop. Both behave identical.

Thank you.

**Comment by samej71** [comment]
This is maybe related, maybe not, bit I'm having the same issue with a brand new installation of KeePass 2.4.3 portable but using Google Drive instead of Dropbox. I only see 4 out of my 25 folders. An older instance of KeePass 2.41 is able to access all of the folders. I'm not sure if the version difference is important or coincidental.

**Comment by Kyrodan** [comment]
Are the folders, you do not see, shared folders?

**Comment by mzielinskim** [comment]
I also only 8 of my  30 folders. One of the 8 is a shared folder - the others arent and i dont see whats different with these 8 Folders.

To resolve the problem for me i moved the File into the main Folder and there it got shown...

**Comment by stbxxl** [comment]
> Are the folders, you do not see, shared folders?

No the folders, which are not shown, are not shared.

**Comment by Matthieu-Quadra** [comment]
I have the same issue with Google Drive Cloud. I see shared and not shared folder but not all my folders (shared or not shared).
I tried to downgrade KeePass to version 2.40 and 2.41 and it's the same issue. I'm currently in version 2.43

**Comment by Matthieu-Quadra** [comment]
> I have the same issue with Google Drive Cloud. I see shared and not shared folder but not all my folders (shared or not shared).
> I tried to downgrade KeePass to version 2.40 and 2.41 and it's the same issue. I'm currently in version 2.43

For information, I found a workaround, I tried to open through the menu "Open URL" and setting my drive URL (gdrive:///XXX/XXX/XXX/MyDatabase.kdbx) and my Drive credentials and it works

**Comment by Kyrodan** [comment]
Hi @stbxxl @samej71, 

can you please check this attempt to fix your issues: [dist.zip](https://github.com/Kyrodan/KeeAnywhere/files/4040566/dist.zip)
The ZIP-File contains the PLGX- and Binary-Distribution. Please prefer using the PLGX for your test.

**Be aware, this is a quick-fix and not testet very well. It's not meant to be used productive.**

**Comment by stbxxl** [comment]
> Hi @stbxxl @samej71,
> 
> can you please check this attempt to fix your issues: [dist.zip](https://github.com/Kyrodan/KeeAnywhere/files/4040566/dist.zip)
> The ZIP-File contains the PLGX- and Binary-Distribution. Please prefer using the PLGX for your test.
> 
> **Be aware, this is a quick-fix and not testet very well. It's not meant to be used productive.**

I tested this test version (1.7.0-unstable) and it did not resolve the issue where I only see 2 root folders in my Dropbox account (out of 10 including the Apps folder where my kdbx file resides). I'm using KeePass 2.43 on a Windows 10 laptop.

Checking the DropBox account in KeeAnywhere Settings/Accounts reports back a successful connection. And I can open my kdbx file. However, I have to enter the full URL in File/Open from Cloud Drive (dropbox:///{accountname}/Apps/KeePass/mydb.kdbx).

**Comment by Kyrodan** [comment]
Hmm, is there anything special with these folders? What happens if you
create a new folder: wiki it be displayed or not? Is it only a problem with
root folders or does it also happen with subfolders, too?

stbxxl <notifications@github.com> schrieb am Do., 9. Jan. 2020, 18:05:

**Comment by stbxxl** [comment]
I'm not aware that there is anything special with those 2 folders that are shown or with the others that are not shown. None of the main folders in the root of my Dropbox are either shared, starred or pinned.

For those two folders that are displayed, I can see all sub-folders once I double click on the main folder.

I just added a new test folder to the root of my Dropbox (with Windows Explorer) and it does not show up when I try to open from Cloud Drive (this is with KeyAnywhere 1.6.0 and KeePass restartet).

**Comment by Kyrodan** [comment]
Ok, next try:
I updated the Dropbox-SDK and put the result of a Directory-Listing to the Clipboard.
If you now open the Cloud Drive File Picker: for each call to the Cloud Drive the result is put to clipboard.
I double-checked whether I do something wron with the requests - it does not seem top be so.

What you should do:
* File/Open/Open from Cloud Drive
* Paste the result of the clipboard to notepad
* Check, whether this is the full result (with all expected folders/files)

[dist.zip](https://github.com/Kyrodan/KeeAnywhere/files/4044969/dist.zip)
Please make sure to delete *all* KeeAnywhere-PLGX-Files.

**Comment by Kyrodan** [comment]
Ohh man, I'm so stupid! I should not write code and debug, if I'm tired :-/

Here again - I'm sure this will fix your problem B-)
[dist.zip](https://github.com/Kyrodan/KeeAnywhere/files/4045071/dist.zip)

**Comment by stbxxl** [comment]
The test build "KeeAnywhere-1.7.0-unstable.plgx" from the latest dist.zip does list all Dropbox folders and I also see sub-folders and individual files. All folders and files are displayed in the file picker (in Open from Cloud Drive) and the directory content pasted into notepad matches the main directory structure of my Dropbox.

**Comment by Kyrodan** [comment]
Very good :-)
Thanks for your help.

stbxxl <notifications@github.com> schrieb am Fr., 10. Jan. 2020, 18:06:

**Comment by stbxxl** [comment]
Gerne doch!
