### ISSUE TITLE
Plugin is incompatible with current KeePass version after update windows10

### ISSUE THREAD

**Issue by FidoUser** [Kyrodan/KeeAnywhere#180]
After installed latest updates on Windows 10 (1903) 
![image](https://user-images.githubusercontent.com/23613572/61392767-40775a00-a8c8-11e9-8256-7d5c1b7d09f1.png)

When started keepass recieved error
![image](https://user-images.githubusercontent.com/23613572/61392549-bdee9a80-a8c7-11e9-94c2-e2711195d60c.png)

**Comment by MrRalphMan** [comment]
Hi,

Same thing has happened to me after my Motherboard was replaced.
I've tried deleting the cache files, but when it goes to compile/load plugins, I get the same error.

Paul

**Comment by seblatre** [comment]
Unfortunately, I got a new Windows 10 PC at work and I'm not able to use this plugin anymore. 
Tested with both Keepass 2.40/2.42.1 and plugin 1.5.1.

**Comment by freMea** [comment]
This issue can be closed as well as other related ones (#180 #169 #175) after notifying users that they need to delete those 3 items to reset the plugin after a Windows fresh install or copying keepass folder from one user to another one.
* [folder] PluginCache 
* [folder] KeeAnywhereOfflineCache
* [file] KeeAnywhere.Accounts.json

**Comment by FidoUser** [comment]
> This issue can be closed as well as other related ones (#180 #169 #175) after notifying users that they need to delete those 3 items to reset the plugin after a Windows fresh install or copying keepass folder from one user to another one.
> 
> * [folder] PluginCache
> * [folder] KeeAnywhereOfflineCache
> * [file] KeeAnywhere.Accounts.json

Tnak you
Its resolved issue
