### ISSUE TITLE
Not able to configure AWS S3 with AWS MFA enabled user.

### ISSUE THREAD

**Issue by htshekhada** [Kyrodan/KeeAnywhere#186]
I am trying to add Amazon S3 with my AWS access key and secret key, my user is MFA enabled but there is no way I can give virtual token along with access key and secret key!

**Comment by Kyrodan** [comment]
Maybe duplicate of #116?

**Comment by Kyrodan** [comment]
Just released version 1.6.0 which hopefully implements this feature.
Please try this.
