### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by jmegner** [Kyrodan/KeeAnywhere#188]
(KeePass 2.43, KeeAnywhere 1.5.1)

I tried to add access to another Google Drive account, I gave my email address, password, and TOTP code, and then was given an error page saying:

> Sign in with Google temporarily disabled for this app
> This app has not been verified yet by Google in order to use Google Sign In.
![image](https://user-images.githubusercontent.com/539362/68516753-862aaa80-024a-11ea-97e1-b909a3fd39d6.png)

A friend got the same thing today.

**Edited to add...**

I also got this email from Google after the access failure:

>Remove risky access to your data
>Some apps or services you allowed to access your Google Account have not been verified by Google. Since they have extensive access to your personal information, you should remove their access unless you trust them.
>Review these apps and see other personalized security recommendations in the Security Checkup.
<img width="349" alt="google_email_keeanywhere_2019-11" src="https://user-images.githubusercontent.com/539362/68532512-a5294b00-02e3-11ea-9a71-7fd9b9f25577.png">

**Comment by julien040** [comment]
Same

**Comment by Halry** [comment]
Yes,I encountered this problem,too.

**Comment by Thacheman** [comment]
Same here (KeePass 2.43 - KeeAnywhere 1.5.1)

**Comment by Kyrodan** [comment]
I know, i am waiting for approval from Google. Please be patient, i will
let you know, if it works again.

Thacheman <notifications@github.com> schrieb am Sa., 9. Nov. 2019, 06:43:

**Comment by diesector2** [comment]
@Kyrodan Any news on when this might be approved? It seems to take a lot of time for just the app review, doesn't it?

**Comment by Kyrodan** [comment]
I'm working on that. I have to provide a homepage under my own second level domain with a privacy statement. After that the review has to be requested again. I'm so sorry for your inconveniences :-(

**Comment by Thacheman** [comment]
I understand, don't worry. I hope it will work soon ;-)

**Comment by Kyrodan** [comment]
Can you please check, whether it works now?

Thacheman <notifications@github.com> schrieb am Fr., 15. Nov. 2019, 22:27:

**Comment by diesector2** [comment]
@Kyrodan Thanks so much! It seems to be working now! I was able to add an GDrive account now.
Thank you for taking the time to sort this out :)

**Comment by dal55555moo** [comment]
sorry to add to a closed thread, not sure if that's proper etiquette or not on github. At any rate, I'm having this issue. I'm on version 2.45. Any tips on how to resolve?  Thank you
