### ISSUE TITLE
Google Drive auth fails when using security key

### ISSUE THREAD

**Issue by ayrtsia** [Kyrodan/KeeAnywhere#194]
Hello,

I have my Google account secured with a Google Titan key. When trying to add my drive account after entering my email/password I get a message saying "You can only use your Security Keys with Google Chrome."

**Comment by Kyrodan** [comment]
KeeAnywhere uses an embedded browser for authorizing an account. This embedded browser is based on system's Internet Explorer. Internet Explorer does not support FIDO-W3C-Hardware.

So currently there is nothing I can do for you, as long as #89 is not implemented.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
Your issue should be fixed there because KeeAnywhere now uses System's default browser.
