### ISSUE TITLE
Support for Nextcloud

### ISSUE THREAD

**Issue by craige1** [Kyrodan/KeeAnywhere#195]
For the people who want to use cloud like storage without the privacy issues of a public cloud, could support be added for clouds like nextcloud.

**Comment by Discostu36** [comment]
You don't need KeeAnywhere to access a .kdbx file stored on Nextcloud, the storage is accessible with HTTPS. Just open them the file with "open url". The URL should look like this:

https://1234.example.com/remote.php/webdav/example.kdbx

**Comment by Kyrodan** [comment]
@craige1 What @Discostu36 writes is correct. So closing this request.

**Comment by Kyrodan** [comment]
Added clarification to the FAQ-Section of the Homepage:
https://keeanywhere.de/use/faq

**Comment by RealDekkia** [comment]
It would still be nice to have webDAV support because KeePass does not support Database-Caching (as far as I know) but keeanywhere does.
