### ISSUE TITLE
How to uninstall old version?

### ISSUE THREAD

**Issue by chrilind** [Kyrodan/KeeAnywhere#197]
Is there a simple way to remove the previous version before installing the new one? I experience now two copies showing up under the tab "Tools" in KeePass. Both copies are showing the old version. Please advice on what to do.

**Comment by chrilind** [comment]
I just downloaded the zip file and installed v1.6. It still shows two copies under the Tools tab ... but now it is the correct version. How to fix so there is only 1 copy?

**Comment by Kyrodan** [comment]
"Uninstall" is simple: Just delete all "old" KeeAnywhere-PLGX-Files from your KeePass-plugin-Folder.

How do you "install" KeeAnywhere?
Using the PLGX-File or NUGET-Package.
Please do not use any DLL-Distributions. I only provide them for very special reasons.

**Comment by Federospo** [comment]
I have the same issue, but I had to install the 1.5.1 bug-fix version, and I cannot find any PLGX-file in the plugin folder. Instead I have a bunch of DLL files related to this plugin (KeeAnywhere.dll and Kyrodan.HiDrive.dll are quite talking names!)
Do I have to delete all and reinstall from scratch the single plugins?

**Comment by Kyrodan** [comment]
@Federospo If you do not have any other plugins installed and all the mentioned files are in the plugins folder => then please delete all of them and just copy the PLGX-File (a single file) to the plugins folder.
Details can be found here: https://keepass.info/help/v2/plugins.html

**Comment by Kyrodan** [comment]
Closed due inactivity.
