### ISSUE TITLE
KeeAnywhere - OneDrive - KeeAutoExec???

### ISSUE THREAD

**Issue by morrigan777** [Kyrodan/KeeAnywhere#198]
manually i can open the 2 databases from Onedrive, the issue I have in a combination with KeeAutoExec.
With KeeAnywhere the path looks like 
-	For gdrive: gdrive:///#NAME/#FOLDER1/#FOLDER2/#DBFILE.kdbx
-	For onedrive: onedrive:///#NAME/#FOLDER1/#FOLDER2/#DBFILE.kdbx
If I configure 
![autoopen](https://user-images.githubusercontent.com/7543135/72225538-e6113a80-3586-11ea-865a-7515357dd66a.png)

Why will gdrive work and onedrive will not?
![autoopen2](https://user-images.githubusercontent.com/7543135/72225541-eb6e8500-3586-11ea-87cc-895225e8033a.png)

**Comment by Kyrodan** [comment]
I have some questions to find a solutions:
* Can you open the Onedrive-Database with "Open from URL" if you do *not* use KeeAutoExec?
* Can you open the Onedrive-Database with the cloud drive file picker?
* If the formes is true, a history-enrtry was created in KeePass: can you use this to open the database?

**Comment by morrigan777** [comment]
-Can you open the Onedrive-Database with "Open from URL" if you do not use KeeAutoExec?
played a bit:  the following url's (conclusion url's are wrong)
  onedrive:///%userName%/Path/file.kdbx, 
  onedrive:///%userName%@outlook.com/Path/file.kdbx, 
All give error:
an exception occurred during a webclient request. Account "URL_ACCOUNT" for type onedrive not found

Url: onedrive:///%Display Name%/Path/file.kdbx gives error:
an exception occurred during a webclient request. One or more error occurred

- Can you open the Onedrive-Database with the cloud drive file picker?
using "open with cloud drive" yes it works
and when i hover over the db-tab i get onedrive:///%Display Name%/Path/file.kdbx

If the formes is true, a history-enrtry was created in KeePass: can you use this to open the database?
yes it works. entry looks like onedrive:///%Display Name%/Path/file.kdbx

Are there any examples of how it should work? Where do i fill what and what is mandatory or optional?

Whit these steps i was able to find out how it worked for gdrive, but can't seem to get it to work with onedrive.

one note: it is about onedrive from office365 Home, NOT onedrive for business.

thanks

**Comment by JanJenicek** [comment]
I encountered same behavior.

You can reproduce behavior from windows CMD execute following:
`"C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe" "onedrive:///%DisplayName%/onedrivePath/filename.kdbx"`

Perhaps you could cooperate with author of KeeAutoExec so the login information to onedrive would be passed from KeeAutoExec to KeeAnywhere directly. If it is necessary.

**Comment by morrigan777** [comment]
i believe KeeAutoExec is not working because the open from url is not working.

Can someone help me to get the open from url working with onedrive?

**Comment by JanJenicek** [comment]
Any news for this topic?

**Comment by morrigan777** [comment]
i finaly got open form url to work, don't ask me what's changed, maybe also an update.
If i use keepautoexec now, i get a pop-up "open from url" and have to hit ok.
That pop-up did not appear with google drive, and not really automatic if i have to hit ok.

but it is step in the right direction

**Comment by JanJenicek** [comment]
Thanks for the update, I have tested it and finally get it working more or less completely.

I had to use **Server credentials** options in KeeAutoExec plugin. Where I had to added string fields with my onedrive credentials as described in KeeAutoExec manual then it started to work.

I would still prefer to use option to always remember credential instead of storing them additionally in entries. But essentialy it is working now.

When opening database manually I'm not prompt to enter credentials. Only when opened from KeeAutoExec without those entries for user name and password.

**Comment by morrigan777** [comment]
I had not tried the server credentials again, but now it's ok (no pop-up).

i have one record with my onedrive account.
In the KeeAutoExec entry i do not use the real values, but reference to my onedrive entry.
This way i only have to manage the one main entry

**Comment by JanJenicek** [comment]
Good point, I was not aware or just forgot this feature. 

Thanks.

@Kyrodan I think this issue can be closed now.

**Comment by ValdarXY** [comment]
It took me a while to spot this...
please note the **triple** slash in onedrive:**///**%userName%/Path/file.kdbx

With that, it works like a charm, thanks!
