### ISSUE TITLE
api gateway the bucket you are attempting to access must be addressed using the specified endpoint

### ISSUE THREAD

**Issue by grootech** [Kyrodan/KeeAnywhere#199]
api gateway the bucket you are attempting to access must be addressed using the specified endpoint

why ?
need help

**Comment by Kyrodan** [comment]
Could you please give some more information: What is the issue? Is this an error report? What do you do (steps to reproduce), what does not work? Which provider are you using (AWS S3)? What are you trying to do?

**Comment by Kyrodan** [comment]
No action for a long time => closing.
