### ISSUE TITLE
incorrect URL display in the "Save to Cloud Drive" (to hubic) window

### ISSUE THREAD

**Issue by vmalguy** [Kyrodan/KeeAnywhere#20]
When I try to save my keeps file to hubic, the URL display on the bottom of the page seems strange.
Sure it work but it could be misleading for users.

<img width="603" alt="keeany_bug" src="https://cloud.githubusercontent.com/assets/10976404/12754855/3a06db4c-c9cd-11e5-8972-cd4817dcd37b.png">

**Comment by Kyrodan** [comment]
The screenshot could not be displayed - could you please readd it?

**Comment by vmalguy** [comment]
URL : hubic:///e e/
my hubic first name  and name is "e" :) (this is a testing account)

**Comment by Kyrodan** [comment]
Ok I see. It's the expected bahavior: all url fit to this scheme: {provider}:\\\{accountname}\{path in account}

To "beautify" this, you can rename your account in KeeAnywhere settings: just select an account and then click on the name again (no double-click, just slow single clicks) - you should now be able to edit the name. I will add this to documentation.

Remark: I just encountered a bug, when you don't chage the name, see #22.

**Comment by vmalguy** [comment]
ok, great work
