### ISSUE TITLE
Google Drive issue, can connect but not load 

### ISSUE THREAD

**Issue by sydios** [Kyrodan/KeeAnywhere#200]
Hello,

I can successfully connect the drive but when I try to load a file I get this error. Sorry for the german.

`Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentException: Invalid chars in path.
   bei KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   bei KeeAnywhere.CloudPath.GetExtension(String path)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

**Comment by Kyrodan** [comment]
Maybe duplicate of #91? 
Rename you account (see https://keeanywhere.de/use/advanced_topics, "Rename an Account) so it does not contain Umlaut.

**Comment by sydios** [comment]
No I don't have an umlaut in the name. But for testing, I changed it anyway but it didn't help.

**Comment by Kyrodan** [comment]
Maybe a slash in the path of the database?
Can you copy your database (or any other database) to the root folder and
test, wether you can open it from there?

Am Mo., 13. Jan. 2020 um 15:08 Uhr schrieb sydios <notifications@github.com

**Comment by Kyrodan** [comment]
Could you please use this test-build: this contains an extenden error message.

[KeeAnywhere-1.7.0-unstable.plgx.zip](https://github.com/Kyrodan/KeeAnywhere/files/4054011/KeeAnywhere-1.7.0-unstable.plgx.zip)

**Comment by sydios** [comment]
Thanks, with this version it told me which file on the drive had the issue in the name. I renamed it and now it works. Thanks a lot!

**Comment by Kyrodan** [comment]
Can you share, which character caused the issue?

sydios <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 16:35:

**Comment by sydios** [comment]
I really don't know because the name of the file looked pretty normal. This is what it was without the ""

"Kopie von Advanced Shotlist Template v1.4"

I deleted the file and then it worked.

**Comment by sydios** [comment]
This is the error message from your plugin: 
"System.ArgumentException: Invalid char in path 'Kopie von Advanced Shotlist Template v1.4
' at position 41: 10 (decimal)"

**Comment by sydios** [comment]
I downgraded to the stable version again, it works kind of. But it doesn't show all the folders. In the unstable version you send it works and I can see all the folders.

**Comment by Kyrodan** [comment]
In the unstable version this other issue is already fixed.

sydios <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 17:41:
