### ISSUE TITLE
Add webdav storage location in keeanywhere settings

### ISSUE THREAD

**Issue by khrel** [Kyrodan/KeeAnywhere#201]
Hello,

new feature request 

I know keepass is able to open databases via webdav URLs, but, if i use this vanilla feature, it lacks the offline sync ...

Could you think about adding "simple webdav" to the list of storage location available in keeanywhere and treat it just like the others (user/paswd) 

(or add nextcloud/owncloud storage provider)

Thanks

**Comment by Kyrodan** [comment]
As explained several times: no I will not - KeePass can handle it natively.

khrel <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 19:32:

**Comment by khrel** [comment]
> As explained several times

sorry for that ... 

I understand that keepass may sync the database locally in a temp folder when openning from a wedav storage ... but when offline i didn't find a way to open that last synced copy ...

nevermind, thanks for your answer ...

**Comment by Kyrodan** [comment]
Sorry for my rude reaction. It was not my intention to annoy you. I
understand that offline caching is an interesting part of this plugin -
beneath the file picker. And I already asked for integrating this into
KeePass itself (like KeePass2Android does).

Initially I wrote this plugin for my personal use and was overwhelmed of
it's success. Now I'm in the situation to maintain an active Open Source
project - which I really really love to. But my spare time is short, so I
often feel not be able to give the support that is "right". I have a kind
of responsibility for my happy users. So I have to decide things like this:
keep this plugin maintainable by myself - and clipping away these kind of
feature requests.

khrel <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 20:51:

**Comment by khrel** [comment]
no prob ... user requests on good program is a nether ending story ...
I think i will make the trick i need with a trigger to export "on open" to a local folder

Thanks again ;)
