### ISSUE TITLE
KeeAnywhere bug?

### ISSUE THREAD

**Issue by Gsuslu** [Kyrodan/KeeAnywhere#204]
Hello,

at home is working perfectly... I don`t know what can be the problem.

************** Texto de la excepción **************
System.ArgumentException: Invalid chars in path.
   en KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   en KeeAnywhere.CloudPath.GetExtension(String path)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4075.0 built by: NET48REL1LAST
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Versión del ensamblado: 2.43.0.18739
    Versión Win32: 2.43.0.0
    Código base: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4001.0 built by: NET48REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4042.0 built by: NET48REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4110.0 built by: NET48REL1LAST_B
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3761.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
KeeAnywhere
    Versión del ensamblado: 1.6.0.0
    Versión Win32: 1.6.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Versión del ensamblado: 4.2.29.0
    Versión Win32: 4.2.29.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Versión del ensamblado: 10.0.0.0
    Versión Win32: 10.0.3.21018
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Versión del ensamblado: 1.9.0.0
    Versión Win32: 1.9.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3761.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3928.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
KeePass.XmlSerializers
    Versión del ensamblado: 2.43.0.18739
    Versión Win32: 2.43.0.18739
    Código base: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Google.Apis.Drive.v3
    Versión del ensamblado: 1.34.0.1239
    Versión Win32: 1.34.0.1239
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Versión del ensamblado: 1.34.0.0
    Versión Win32: 1.34.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Versión del ensamblado: 1.34.0.0
    Versión Win32: 1.34.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Versión del ensamblado: 1.34.0.0
    Versión Win32: 1.34.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/jBkv2pTxABGDDMarGvaB/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3761.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by Kyrodan** [comment]
Which provider leads to this exception?

Gsuslu <notifications@github.com> schrieb am So., 19. Jan. 2020, 11:16:

**Comment by Gsuslu** [comment]
Google drive. I checked that there is any kind of strange chars like ?,%...

**Comment by Kyrodan** [comment]
This seems to be the same than in issue #200. Could you please try the
unstable build I provided there and report back the result of the extended
exception message?

Gsuslu <notifications@github.com> schrieb am So., 19. Jan. 2020, 11:42:

**Comment by Gsuslu** [comment]
Sure. Will do it now.

**Comment by Gsuslu** [comment]
************** Texto de la excepción **************
System.ArgumentException: Invalid char in path 'Copia de labnol's Gmail Unsubscriber
' at position 36: 10 (decimal)
   en KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   en KeeAnywhere.CloudPath.GetExtension(String path)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4075.0 built by: NET48REL1LAST
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Versión del ensamblado: 2.43.0.18739
    Versión Win32: 2.43.0.0
    Código base: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4001.0 built by: NET48REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4042.0 built by: NET48REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4110.0 built by: NET48REL1LAST_B
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3761.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
KeeAnywhere
    Versión del ensamblado: 1.7.0.0
    Versión Win32: 1.7.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Versión del ensamblado: 4.2.29.0
    Versión Win32: 4.2.29.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Versión del ensamblado: 10.0.0.0
    Versión Win32: 10.0.3.21018
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Versión del ensamblado: 1.19.0.0
    Versión Win32: 1.19.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3761.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3928.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
KeePass.XmlSerializers
    Versión del ensamblado: 2.43.0.18739
    Versión Win32: 2.43.0.18739
    Código base: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Google.Apis.Drive.v3
    Versión del ensamblado: 1.43.0.1800
    Versión Win32: 1.43.0.1800
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Versión del ensamblado: 1.43.0.0
    Versión Win32: 1.43.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Versión del ensamblado: 1.43.0.0
    Versión Win32: 1.43.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Versión del ensamblado: 1.43.0.0
    Versión Win32: 1.43.0.0
    Código base: file:///C:/Users/Puesto%201/AppData/Local/KeePass/PluginCache/PMbjnqmwHQdlBymqjjNW/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3761.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.


![image](https://user-images.githubusercontent.com/47099454/72679759-a381bd80-3ab2-11ea-82fb-9014ce4038d5.png)

**Comment by Gsuslu** [comment]
Deleting this archive is working. But is really weird that at home is working perfectly.

**Comment by Kyrodan** [comment]
I know, it's a weird behavior. But I'm getting closer to a solution.

Gsuslu <notifications@github.com> schrieb am So., 19. Jan. 2020, 12:01:

**Comment by Gsuslu** [comment]
Thank you very much for your help.
