### ISSUE TITLE
DPI scaling issue

### ISSUE THREAD

**Issue by vytux-com** [Kyrodan/KeeAnywhere#206]
When using this plugin on a high resolution screen (4K TV with Windows 10 screen scaling turned on to 200%) some of the KeeAnywhere dialogs are not sized correctly such as the one below

![image](https://user-images.githubusercontent.com/5370583/72845113-0614cc80-3cf2-11ea-9482-292579b8d634.png)

This makes it hard to select the correct item from the list

**Comment by Kyrodan** [comment]
Own control "ImageComboBox" does not respect DPI scaling. I will try to improve this.

**Comment by Kyrodan** [comment]
@vytux-com could you please try this unstable build and post the same image again?

[KeeAnywhere-1.7.0-unstable.plgx.zip](https://github.com/Kyrodan/KeeAnywhere/files/4108962/KeeAnywhere-1.7.0-unstable.plgx.zip)

**Comment by vytux-com** [comment]
This is a little better, the dropdown items no longer overlap
However the dropdown box itself is still a little too short both when closed and the dropdown only shows 2 items so could be made longer too
![image](https://user-images.githubusercontent.com/5370583/73305511-5a79f800-426e-11ea-9684-fee20dde5ce0.png)
![image](https://user-images.githubusercontent.com/5370583/73305552-6bc30480-426e-11ea-9452-0a3f906992a4.png)

**Comment by Kyrodan** [comment]
Okay, thank you for your feedback. I will continue investigating this.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
