### ISSUE TITLE
OneDrive no longer works for me

### ISSUE THREAD

**Issue by Saxonis** [Kyrodan/KeeAnywhere#208]
A few days ago my OneDrive password file cannot be retrieved from KeeAnywhere. The following message is displayed:

> Code: generalException
> Message: Unexpected exception returned from the service.

I'm using the latest version.

**Comment by 1zias01** [comment]
Same here.  Just updated to latest version of Keepass v2.44.  Then downloaded latest KeeAnywere v1.6

and got this too: 
![image](https://user-images.githubusercontent.com/651674/73141137-89198800-404e-11ea-8abd-4a4a09f51a9e.png)

**Comment by Kyrodan** [comment]
Hmm, I tried to reproduce it, but can't. I tried KeePass 2.43 and the latest 2.44 with KeeAnywhere 1.6.0.

Was this maybe a temporary issue? If not: Can you try to re-authenticate your account in settings (Select Account and Press Check-Button => if it fails KeeAnywhere requests to re-authenticate).

**Comment by Saxonis** [comment]
You're right. Checking and re-authenticating my account fixed the problem.

My error message was a bit different to 1zias01's screenshot though, as it did show the URI of my password file.
