### ISSUE TITLE
Local Backup does not work

### ISSUE THREAD

**Issue by xfilesee** [Kyrodan/KeeAnywhere#209]
I want to store database backups locally but keeanywhere does not store anything in the folder i pick.

p.s: i am using portable keepass

**Comment by Kyrodan** [comment]
Could you please explain a little bit more, what your settings and setup looks like.
Maybe append a screenshot of your settings?

**Comment by xfilesee** [comment]
![image](https://user-images.githubusercontent.com/18439149/73921340-2f2f8280-48d8-11ea-85eb-843177758e44.png)

I am using windows 10 and keepass 2.44

**Comment by Kyrodan** [comment]
That looks correct. I will try to reproduce this issue.

Just to clarify: local backups are only created, if the changed database
gets saved (in the cloud).

xfilesee <notifications@github.com> schrieb am Do., 6. Feb. 2020, 10:00:

**Comment by Kyrodan** [comment]
Ahhhhhh  one moment. Can you switch off offline caching and try again?

Daniel Bölts <daniel@boelts.de> schrieb am Do., 6. Feb. 2020, 10:23:

**Comment by xfilesee** [comment]
I tried disabling offline caching. still does not work.
![image](https://user-images.githubusercontent.com/18439149/73927156-e8df2100-48e1-11ea-8c33-7fff10d0036b.png)
I do not save anything in the cloud by the way.

**Comment by xfilesee** [comment]
Do not you think we should be able to use plugin to save only offline?

**Comment by Kyrodan** [comment]
The intention of this plugin is to use Cloud-Saved databases easily. Just
using the Backup-Mechanism is not the intention and does not work.
So what you describe is the expected behavior: local backup unly works for
cloud-based-databases.

Am Do., 6. Feb. 2020 um 11:10 Uhr schrieb xfilesee <notifications@github.com

**Comment by xfilesee** [comment]
How about save a copy of the offline database? There is another plugin for that but i thought your plugin would cover that.

**Comment by xfilesee** [comment]
When I do not enable automatic backup and click save what does happen?
Does it save the database to cloud?

**Comment by Kyrodan** [comment]
Very old issue - closed for cleanup-reason. Feel free to reopen, if it is still valid in latest version 2.1.0
