### ISSUE TITLE
Add periodical background synchronization

### ISSUE THREAD

**Issue by vmalguy** [Kyrodan/KeeAnywhere#21]
I share passwords with some of people. 
To do this, I setup a shared  cloud account where I store a kdbx.
We all setup our keepass to load this kdbx.
We are now able to use all the password stored in the kbdx.
We someone made a modification, everyone get the modification by using 'file>Synchronize>Recent Files>[the kbdx]'
For lazy people like me, i neap feature would be to configure KeePass to do a periodical background synchronization at a configurable interval to have modifications automaticaly available on my KeePass.

Thanks and keep up with this good work !

**Comment by Kyrodan** [comment]
I think it's possible to setup a trigger to automate the process. I don't think this is a feature for KeeAnywhere.
