### ISSUE TITLE
KeeAnywhere 1.6.0 incompatible with the current KeePass verison 2.44?

### ISSUE THREAD

**Issue by blueFire-BF** [Kyrodan/KeeAnywhere#210]
[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
...KeePass\PluginCache\1DrtdULcD8nsbKZ5k46A\KeeAnywhere.dll

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
Der Typ "Dropbox.Api.FileProperties.PropertyGroup" in der Assembly "Dropbox.Api, Version=4.0.0.0, Culture=neutral, PublicKeyToken=310f0e82fbb45d01" konnte nicht geladen werden.
mscorlib
   bei System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   bei System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   bei System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   bei KeePass.Plugins.PluginManager.CheckTypeRef(Module m, Int32 iMdToken)
   bei KeePass.Plugins.PluginManager.CheckRefs(Module m, Int32 iMdTokenType, GAction`2 fCheck)
   bei KeePass.Plugins.PluginManager.CheckCompatibilityPriv(Plugin p)
   bei KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)
Void ResolveType(System.Reflection.RuntimeModule, Int32, IntPtr*, Int32, IntPtr*, Int32, System.Runtime.CompilerServices.ObjectHandleOnStack)

[^] Details  [OK]

**Comment by Kyrodan** [comment]
Could you please describe the steps, that lead to this problem?
Or does this immediately pop up after you started KeePass?

**Comment by blueFire-BF** [comment]
Immediately with starting KeePass.
Even a dowegrad did not help.

I have one pc running KeePass I guess 2.43 and KeeAnywhere 1.6.0 with no problems.

And an other one with that Failure. After updating KeePass to 2.44. In this case a dowegrad is not solving the Problem.
(Deinstall KeePass 2.44 and install KeePass 2.43)

Thank you for your help! 

---- Daniel Bölts schrieb ----

**Comment by Kyrodan** [comment]
Plaease use PLGX-Distribution and clear plugin cache.
