### ISSUE TITLE
Can't connect to Dropbox

### ISSUE THREAD

**Issue by Jovial-Gent** [Kyrodan/KeeAnywhere#211]
Hello!

I can't connect to Dropbox, "Login" and "Google login" buttons at login page are inactive and unclickable

Other cloud services work fine.

KeePass 2.44
KeeAnyWhere 1.6.0
Windows 8.1

Please check it.

Thanks in advance.
![dropbox](https://user-images.githubusercontent.com/35640944/74141934-e6920500-4c08-11ea-9c52-a062f5df0ee7.jpg)

**Comment by alexonski** [comment]
Perhaps this issue is specific to Windows 8.1, as I have same problem on my windows 8.1 machine, but no problem on several Windows 10 machines.
Keepass 2.45
KeeAnyWhere 1.6.0

**Comment by BlueMM75** [comment]
Happens in Server 2012 R2 as well. Couldn't find a workaround. I wonder if it has to do with the version of Internet Explorer (or Active X control) included with these operating systems? Interestingly, you can't use shortcut keys to paste into the login fields, and when I right-click to paste (which works fine), the "Email" label inside the login field stays there. So it's like the page isn't recognising any input (whether pasted or typed).
Though I could copy the Dropbox authorisation URL used in the popup, and open in a browser & successfully login (though obviously the auth token never gets to Anywhere plugin).

**Comment by Kyrodan** [comment]
Please try latest build from #237.
