### ISSUE TITLE
Can't connect to google drive account

### ISSUE THREAD

**Issue by Turiok** [Kyrodan/KeeAnywhere#212]
Hello,

Thx for your plugin. 
I have a database on my google drive.

I installed in Keepass 2.44 portable and KeeAnywhere 1.60 on windows 10.
When I tried to configure my account. After google login and password. I have this screen in the pop up.
![Keeanywhere](https://user-images.githubusercontent.com/6814217/74187386-b704ec00-4c4c-11ea-85af-f3e15547b146.PNG)

I tried to connect to my google account with my firefox, chrome and internet explorer on the same laptop with success.

Searching on the web, I found several explanations but not solutions for me.
The user agent could be bad for google. 
Or my account would be too much secure.
https://support.google.com/accounts/thread/22873505?hl=en
But I already tried to enable "less security apps" settings without success.

**Comment by marcomsousa** [comment]
![image](https://user-images.githubusercontent.com/1110889/74341556-38bd5c80-4da8-11ea-82da-49ef6562c756.png)

For me the denied/allow button is disable.

**Comment by Turiok** [comment]
Hi,

Update info, I don't know why but now I have the same problem than @marcomsousa.
Maybe an application restart? A network configuration. I play a lot with my DNS recently.
But I had tested on other network with the same old result.
I tried to install another instance of keepaas with the same version.
And now two of them have the webpage open but I can't click on authorized button.

**Comment by marcomsousa** [comment]
The way to go is to implement this: https://github.com/Kyrodan/KeeAnywhere/issues/89#issuecomment-586282294

**Comment by xwitty** [comment]
I have the same issue:
* Google Drive access worked fine in the past
* now the same screen pops-up ([as listed above](https://user-images.githubusercontent.com/6814217/74187386-b704ec00-4c4c-11ea-85af-f3e15547b146.PNG))

**Comment by ops99** [comment]
MEE TO not work

**Comment by xwitty** [comment]
same issue for me!! Can't login to Google!
![2020-04-15 11_28_19-Window](https://user-images.githubusercontent.com/43315743/79322191-c20a2000-7f0c-11ea-86a5-3e11376c9949.png)

**Comment by kchenery** [comment]
Found a work around for this. Its a bit fiddly to do (and I'm basing this off memory so might be a bit off on the instructions)

You need to open Internet Explorer and grab the URL that KeeAnywhere is trying to use.  I think the Url is: `https://accounts.google.com/signin/oauth/oauthchooseaccount`

In IE open that URL and then make sure the compatibility settings for IE are disabled on that site. In my case I had to remove google.com from the list of sites to run in compatibility mode.

Then if you go back into KeeAnywhere it should allow you to sign in.

**Comment by DaftVader43** [comment]
"This browser or app is not secure" is **Google Account Dependant**
All of my G accounts except one can login via the KeeAnywhere Google Drive.

That rules out settings in Keepass or KeeAnywhere. Doesn't rule out API issues.

Sorry but I don't have a solution as yet

**Comment by coor** [comment]
Win 10 Chrome + Edge (IE11 disabled). "Agree" is greyed out. Custom URLs do not work.

**Comment by docfactory37** [comment]
I'm also having the same issue not able to cnnect to Google Drive :( 
![image](https://user-images.githubusercontent.com/20963053/83983450-e8c75e80-a971-11ea-881e-99e80334e491.png)

**Comment by Kyrodan** [comment]
Duplicate - move on to #241
