### ISSUE TITLE
Error when trying to open Dropbox database

### ISSUE THREAD

**Issue by KarlR83** [Kyrodan/KeeAnywhere#215]
I use Keepass and KeeAnywhere with 3 devices (2xWin10 and 1xAndroid). My Keepass database is on my dropbox drive to keep it synced.

All of the sudden KeeAnywhere stopped working on one of the Win10 device (the other Win10 and the Android are

 still working).
When KeePass starts and trying to open the database from dropbox, I get an error:

```
dropbox:///Hans Wurst/KP/kp.kdbx
Failed to load the specified file!
Ausnahmefehler während einer WebClient-Anforderung!
```
(Last sentence is in German, because my Win10 is German. It's says something about an Exception during WebClient Request.)

I checked all the settings, they are the same on both Win10 devices, also Keepass and KeeAnywhere versions are the same. Both devices are in the same network, but it also doesn't work if I connect the faulty device via LTE, so it's not a connectivity issue.

Any idea what goes wrong here? Can I somehow turn on debug mode and check a log file?

Thanks a lot!

**Comment by Kyrodan** [comment]
Is this still a problem? If yes, then please reopen this issue and update with further information.

**Comment by KarlR83** [comment]
I still get this error occasionally.
To fix it, I have to log into Dropbox on the same machine with a browser, then open keypass with the database loaded from that Dropbox, and it works.
Seems some kind of token expiration. Not sure if you can do something to fix this. I can work with the manual steps every few weeks
