### ISSUE TITLE
BOX - Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown

### ISSUE THREAD

**Issue by ACL0815** [Kyrodan/KeeAnywhere#217]
First, thank you fot this outstanding plugin! I love it!

The message "Error loading file list. Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown" is displayed when I do a check on the Box account that I had previously created. 

I can setup the access to the Box account fine and retrieve the KeePass database, work on it, save back to Box - no problem.

BUT In irregular intervals when i open the File i get the error message.

Workaround: Than i have to go manually in the KeeAnywhere menu klick on check and have to reenter the password and username.

I have that problem since i use the plugin (between 6 - 18 month). But i update it to one month ago to 1.6 and the problem is still there.

I would love if you are able to fix it, in one of the following ways:
1. That will don't happend again ;)
2. You save the password secure and autotype it in the loginscreen (If box.net ask again per design)
3. We get an login popup insted of the error message if we open the database (without the indirect way over the KeeAnywhere menu and check button)

KR Axel

**Comment by kibitzer** [comment]
I regularly experience this issue -- maybe once or twice a week?

**Comment by Kyrodan** [comment]
Issue #106 will fix this
