### ISSUE TITLE
google login not work new pc

### ISSUE THREAD

**Issue by ops99** [Kyrodan/KeeAnywhere#218]
i can not klick botton

https://imgur.com/p9MSytJ

**Comment by kins-dev** [comment]
I had a similar issue, resolved it via:

Open internet explorer (yes it must be IE)
Hit the gear and select Compatibility View Settings
Uncheck Display Intranet sites in Compatibility View

**Comment by Kyrodan** [comment]
Releases v2.0.0 today. This fixes your problem.
