### ISSUE TITLE
error message when connecting to dropbox

### ISSUE THREAD

**Issue by Trader6969** [Kyrodan/KeeAnywhere#219]
Hello everybody,

I use KeePass 2.44 Portable. For this I set up the KeeAnywhere-1.6.0 plug-in and configured it for a DropBox account. The connection works but when logging in via Open From Cloud Drive the error message comes: Exception error during a WebClient request. What can I do against it?

![image](https://user-images.githubusercontent.com/63540473/79067009-8aa53480-7cbc-11ea-8f9f-6cdf1109e0fa.png)

**Comment by Kyrodan** [comment]
Is this still a problem? If yes, then please reopen this issue and update with further information.
