### ISSUE TITLE
Login to google drive gives exception error

### ISSUE THREAD

**Issue by Bubischi** [Kyrodan/KeeAnywhere#220]
Hello,

I put my credentials in the setup, but when I try to open a kdbx file on google drive I get an exception error:

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentException: Invalid chars in path.
   bei KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   bei KeeAnywhere.CloudPath.GetExtension(String path)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
KeePass
    Assembly-Version: 2.44.0.19625.
    Win32-Version: 2.44.0.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4001.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
GoogleSyncPlugin
    Assembly-Version: 3.0.1.0.
    Win32-Version: 3.0.1.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/pu4MkG5dBCjieTCPAqS7/GoogleSyncPlugin.dll.
----------------------------------------
KeeAnywhere
    Assembly-Version: 1.6.0.0.
    Win32-Version: 1.6.0.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/KeeAnywhere.dll.
----------------------------------------
System.Net.Http.Primitives
    Assembly-Version: 4.2.29.0.
    Win32-Version: 4.2.29.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/System.Net.Http.Primitives.DLL.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 10.0.0.0.
    Win32-Version: 10.0.3.21018.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/Newtonsoft.Json.DLL.
----------------------------------------
Microsoft.Graph.Core
    Assembly-Version: 1.9.0.0.
    Win32-Version: 1.9.0.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/Microsoft.Graph.Core.DLL.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.Security
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll.
----------------------------------------
KeePass.XmlSerializers
    Assembly-Version: 2.44.0.19625.
    Win32-Version: 2.44.0.19625.
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
Google.Apis.Auth
    Assembly-Version: 1.16.0.0.
    Win32-Version: 1.16.0.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/pu4MkG5dBCjieTCPAqS7/Google.Apis.Auth.DLL.
----------------------------------------
Google.Apis.Core
    Assembly-Version: 1.16.0.0.
    Win32-Version: 1.16.0.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/pu4MkG5dBCjieTCPAqS7/Google.Apis.Core.DLL.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
Google.Apis.Drive.v3
    Assembly-Version: 1.34.0.1239.
    Win32-Version: 1.34.0.1239.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/Google.Apis.Drive.v3.DLL.
----------------------------------------
Google.Apis
    Assembly-Version: 1.34.0.0.
    Win32-Version: 1.34.0.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/Google.Apis.DLL.
----------------------------------------
Google.Apis.Core
    Assembly-Version: 1.34.0.0.
    Win32-Version: 1.34.0.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/Google.Apis.Core.DLL.
----------------------------------------
Google.Apis.Auth
    Assembly-Version: 1.34.0.0.
    Win32-Version: 1.34.0.0.
    CodeBase: file:///C:/Users/Andre/AppData/Local/KeePass/PluginCache/1DrtdULcD8nsbKZ5k46A/Google.Apis.Auth.DLL.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by fetttobse** [comment]
I have the exact same issue when trying to open a database from Google Drive. Newest version of KeePass and KeeAnywhere installed. As my existing KeePass database is already located on Google Drive there is no alternative.

**Comment by Kyrodan** [comment]
There are invalid chars in path or account name.
Try using pre-release-version from #91 and re-check with extended error message.
