### ISSUE TITLE
I'm not able to open database from Google Drive

### ISSUE THREAD

**Issue by iklymenko** [Kyrodan/KeeAnywhere#222]
1. For some reason, not all the files and folders are listed after I have added my account. I had to restrict permissions to not share the folder to have it appear in the list.

2. When I try to open a file from the folder it shows me a popup that tells: "Failed to load the specific file!". I'm an owner of both file and folder. 

![image](https://user-images.githubusercontent.com/3464988/83628257-dc718900-a5a0-11ea-8187-290088c0abf0.png)

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
Please test it with this version. If you problem still appears, please re-open this issue.
