### ISSUE TITLE
[Amazon S3] - Cannot open bucket and acces db file (The bucket you are attempting to access must be addressed using the specified endpoint.

### ISSUE THREAD

**Issue by fab2bx** [Kyrodan/KeeAnywhere#224]
OS : Win 10 enterprise 2016 - v1607
keepass version : v2.44 portable
KeeAnywhere version : v1.6.0.0

When i test the connection its OK. I can see my bucket but when in try enter in it to select the specific folder i have created inside (//bucket/keepass_folder/keepass_file.kdbx) i have an error : The bucket you are attempting to access must be addressed using the specified endpoint.

I am using my principal user on S3 with full access rights.

![KeeAnywhere - S3 issue - 01](https://user-images.githubusercontent.com/66563053/83975051-d1e12780-a8f1-11ea-953d-b37d00dbffc5.png)

![KeeAnywhere - S3 issue - 02](https://user-images.githubusercontent.com/66563053/83975065-e7eee800-a8f1-11ea-860f-02cc13c863ff.png)

any idea ?

Thks, Fab.

**Comment by Kyrodan** [comment]
@fab2bx 
The Bucket "backup-foto-fab2" does not belong to the region you registered for this S3 account.
