### ISSUE TITLE
[Amazon Drive] Can't Add Amazon Drive

### ISSUE THREAD

**Issue by Lighsark** [Kyrodan/KeeAnywhere#225]
OS：Windows 10
Keepass ver. 2.45
KeeAnywhere 1.60

![2020-06-14_14-05-31](https://user-images.githubusercontent.com/40225316/84586243-511eb000-ae4a-11ea-8e98-ec2f51bf4b8b.png)

After clicking "Allow", I get

![2020-06-14_14-07-23](https://user-images.githubusercontent.com/40225316/84586068-a1950e00-ae48-11ea-8766-7c59c15e7450.png)

No account is added successfully. It just stay on that page.
Plearse help. Thanks.

**Comment by NoobMaster1999** [comment]
Ok I am trying to fix it

**Comment by NoobMaster1999** [comment]
Okk the thing is it is a bug which is now when I write this message. You try again and now it is fixed

**Comment by wael3l** [comment]
i have the same error and i have installed the newest version of the software and still got the same bug. i would appreciate the help

**Comment by Kyrodan** [comment]
Amazon has decided to not support other parties to use/access Amazon Drive anymore. It worked just because they kept it intact for some time.

It seems it is not the case anymore, so I think I will completely remove Amazon Drive support.
