### ISSUE TITLE
Google Drive 6 folders limit

### ISSUE THREAD

**Issue by ultimus247** [Kyrodan/KeeAnywhere#226]
It seems on multiple computers and with both my wife and I using this we see the first 6 folders but no more when trying to browse the contents of our google drive for the keepass files.

**Comment by brokenfan88** [comment]
May be related but I am not able to browse more than 13 folders in google drive. It does not seem to be the first 13 alphabetically either, but rather 13 random folders out of about 20. This is on a fresh install of the latest versions of keepass/keeanywhere on a fresh install of windows 10 fully updated.

**Comment by mattgyver-it** [comment]
This is happening to me, as well, with regards to 13 non-sequential folders. If my KeePass folder would show up, I'd be golden. But of course, it's got a bunch before, and a bunch after.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
I fixed a bug regarding this issue.
