### ISSUE TITLE
"Couldn't sign you in" GDrive error

### ISSUE THREAD

**Issue by alabamatoy** [Kyrodan/KeeAnywhere#227]
Open Keeanywhere settings, click on ADD, choose GOOGLE DRIVE, enter my email address, and I click NEXT and I get the following:

![keeanywhere](https://user-images.githubusercontent.com/28680526/89344153-70300600-d673-11ea-93c8-e34fa5bc38dd.png)

Any assistance would be appreciated.

![image](https://user-images.githubusercontent.com/28680526/89344243-95247900-d673-11ea-90bd-72a6e59f425b.png)

**Comment by flochy** [comment]
Same error for me.

**Comment by imnotyourson** [comment]
I am also running into the same issue as alabamatoy, anyone can help?

**Comment by flochy** [comment]
Apparently it has been fixed ! At least, it's working for me today.

**Comment by alabamatoy** [comment]
Still same error for me.  So its not been fixed AFAICT.

**Comment by ErikAnderson3** [comment]
Same problem here.  Checking for updates appears to work in KeePass.

Poking around, it seems like the core issue is that this KeeAnywhere window for logging into Google Drive is a spawned instance of Internet Explorer.  Google Drive requires JavaScript, and it seems like JavaScript is not enabled in this IE instance.

**Comment by ErikAnderson3** [comment]
FWIW, using KeePass 2.46 portable, KeeAnywhere 1.6.  I also have the KeePassHttp v 1.8.4.2 plugin installed, just on the off chance that this is a factor.

**Comment by alabamatoy** [comment]
"KeeAnywhere window for logging into Google Drive is a spawned instance of Internet Explorer". This must be fixed.  It should use whatever browser is set as default.  IE is at or beyond end of life and many Windows boxes are now being deployed without it.

**Comment by Kyrodan** [comment]
Hi,

the used Browser is the Internet Control which is part of .NET. Even if
Internet Explorer ist not "installed" this Control is based on it and will
continue to work.

Nevertheless I plan to abandon the internal browser window and use systems
default browser. This will lead to a changed user flow. There is no
concrete time frame.

What I do not understand is, that this simple login is nowadays so
complicated, that a simple browser is not able to serve this anymore.



alabamatoy <notifications@github.com> schrieb am Do., 1. Okt. 2020, 12:53:

**Comment by nascentt** [comment]
Anyone got a workaround until this is fixed long-term?
I can't not have access to my passwords for months.

There's no link to copy to another browser

**Comment by Kyrodan** [comment]
Desperately there is no good workaround.
What you can do:
* install GDrive Sync-Client and use the Database inside the (local) Sync
Folder
* Download database locally and use it there.

I'm sorry for your inconvenience.

Am Fr., 29. Jan. 2021 um 08:59 Uhr schrieb nascentt <
notifications@github.com>:

**Comment by vidlaque** [comment]
Hello everybody

@Kyrodan Is there already a time plan to fix this issue (abandon internet explorer) ?
btw: thanks for this great piece of software!

**Comment by Kyrodan** [comment]
I'm still alive and already working on a fix. Hopefully you all can do some first tests very soon.

**Comment by Kyrodan** [comment]
Duplicate - move on to #241
