### ISSUE TITLE
Auto Backup not work

### ISSUE THREAD

**Issue by Schrotty74** [Kyrodan/KeeAnywhere#228]
I use latest Keepass Portable and i have install the plugin and connect with Google Drive and select Backup to Remote and Backup to Local but the Plugin make no backups.

![2020-08-05_101003](https://user-images.githubusercontent.com/25227541/89388234-07dd3500-d704-11ea-9f26-80b4aa558c50.png)

![2020-08-05_101012](https://user-images.githubusercontent.com/25227541/89388254-0f044300-d704-11ea-9d85-27cfaca8eed8.png)

**Comment by Kyrodan** [comment]
If I remember right there exists a bug regarding havin both options
switched on. If you have only one switched on, then it works.

Am Mi., 5. Aug. 2020 um 10:12 Uhr schrieb Scoty43 <notifications@github.com

**Comment by Scoty43** [comment]
I have switch to one only but also not work. There is no backup on Google Drive.

**Comment by pizu** [comment]
yeah, same issue :(

**Comment by Kyrodan** [comment]
Maybe it's fixed in v2.1.0
