### ISSUE TITLE
Error when special characters are in filenames

### ISSUE THREAD

**Issue by Kyrodan** [Kyrodan/KeeAnywhere#23]
Error when Quotation Marks are in filenames.

**Comment by Kyrodan** [comment]
Same for hubiC. 
In OneDrive and Dropbox quotation marks in filenames are forbidden.

Investigation for other special characters pending.

**Comment by Kyrodan** [comment]
Need to implement special characters handling for all providers.

**Comment by Jas0nGER** [comment]
Sorry, but this issue still exists. I'm using Keepass 2.34 and the newest version of Keeanywhere. If I have some datafiles in my root directory of google drive I got the error.
After I'd pulled all files into a directory it works normally. But until now I can't say which character leads to the issue. There are only some with - or _.

**Comment by Kyrodan** [comment]
@Jas0nGER: Do you get an Exception? If yes, please post it here, so I can take a look at it.

**Comment by Jas0nGER** [comment]
@Kyrodan Yes it is the same as shown in #38 

I tested a little bit moving files with starting "~", empty spaces, no extensions or "äüö" to my root directory but it worked always. Only if I move all the files to the root the error occures. Could it be related to the amount of files stored in the root directory?

**Comment by Kyrodan** [comment]
@Jas0nGER: I will check, whether it could be related to items in root folder only (many items or illegal characters).
