### ISSUE TITLE
Don't block viewing of the database to sync. Only block upon editing

### ISSUE THREAD

**Issue by TomsonBoylett** [Kyrodan/KeeAnywhere#230]
This is more noticeable on slower connections but this plugin can add a lot of wait time to open the database while it is syncing. I think a better trade-off is to show the database contents straight away, sync in the background, and only when you go to edit an entry do you freeze the window.

This implementation could potentially show you outdated information but for me in the majority of cases there are no changes or the entry I'm trying to access hasn't changed. I think if you make it clear it is syncing in the background in the UI you could mitigate this issue.

Edit: Some easier alternatives is to have a configurable timeout after which we give up syncing. Or having some button to click to skip syncing.

Edit 2: Lets say we are viewing the database and then while interacting with an entry it finishes syncing. I feel it would be challenging to update all the entries etc without interrupting the flow of the user. I still think it's worth considering some of the simpler alternatives as currently the timeout is set to be infinite allowing the application to hang for a very long time on slow connections.

**Comment by Kyrodan** [comment]
Syncing (and UI blocking) is done by KeePass itself. I have no possibility to change this.
