### ISSUE TITLE
KeeAnywhere extremly slow since w10 2004 ?

### ISSUE THREAD

**Issue by pfoucray** [Kyrodan/KeeAnywhere#231]
Hey,

thx for doing that great tool.
It seems on my pc that keeAnywhere has become very slow since 2004 update.
I unistalled completly keepass the plugin.
Re-installed 2.45 and 1.6.0.
Re configured the access to gDrive, re-authorized access (was very long too, each step).

Still, it takes up to 10 minuts to load the .kdbx from gDrive
![image](https://user-images.githubusercontent.com/16115517/91663373-a46adb00-eae8-11ea-8b55-0cc3ae38e2b7.png)

I don't have any specific AntiVirus. Just basic default windows 10 configuration.

using keepass + keeAnywhere on other w10 1909 machines, Android. Works like a charm.

dunno if there is anything to do code wise. Hope that will not happen to everyone updating their Windows OS

Regards,
PF

**Comment by trissi1987** [comment]
I am also running into the same issue as pfoucray, anyone can help?

**Comment by adoucette** [comment]
I also have the issue, but using KeeAnywhere with OneDrive. Saving/synchronizing the database takes about 6-10 seconds now. It used to be <1 second.

**Comment by auanasgheps** [comment]
I can confirm the issue on Windows 10 2004 and Google Drive, although I don't know if its' caused by 2004. Saving is terribly slow as I mentioned in #242

**Comment by adoucette** [comment]
I'm on KeePass 64bit ver 2.47, and using Windows 10 Pro Version 20H2 (OS build 19042.746), and still having the same issue.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
Is this problem gone with this update? If not: please re-open this issue.
