### ISSUE TITLE
Issue when opening a shared keepass file in gdrive

### ISSUE THREAD

**Issue by vdrmrt** [Kyrodan/KeeAnywhere#232]
User A shares a keepass file with user B in gdrive and user B creates a shortcut to this shared keepass file.
When user B tries to open this shared keepass file with KeeAnywhere, user B get's the following error.

![image](https://user-images.githubusercontent.com/71460525/93509908-ade5a700-f920-11ea-8a75-23c4382457c2.png)

**Comment by Grizzly90** [comment]
please fix this
:(
