### ISSUE TITLE
KeeAnywhere cant open embeded browser

### ISSUE THREAD

**Issue by IRetEst** [Kyrodan/KeeAnywhere#240]
I keep getting a message requesting me to install a compatible browser to add drobox synchronization. The message request me to install compatible browsers: safari, chrome, firefox and edge. I have firefox and edge installed.
I tried to set firefox and edge as default browser and even uninstall any other browser I had installed in the system without success.
I have the plugin working correctly in other systems.
![imagen](https://user-images.githubusercontent.com/10964436/104440964-52a48800-5593-11eb-8dce-e28630f1907e.png)

**Comment by evlo** [comment]
https://github.com/Kyrodan/KeeAnywhere/issues/237

**Comment by RicardoCapricciosa** [comment]
I have the exact same issue. I recently reinstalled Windows 10 Pro, but I'm not sure if the problem only came after it, because I really did not do this setup for a very long time, it just worked.

**Comment by Kyrodan** [comment]
Duplicate of #237
