### ISSUE TITLE
Keepass 2.47 reporting that KeeAnyWhere 1.6.0 is not compatible anymore

### ISSUE THREAD

**Issue by marcelser** [Kyrodan/KeeAnywhere#243]
Please update KeeAnywhere to make it compatible with latest KeePass. It reports at startup that plugin is no longer compatible and we should obtain newer one although it still perfectly works.

**Comment by A12341A** [comment]
Reinstall Keepass and Keeanywhere (delete it) and try again. Once the error came for me. Reinstalling the plugin and Keepass solved it for me.

**Comment by nascentt** [comment]
I had the same issue just now.  I was able to fix it with the solution in the similar issue #141

**Comment by Kyrodan** [comment]
Please use PLGX-Distribution and/or delete plugin cache as mentioned by @nascentt

**Comment by marcelser** [comment]
I was using plgx distribution always and I now deleted plugin cache but still I get that message but only once. If you restart KeePass the message is gone and plugin is loaded. But deleting the plugin cache is what actually triggers the error btw it does not solve it at all. Clear plugin cache and have KeePass recompile the plugins and then the error appears.

And the solution mention in #141 of copying some dll's and other stuff I think is not really a viable solution.

As I can use the plugin when I restart Keepass I don't think it's super urgent but I'm 100% sure that there's a bug in this plugin otherwise KeePass would not complain about it when recompiling it.
