### ISSUE TITLE
Feature Request: nonAWS S3

### ISSUE THREAD

**Issue by kwehrle** [Kyrodan/KeeAnywhere#244]
Hi Kyrodan,
there are some AWS S3 compatible providers around(e.g. IONOS enterprise has one). At then moment KeeAnywhere isn't able to define an endpoint other than AWS - or to be exact, this endpoint is implicitly set/not needed for AWS S3.

Maybe this would be an idea to extend S3 to nonAWS providers. Or is a already possible and I didn't find the documentation?

Greets Knut

**Comment by Tupsi** [comment]
Your not the only one searching for that option, but atm it is not present. The aws URL are hardcoded. We would need an option in the settings for our own base url. See #130

**Comment by Kyrodan** [comment]
@kwehrle @Tupsi 
Please try Beta-Build from here: https://github.com/Kyrodan/KeeAnywhere/issues/252#issuecomment-782150223

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
