### ISSUE TITLE
Add "Save Copy to Cloud Drive" support

### ISSUE THREAD

**Issue by ebekker** [Kyrodan/KeeAnywhere#25]
Similar to the way "Cloud Drive" has been added as a source for "File > Open" and a destination for "File > Save As", add support for "File > Save As > Save Copy to Cloud Drive".

**Comment by Kyrodan** [comment]
I ommited it beacuse in KeePass itself there is no "Save copy to URL" (and KeeAnywhere has a tight integration to the "Open/Save URL" feature). 

But if it makes sense for you, I think it could be implemented.
