### ISSUE TITLE
Dropbox profile not work with Google Chrome Developer Edition

### ISSUE THREAD

**Issue by betagoo** [Kyrodan/KeeAnywhere#253]
I use Google Chrome Developer Edition browser.
Dropbox profile not work with Google Chrome Developer Edition
After click ADD -> Dropbox, plugin display this error:
Upgrade your browser to use Dropbox
Your current browser is not supported. We support the latest versions of the following browsers: Edge Chrome Firefox Safari

**Comment by Kyrodan** [comment]
This is known and currently in Fixing vor next Version 2.0. You can try
this beta release here #251.

betagoo <notifications@github.com> schrieb am Do., 18. Feb. 2021, 07:22:
