### ISSUE TITLE
HiDrive: Cannot sync / save KeePass file

### ISSUE THREAD

**Issue by jaceeea** [Kyrodan/KeeAnywhere#255]
Hi,

I can open files from HiDrive without problems but when I want to save / synchronize the database, I get these two windows:

![F22C5471-A86A-4983-88A4-DC79C6A06528](https://user-images.githubusercontent.com/79337350/108562138-b2632100-72ff-11eb-886c-741d507ba877.jpeg)

Would be really great if you can point me to the resolution.

thanks
jake

**Comment by Kyrodan** [comment]
Is your database in root folder? Please use a subfolder for testing. If I remember right, there is an issue with that.

**Comment by Kyrodan** [comment]
BTW: which version are you using? The last beta from #252?

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
Please delete your HiDrive account from KeeAnywhere Settings and recreate the account.
Reopen this issue, if your problems still appear.
