### ISSUE TITLE
DropBox : access_token_expired

### ISSUE THREAD

**Issue by Fillonj** [Kyrodan/KeeAnywhere#256]
Hi, im using Dropbox(free 2GB) as cloud provider for a database synced using with Keepass/KeeAnywhere and Keepass2Android.
Everyday when i open KeePass i got an error : access_token_expired
The database is then opened with local cache, so i must renew the token with tools > KeeAnywhere > dropbox account > check.

Is there a way to increase the TTL ? I didn't seen any option in dropbox. Anyone facing the same problem ?

Im using : 
KeeAnywhere-2.0.0-unstable
KeePass 2.47
KP2Android

Thanks
Johan

**Comment by Kyrodan** [comment]
@Fillonj Which 2.0.0-unstable-Version are you using? This problem is known and (hopefully) already fixed in another 2.0.0-unstable.
Please try the latest unstable from #252 and report back here.

**Comment by Fillonj** [comment]
@Kyrodan Thx, i was using KeeAnywhere-2.0.0-unstable-20210204.plgx, I will try dist-20210219.zip asap.

**Comment by Kyrodan** [comment]
Okay, I'm sure has been fixed after 2021-02-04 - ich think it was four days after that ...-08.
I close this here, if you still encounter problems, feel free to reopen this again.
