### ISSUE TITLE
Google  Sync Insecure Browser error

### ISSUE THREAD

**Issue by blissfulrockslide** [Kyrodan/KeeAnywhere#258]
When trying to setup a sync, the window that opens up to allow a google account sign in is marked as "insecure", and google will not let you continue the sign in process
![image](https://user-images.githubusercontent.com/49246330/109378413-23b64d00-7887-11eb-8cc8-c64fd2f2654d.png)

**Comment by blissfulrockslide** [comment]
Refreshing doesn't work, ofc.

**Comment by Kyrodan** [comment]
See #252

blissfulrockslide <notifications@github.com> schrieb am Sa., 27. Feb. 2021,
08:06:

**Comment by KevCo89** [comment]
I got the same message, cannot sign in to Google account.

**Comment by crakerjac** [comment]
Same issue.  Following. Seems related to:
https://github.com/keeweb/keeweb/issues/1359
