### ISSUE TITLE
Unsupported Browser when adding Dropbox account

### ISSUE THREAD

**Issue by TheDezperado** [Kyrodan/KeeAnywhere#259]
When choosing to add an account and then selecting Dropbox, the browser window states that the current browser is unsupported. 

![kperror](https://user-images.githubusercontent.com/79878268/109568635-31e9b080-7ab5-11eb-94d8-2de88229c618.JPG)

**Comment by Kyrodan** [comment]
See #252 for temporary solution.

**Comment by TheDezperado** [comment]
> See #252 for temporary solution.

Thanks for pointing me that way, the 20210204 build did the trick. I appreciate all the work you've put into this plugin, thanks again!
