### ISSUE TITLE
AWS S3 support

### ISSUE THREAD

**Issue by ebekker** [Kyrodan/KeeAnywhere#26]
Add support for [AWS S3](http://aws.amazon.com/s3/) as a cloud storage back-end.

I know that this comes close to violating one of the [Blacklisted Feature](https://github.com/Kyrodan/KeeAnywhere/wiki/Contributing#blacklisted-features) rules, since you would need to give them a CC to open up an AWS root account, but you wouldn't necessarily be charged anything under the [free tier](http://aws.amazon.com/s3/pricing/).

Assuming this is something that you would consider adding support for...

* The developer documentation can be found [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html).
* I'm a developer and would be willing to contribute the actual implementation.

**Comment by Kyrodan** [comment]
Just to clarify the intent of the "blacklistet features": I do not want to get in a "pay-dependency" for features I do not use by myself only for the purpose that others can use it.

Is the AWS account only required for testing the feature by me or is it necessary to have an account to get a kind off "app key" (like in OAuth) which needs to be compiled into KeeAnywhere? 

If it's only required for testing and I do not need to pay for it after one year free period and KeeAnywhere (with this provider) can still be used, I think this might be okay and I welcome your pull request for that.

**Comment by Kyrodan** [comment]
Hi @ebekker,

here is a Developer Snapshot of this feature. Could you please try it, whether it fits to your needs?
**Be aware: THIS SHOULD NOT BE USED PRODUCTIVE**

https://dl.dropboxusercontent.com/u/68134839/KeeAnywhere-1.3.0-unstable.plgx
https://dl.dropboxusercontent.com/u/68134839/KeeAnywhere-1.3.0-unstable.zip#

Regards,
Daniel
