### ISSUE TITLE
possible new issue - GDrive

### ISSUE THREAD

**Issue by alabamatoy** [Kyrodan/KeeAnywhere#260]
![keeanywhere](https://user-images.githubusercontent.com/28680526/109978192-3c799500-7cc3-11eb-9ad2-b3cae3342391.jpg)
Is this something on my end or a new issue?

**Comment by Kyrodan** [comment]
@alabamatoy 
* Which version are you using? 
* Have you tried to re-authenticate?

**Comment by alabamatoy** [comment]
Drop this one.  After repeated reboots, updates, even reinstalls through which the error persisted, it is suddenly working again.  Apologies for wasting your time.
