### ISSUE TITLE
KeeAnywhere ne fonctionne plus incompatible avec les derniere versions de dropbox ou GDrive 

### ISSUE THREAD

**Issue by docelto** [Kyrodan/KeeAnywhere#263]
Quand on veut charger dropbox ou gdrive ...un message repond que la version de notre navigateur n'est pas actualisé, fenetre envoyée par le navigateur. La reinstallation complete de keepass et keeanywhere n'y change rien.

**Comment by Kyrodan** [comment]
Please See #252

docelto ***@***.***> schrieb am Di., 9. März 2021, 22:45:

**Comment by tomg1970** [comment]
Hallo, ich habe aktuell das Problem, das ein Datenbanksync über Dropbox nicht möglich ist? Ist das schon bekannt oder liegt das an der Dropbox API?

**Comment by Kyrodan** [comment]
Ist schon bekannt, schaue in #252 für eine Beta-Version.

tomg1970 ***@***.***> schrieb am So., 14. März 2021, 19:56:

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
