### ISSUE TITLE
Zaloguj się przez Google

### ISSUE THREAD

**Issue by Marcin-esz** [Kyrodan/KeeAnywhere#264]
Problemy z logowaniem do Google Drive na Windows 10. 
Nie udało się zalogować
Ta przeglądarka lub aplikacja może nie być bezpieczna.
Spróbuj użyć innej przeglądarki. Jeśli już używasz obsługiwanej przeglądarki, możesz odświeżyć ekran i ponownie spróbować się zalogować.

![Zrzut ekranu 2021-03-10 202618](https://user-images.githubusercontent.com/22896955/110685781-efc01d80-81de-11eb-825d-e60c3e857390.png)

**Comment by Kyrodan** [comment]
See #252.

Marcin Szewczyk ***@***.***> schrieb am Mi., 10. März 2021,
20:29:

**Comment by hstracker90** [comment]
I have the same problem, I cannot access my keepass file hosted on Google Drive.
Please make Google Drive accessible again. Thank you.

**Comment by Kyrodan** [comment]
see #252

hstracker90 ***@***.***> schrieb am Fr., 12. März 2021, 18:58:

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
