### ISSUE TITLE
KeeAnywhere Translations

### ISSUE THREAD

**Issue by wanderleihuttel** [Kyrodan/KeeAnywhere#265]
Hello @Kyrodan

There is some plans for translate KeeAnywhere? I would like to translate for Portuguese Brazilian (PT-BR).

Thanks

**Comment by wanderleihuttel** [comment]
Anything about @Kyrodan ?

**Comment by Kyrodan** [comment]
I'm sorry, I don't think I would implement this. Currently KeePass does not
support translations for plugins the same way as for KeePass itself. So
there is no really "clean" way of doing this.

Am Do., 8. Apr. 2021 um 12:49 Uhr schrieb Wanderlei Hüttel <
***@***.***>:
