### ISSUE TITLE
KeeAnywhere v1.6.0 not compatible with KeePass 2.47r2

### ISSUE THREAD

**Issue by bee-am** [Kyrodan/KeeAnywhere#266]
I'm getting the following error message since updating to KeePass Pro Portable 2.47 Rev 2:

`The following plugin is incompatible with the current KeePass version:`
`- KeeAnywhere.dll`

**Comment by Kyrodan** [comment]
Please use PLGX-Distribution. A DLL-Release is always "pinned" to a specific KeePass-Version.

Btw.: try v2.0-unstable/Beta-Release from #252, if you encounter Browser-Issues.

**Comment by bee-am** [comment]
@Kyrodan Thank you for the feedback - however I'm getting this error with the .plgx distribution, not the .dll release. The same error appears with v2.0, although it does refers to an incompatible .plgx and not .dll

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
Please make sure at least .Net Framework 4.6.1 is installed. If your problems are still valid, please reopen this issue.
