### ISSUE TITLE
Error when using Google Drive

### ISSUE THREAD

**Issue by Lightningblade** [Kyrodan/KeeAnywhere#267]
Related: #260

Same error. When I removed the account to add it again the browser (Internet explorer) that opens showed me this:

![image](https://user-images.githubusercontent.com/30607152/112320004-e63eb700-8cae-11eb-9879-aac6f36ae415.png)

Is it possible to use edge instead now since google doesn't accept IE anymore apparently.

**Comment by Kyrodan** [comment]
see #252 for a beta-Release.

Am Mi., 24. März 2021 um 14:41 Uhr schrieb Lightningblade <
***@***.***>:

**Comment by Lightningblade** [comment]
Sorry, tried various search strings but i see the text in that issue is in a picture.
