### ISSUE TITLE
AWS s3.amazonaws.com - SSL certificate issues

### ISSUE THREAD

**Issue by rvinothkannan** [Kyrodan/KeeAnywhere#27]
We  are recently having multiple issues like connection reset using the Amazon URL s3.amazonaws.com and this has been caused due to the SSL intermediate certificate change from Amazon. We noticed this is the second time Amazon updating the certificate which triggered connection reset issue. We are aware this is due to recent security fixes. After importing the root and intermediate certificates the issue got resolved. We are using JDK 1.6 for our application server. Does anyone having similar issue with s3.amazonaws.com and how to resolve this proactively.

**Comment by Kyrodan** [comment]
As KeeAnywhere does not have an AWS-Provider this is not an issue and will be closed.
