### ISSUE TITLE
S3 bucket with object lock enabled can't be used

### ISSUE THREAD

**Issue by mabatko** [Kyrodan/KeeAnywhere#270]
When I try to save database on S3 bucket which has object lock enabled (compliance mode), it fails with error:
![kp](https://user-images.githubusercontent.com/41372990/113830764-39246e00-9787-11eb-8e71-d57486205691.PNG)

The reasoning for using object lock is to protect keepass database and all its previous versions from accidental or malicious deletion.

**Comment by Kyrodan** [comment]
Is this still relevant or can this be closed?

**Comment by Kyrodan** [comment]
Okay, thnaks for your reply, so I close this.
