### ISSUE TITLE
connexion with dropbox

### ISSUE THREAD

**Issue by E-CDR** [Kyrodan/KeeAnywhere#271]
I have the same message

Actualisez votre navigateur pour utiliser Dropbox
Votre navigateur actuel n'est pas pris en charge. Les versions les plus récentes des navigateurs suivants sont prises en charge :
Edge
Chrome
Firefox
Safari

**Comment by Kyrodan** [comment]
see #252: a beta-2.0.0 is available.

Am Do., 8. Apr. 2021 um 14:58 Uhr schrieb E-CDR ***@***.***>:

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
