### ISSUE TITLE
you are use an old browser

### ISSUE THREAD

**Issue by Labirent** [Kyrodan/KeeAnywhere#273]
i can't add gdrive, box.com and dropbox account.

--------------- box.com says this: ---------------
_**This page cannot be displayed
• Make sure the web address https: //app.box.com is correct.
• Search the page using your search engine.
• Refresh the page after a few minutes.**_

--------------- gdrive's error message: ---------------
_**Your session could not be signed
This browser or app may not be secure.
Try using a different browser. If you are already using a supported browser, you can refresh the page you were on and try to log in again.**_

When adding an account, wouldn't it be better if we give this confirmation on the page in the tab to be opened in the browser installed on the computer instead of getting confirmation from the add-on window in the application?

these are screenshots:
![a](https://user-images.githubusercontent.com/47904773/114270731-b0bbfc80-9a16-11eb-85e3-b72008ea1f78.png)
![b](https://user-images.githubusercontent.com/47904773/114270737-b74a7400-9a16-11eb-9249-947752137679.png)
![c](https://user-images.githubusercontent.com/47904773/114270745-bd405500-9a16-11eb-865a-0d5955406f6a.png)

**Comment by Kyrodan** [comment]
See #252

ん ***@***.***> schrieb am Sa., 10. Apr. 2021, 14:59:

**Comment by Labirent** [comment]
thanks for quick answer.

btw I hope you don't get corona. take care. we need you :)
