### ISSUE TITLE
Dropbox - Token expires every day

### ISSUE THREAD

**Issue by BesT1CooKie1** [Kyrodan/KeeAnywhere#276]
Hello there,
at first thanks for the very useful app. I am frequently using it.
I noticed that the token for the dropbox option is expiring after every day. I searched a bit in the internet
and found out that the token usually does not expire by its own.

I am also using OneDrive and there it does not expire by its own, so I think this isn't meant to happen.

EDIT:
Maybe some context.
![grafik](https://user-images.githubusercontent.com/23483768/117538111-e4ce1180-b004-11eb-9b52-5315b590bf66.png)

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
Please try this release and reopen if this still appears.
