### ISSUE TITLE
Can't Authorize KeyAnywhere for Google Drive

### ISSUE THREAD

**Issue by dushkin** [Kyrodan/KeeAnywhere#277]
Hello,

I know this issue has been raised several months ago, but I could not find the solution there.

I get the infamous "This browser or app may not be secure" error message.
I use KeyPass 2.47 and KeyAnywhere 1.6.0.0.
Chrome version: 90.

Another point to note: I am working on a company managed laptop. Does that matters?

Please advise.

Thanks!

**Comment by BesT1CooKie1** [comment]
You describe a similar problem like in #268 . 
The author @Kyrodan was refering to the unreleased beta. 
You can find it here: #252 As I remember it, they also explain why this error occurs. It had nothing in particular to do with the security of the app itself, but with google not supporting third party browers anymore.

To fix your bug the beta should help. About the security matters: It would help if somebody else clarify or verify it.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
