### ISSUE TITLE
dropbox auth is impossible

### ISSUE THREAD

**Issue by sergentum** [Kyrodan/KeeAnywhere#278]
I'm trying to add dropbox, but inner browser is deprecated. Is there any way to switch it to something else? I have chrome installed, but inner page is opened by IE I suppose
![2021-05-17 15_27_23-Issues · Kyrodan_KeeAnywhere · GitHub - Vivaldi](https://user-images.githubusercontent.com/4054762/118488536-7edc3b00-b724-11eb-96dd-7be27e60ca9e.png)

**Comment by PBahner** [comment]
I'm having the same issue.

**Comment by PBahner** [comment]
try this: https://github.com/Kyrodan/KeeAnywhere/issues/241#issuecomment-775249257
- for me dropbox and google drive didn't worked with this.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.

**Comment by p29444** [comment]
Unfortunately, I'm using v2.0.3 and Dropbox sync is not working until now...
