### ISSUE TITLE
OneDrive cannot be accessed anymore

### ISSUE THREAD

**Issue by Angel0fDarkness** [Kyrodan/KeeAnywhere#281]
I have updated to v2.0 today and afterwards was unable to connect to OneDrive again.
It opens the authentication website, asks for permissions and correctly shows the success page at the end "Received verification code. You may now close this window."
But in KeePass, an error window pops up:
![KeeAnywhere_Onedrive_error](https://user-images.githubusercontent.com/439031/118803884-36e42200-b8a4-11eb-94b6-af3fbb885752.png)
If the blackened IDs are important, I could share them in private.

Best Regards,
Tobias

**Comment by Kyrodan** [comment]
I cannot find an issue with that. Is it maybe a temporary thing?
Can you delete your OneDrive Account and recreate it?
Do you use a proxy?

**Comment by Angel0fDarkness** [comment]
I have tried with "Check" first, but afterwards completely deleted and reset the account.
Currently I am working behind a VPN but without proxy, could try it without VPN in the evening..

Thanks :)

**Comment by flotux2** [comment]
I'm getting the same error message when trying to re-authenticate after upgrading to the new version 2.0.0.

I also removed my OneDrive account from KeeAnywhere and re-added it. But I still get the same error message. :-(

**Comment by Kyrodan** [comment]
This is weired. Yesterday I checked everything and everything was fine :-/

**Comment by StevenTN615** [comment]
I just updated the plugin to 2.0.0 and also received the same error. Tried your 2.0.1 plugin and it connected.

**Comment by Snoobz** [comment]
Hello, the new version 2.0.1 is not working for me! After I login into my OneDrive account, it redirects my Mozilla browser to this URL : http://127.0.0.1:49215/

Which is obviously not right. Any help please? I had to revert back to 1.6.0

Thanks.

**Comment by flotux2** [comment]
With version 2.0.1 re-authentication of OneDrive failed. After removing and adding the OneDrive account access now works again!

![grafik](https://user-images.githubusercontent.com/23209679/118854828-68c1ac80-b8d5-11eb-92bd-f7a00dde9b94.png)

I could use my Google Drive account directly without the need to re-authenticate.
I could use my Dropbox account after re-authentication. I didn't need to remove and re-add it!

**Comment by daecarne** [comment]
Hi! same here. I was get the same error when I updated to 2.0.0 version. I just updated to 2.0.1 version and it's fine now. Anyway, I needed to remove my onedrive account before and re-added after.

**Comment by Snoobz** [comment]
Well, this is weird but I solved my problem...
I reinstalled the 2.0.1 version, removed my OneDrive account, re-added it after the loggin process my browser still got redirected to this weird URL : http://127.0.0.1:49215/

Then going back to KeePass I clicked on the "Check" button and it said "Connection succeeded".

I don't know if you can "solve" this weird redirection after the loggin process (I don't know why it looks like I'm the only one facing this issue) but anyway it works now.

Thanks for the quick update.

**Comment by Angel0fDarkness** [comment]
@Kyrodan 
I have just tested the same on my other PC, similar problem appeared with 2.0.0.
With 2.0.1 it was fixed and I could re-connect to OneDrive.

However, on this PC I am seeing a error when the page is loaded after OneDrive authentication (still in the browser) where I would expect to see the success message "Received verification code. You may now close this window.".

@Snoobz 
I think this redirect is perfectly fine and the way this authentication works.

**Comment by lsaudon** [comment]
2.0.1 fix for me.

**Comment by Uwe11** [comment]
same here. No connection with 2.0.0, but works again with 2.0.1
Thnaks for quick reaction!

**Comment by SoerenEilenberger** [comment]
Hi, I just came here after I had the same problem and then tried 2.0.1. Unfortunately, it claims it's a different account now instead of the "code line error message". I am sure I am using the right account. I am using a second factor with MSAuth-App on my OneDrive, maybe this leads to it?

**Comment by SoerenEilenberger** [comment]
It does work to create the account from scratch again.

**Comment by Kyrodan** [comment]
>... it redirects my Mozilla browser to this URL : http://127.0.0.1:49215/
> Which is obviously not right. Any help please? 

This is correct. I should add a migration guide for Version 2.x to documentation to clarify this.

**Comment by Kyrodan** [comment]
@Angel0fDarkness  
> However, on this PC I am seeing a error when the page is loaded after OneDrive authentication (still in the browser) where I would expect to see the success message "Received verification code. You may now close this window.".

Why is the exact message? Or do you have a screenshot of that?

**Comment by Angel0fDarkness** [comment]
I cannot reproduce it on my laptop, it is working fine here.
Yesterday, it was showing the "Page could not be loaded" general error in Firefox as if the page wouldn't exist.
But authentication of the OneDrive account worked in both cases.

**Comment by gbaroni-csw** [comment]
For me, with OneDrive, version 2.0.1 worked by deleting the account and recreating it from scratch.

**Comment by Kyrodan** [comment]
I released v2.0.2 a few minutes ago, that should fix this issue.
Please read "notworthy" in changelog.
So this can be closed now?

If problems are still present in v2.0.2 then please open a *new* issue, this is a liitle bit confusing now (due to the many comments)
