### ISSUE TITLE
Port range for redirect URI calculated wrong

### ISSUE THREAD

**Issue by Elaborendum** [Kyrodan/KeeAnywhere#283]
Every since the last update, this dialog appears everytime I try to open the remote database from my DropBox account:
![image](https://user-images.githubusercontent.com/71190696/118896425-d7027100-b8cd-11eb-9250-b7e32f99dad9.png)

I can still access my account normally, so It's not blocked or anything.

**Comment by Kyrodan** [comment]
Have you already tried to re-authenticate?

**Comment by Wishmaster172** [comment]
I have the same problem here.

I tried to delete my Dropbox Account from the list to re-authenticate, but I got another error. :(
![screely-1621495428718](https://user-images.githubusercontent.com/17496386/118936900-423f5800-b94d-11eb-8b81-dcc98c09b1c5.png)

**Comment by erdmenchen** [comment]
I can confirm, I have the same issue since updating to v2.0

**Comment by yetanotherjr** [comment]
I had the same issue ; solved it with a "Check" of the account.
(I did clean the local cache first, don't know if it helped or not)

Go to Tools > KeeAnywhere Settings
![image](https://user-images.githubusercontent.com/31735062/118943835-4e7ae380-b954-11eb-8c21-671bf666f2b2.png)

Select your Dropbox account then "Check"
![image](https://user-images.githubusercontent.com/31735062/118944038-7cf8be80-b954-11eb-9dcd-3d81b4ae7ba4.png)

You'll be redirected to the Dropbox page to authorize the application again.

Afterwards, check should be OK again : 
![image](https://user-images.githubusercontent.com/31735062/118944182-9dc11400-b954-11eb-92d4-7aac93c12f82.png)

**Comment by xwitty** [comment]
in case yetanotherjr's hint is not working:
are you using a http/https-proxy? - maybe links back to [Issue #280](https://github.com/Kyrodan/KeeAnywhere/issues/280)

**Comment by Wishmaster172** [comment]
There is nothing for my to "Check", because I deletet my account to reconnect it. :(
No, I don't use any Proxy, I'm just directly connected to the Internet.

**Comment by mikesuderman** [comment]
I had the same problem, was able to reconnect after:
- deleting folder "KeeAnywhereOfflineCache", 
- Removing Dropbox link
- Signing into Dropbox in my browser
- Adding new "Keepass Anywhere" connection to Dropbox - Restricted.

**Comment by Wishmaster172** [comment]
I followed the same steps, but I'm still facing the same problem. :(

The folder is located here: C:\Users\%USERNAME%\AppData\Roaming\KeePass\KeeAnywhereOfflineCache
And the Cache can be cleared also via Plugin Settings:
![2021-05-20 17_38_06-KeeAnywhere Settings](https://user-images.githubusercontent.com/17496386/119008399-6bcea280-b992-11eb-8df7-93d9e07a2fea.png)

But this didn't work for me. :(

**Comment by Elaborendum** [comment]
yetanotherjr's fix worked for me, reauthorized it and everything's working now. In my case, I didn't clear the cache.

**Comment by Kyrodan** [comment]
So this can be closed? 
If problems still appear:
I released v2.0.2 a few minutes ago, that should fix this issue.
Please give it a try and reopen this issue, if your problem is still present.
Please read "notworthy" in changelog.

**Comment by Wishmaster172** [comment]
Sorry, I'm still facing the same issue.

- I updated to 2.02.
- I deleted Plugin Cache and restarted KeePass
- I tried to add a new account (because I deleted the old one before)

And I still receive 
`Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).`

**Comment by Kyrodan** [comment]
Can you post the redirect uri here? It's part of the Browser URL.

**Comment by Wishmaster172** [comment]
Sure. This is the whole URL:

`https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=320uxzdt4zl484z&redirect_uri=http://127.0.0.1:49588/&state=664b1bdb9fae46d891e1f36c6088c68d&token_access_type=offline&scope=account_info.read%20files.metadata.write%20files.metadata.read%20files.content.write%20files.content.read&code_challenge_method=S256&code_challenge=<xyz>`

**Comment by Kyrodan** [comment]
Okay, I found the problem, I'm so stupid *ggg*
I will release 2.0.3 later this day which hopefully fixes this problem.

**Comment by Kyrodan** [comment]
Fixed an released:
https://github.com/Kyrodan/KeeAnywhere/releases/tag/v2.0.3
