### ISSUE TITLE
OneDrive fail on 2.0

### ISSUE THREAD

**Issue by gbaroni-csw** [Kyrodan/KeeAnywhere#284]
II have installed version 2.0, but when I try to do a connection check, to update the login data, the Microsoft identification page opens correctly, I authenticate correctly, but when I go back to KeePass an error is generated and does not validate the connection to OneDrive.

**Comment by Skinn0r** [comment]
I have the same problem one one of my notebooks.

**Comment by vadimmitin** [comment]
the same issue

**Comment by Franck92500** [comment]
I have the same issue.
![Bug_KeyAnywhere](https://user-images.githubusercontent.com/80588317/119081053-812be700-b9fb-11eb-8797-5e5641a06ca2.PNG)

**Comment by ArwynFr** [comment]
**Downgrading to v1.6 works, so I suppose I'll stick with that version as a workaround.**

At first I thought this was caused but using MSEdge + Windows Hello authentication which might use a newer version of OAuth2 protocol. The problem still occurs using Firefox + Authenticator though, so it's probably the plugin's protocol which is outdated and needs upgrading.

**Comment by Kyrodan** [comment]
Hi, this is a knowed bug in v2.0.0 and I released v2.0.2 a few minutes ago, that should fix this issue.
Please give it a try and reopen this issue, if your problem is still present.
Please read "notworthy" in changelog.

**Comment by ArwynFr** [comment]
Tested with v2.0.3.
I needed to delete and re-add the account but it works, thanks !
