### ISSUE TITLE
OneDrive Authorization failed in Version 2.0

### ISSUE THREAD

**Issue by leachimus** [Kyrodan/KeeAnywhere#285]
First of all, thanks for the update, but in this version I can no longer authorize my OneDrive. Attached is the error message I get. I'm back to version 1.6 for now. With this it works without problems.

```
Authorization failed:

Error contacting userinfo endpoint: {

  "code": "BadRequest",

  "message": "{\r\n  \"error\":{\r\n    \"code\":\"UndefinedScope\",\"message\":\"Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileBadRequestException' was thrown.\"\r\n  }\r\n}",

  "innerError": {

    "date": "2021-05-21T07:26:05",

    "request-id": "1e096aba-05fb-4cb7-a0fc-2f50474087dc",

    "client-request-id": "1e096aba-05fb-4cb7-a0fc-2f50474087dc"

  }

}

```

**Comment by Kyrodan** [comment]
@leachimus are you using v2.0.*2*?
I fixed this in that version. I cannot reproduce it with 2.0.2, but with 2.0.0.

**Comment by leachimus** [comment]
Ohh, I'm really sorry. That one had already opened a issue, I have overlooked. I should have looked in the closed cases before. 🙈 Works now, thanks!
