### ISSUE TITLE
2.0.2 Dropbox still opens in some inline browser window

### ISSUE THREAD

**Issue by antgustech** [Kyrodan/KeeAnywhere#286]
When I try to add my Dropbox account I still get a Window saying I need to "Upgrade your browser to use Dropbox". I got the impression that it should now just your default browser but it doesn't look like that is working.

**Comment by Kyrodan** [comment]
> I got the impression that it should now just your default browser but it doesn't look like that is working.
Then you are **not** using the v2.0.2. Please check, that you are not accidently using an old version in parallel. You can check this e.g. by opening the Update Checker.

**Comment by antgustech** [comment]
Sorry, my bad, I accidently still had the old version installed. Now it works.
