### ISSUE TITLE
2.0.2 Fails OneDrive Authentication with System Exception

### ISSUE THREAD

**Issue by JNavas2** [Kyrodan/KeeAnywhere#288]
After upgrading from 1.6.0 to 2.0.2, I Removed my OneDrive account, and then attempted to Add it, but KeeAnywhere failed with a System Exception (attached). I have reverted to 1.6.0 (which Added my OneDrive account successfully again).

OS Name	Microsoft Windows 8.1 Pro
Version	6.3.9600 Build 9600
.NET 4.8.03761
KeePass 2.48.1

[KeeAnywhere-202-Exception.txt](https://github.com/Kyrodan/KeeAnywhere/files/6526521/KeeAnywhere-202-Exception.txt)

**Comment by Kyrodan** [comment]
Do you have any restrictions for opening a local port?
We had these kind f problems during the beta-phase of 2.0 but could not find a root cause. Maybe you are using a very restrictive firewall or something like this. Maybe it asks you for permission?

You could also try version 2.0.**3** (which fixes another port range bug especially for Dropbox).

**Comment by JNavas2** [comment]
>Do you have any restrictions for opening a local port?
>Maybe you are using a very restrictive firewall or something like this.

Standard Windows Firewall, but I'm usually on a _Public_ (rather than a Private) network, which causes Windows to lock down. See attached screenshot.

>Maybe it asks you for permission?

It does not ask for permission.

>You could also try version 2.0.3 (which fixes another port range bug especially for Dropbox).

2.0.3 also fails the same way.

Anything else I can try or do to help?

<img width="400" alt="explorer_20210523-064600 060" src="https://user-images.githubusercontent.com/14850792/119263194-e8c86a80-bb92-11eb-8c02-57eba689cda9.png">

**Comment by pozom** [comment]
In 2.0.3 you can try to remove the OneDrive account created with a previous version and create it again.

Thank you.

**Comment by JNavas2** [comment]
> In 2.0.3 you can try to remove the OneDrive account created with a previous version and create it again.

Been there, done that. Also in 2.0.2. In both versions, I Removed my OneDrive account, and then attempted to Add it, but KeeAnywhere failed with the same System Exception.

**Comment by TuggyNE** [comment]
I had the same problem, but was able to get it to work by running KeePass elevated.
