### ISSUE TITLE
Update latest version on website to 2.0.3

### ISSUE THREAD

**Issue by jlowag** [Kyrodan/KeeAnywhere#289]
Keepass prompts to update KeeAnywhere to version 2.0.3 but the latest version linked on https://keeanywhere.de is 2.0.2.

I did eventually find the download by changing the version numbers in the download link, but it should be updated on the website.

Thanks in advance.

**Comment by Kyrodan** [comment]
Thanks for pointing to this, I forgot to update the Homepage-Link.
It should now be correctly.
