### ISSUE TITLE
KeyPass Tray Commands Grayed Out

### ISSUE THREAD

**Issue by LeeThompson** [Kyrodan/KeeAnywhere#29]
KeePass 2.32
Windows 7 x64 (Sp1)
KeeAnywhere 1.0.0.0

I set up KeeAnywhere with Dropbox and it works but the second I minimize KeePass to tray, it's unusable because the right click menu on the tray icon is completely grayed out.   Double clicking on the tray icon does not restore it either.    I have to kill it with task manager.

**Comment by LeeThompson** [comment]
UPDATE: I think it's because I set up KeeAnywhere and didn't exit KeePass before starting to use the plugin.    It's working ok now.

**Comment by Kyrodan** [comment]
Great, if it is working now.

**Comment by LeeThompson** [comment]
Should probably add something in the readme that the user should re-start KeePass once you've set up KeeAnywhere.

**Comment by Kyrodan** [comment]
I can't reproduce this behavior. Can you? If yes, could you please write the steps for reproduction?

**Comment by LeeThompson** [comment]
I'll work on trying to reproduce this on demand for you.
