### ISSUE TITLE
ieframe.dll error when cancelling Box.com authorization

### ISSUE THREAD

**Issue by leftdisconnected** [Kyrodan/KeeAnywhere#291]
# Issue
Ieframe error when cancelling Box.com authorization.  Errors are expected when cancelling or failing the authorization process, but this one seems unexpected.  Apologies if otherwise.

May be separate issue, but  **Authorize to Box** window can be left open indefinitely after these authentication errors.

# Environment
Windows 7-64
.Net 4.8.03761
KeePass 2.48.1
KeeAnywhere 2.0.3

# Steps
1.  Open KeeAnywhere Settings,
2. Click **Add...**,
3. Choose **Box**,
4. Log in using resulting web frame,
5. When asked for authorization, click **Deny access to Box**,
6. *Expected* **KeePass - Fatal Error**:  `Authentication failed`,
7. *Unexpected* **Ieframe error**, as below.
8. **Authorize to Box** window may be left open indefinitely unless user presses **Cancel**.

## Ieframe Error Window Title
`res://ieframe.dll/dnserrordiagoff.htm - #https://localhost/oauth?error=access_denied&error_description=The+user+denied+access+to+your+application`

## Ieframe Error Window Message
`There is no program associated to perform the requested action. Please install a program or, if one is already installed, create an association in the Default Programs control panel.`

# Important Note
Iexplore.exe permissions are set to Full Deny "Everyone" on this machine, but the KeeAnywhere frame to login and authorize to Box.com *does* work.

**Comment by Kyrodan** [comment]
will be fixed with #409
