### ISSUE TITLE
Unable to login to OneDrive due to different accounts

### ISSUE THREAD

**Issue by xanderhurley** [Kyrodan/KeeAnywhere#292]
When logging into my work pc using my work account for example xyz@work.com and trying to use key anywhere with my personal home account of abc@home.com I get this error as shown in the screenshot submitted.

![image](https://user-images.githubusercontent.com/13451572/119318028-b9882b00-bc70-11eb-9b71-d5c98fe41195.png)

Any help on this will be greatly appreciated I only use Keepass with one account and access it from everywhere

**Comment by Kyrodan** [comment]
Please Demeter your existing Account a recreate one.

Xander ***@***.***> schrieb am Mo., 24. Mai 2021, 10:18:

**Comment by xanderhurley** [comment]
Ah that did the trick, thanks
