### ISSUE TITLE
Error loading file

### ISSUE THREAD

**Issue by namol8848** [Kyrodan/KeeAnywhere#293]
After updateting to 2.0.3 version of KeeAnywhere I cannot save anything to Dropbox. I receive "Error loading file list" every time. With 1.6.0 this problem does not exist.

**Comment by Kyrodan** [comment]
please re-authenticate your Account.

namol8848 ***@***.***> schrieb am Fr., 28. Mai 2021, 11:50:

**Comment by namol8848** [comment]
Hi,
Thank You for quick response. That helped. Don't know why I didn't thought of that myself. Sorry for bothering You and, once again - Thank You!
