### ISSUE TITLE
Migrating OneDrive 1->2  

### ISSUE THREAD

**Issue by oleg-shilo** [Kyrodan/KeeAnywhere#299]
Ihave difficulties of migrating v1.6->2.* for One Drive account. This I found this:
![image](https://user-images.githubusercontent.com/16729806/121353148-e165d700-c970-11eb-85ed-ff70f1b0f472.png)

What exactly does it mean "OneDrive-account"? 
Is it a configuration for OneDrive channel or the actual OneDrive account with a MS?  

Asking this because I have removed the configuration for OneDrive channel and the problem did not go away:
![image](https://user-images.githubusercontent.com/16729806/121353696-7bc61a80-c971-11eb-89a3-ff7ee5320b1e.png)

**Comment by Sir-Launcelot** [comment]
I am not sure what error message you are getting, but I am having issues as well, and don't know if they match yours.

![image](https://user-images.githubusercontent.com/6750561/121538807-1276f380-c9d3-11eb-8f90-c62c2fae3423.png)

**Comment by Kyrodan** [comment]
Very old issue, maybe already fixed. => closed.
