### ISSUE TITLE
When the time is not right you cant add google account to keeanywhere

### ISSUE THREAD

**Issue by OMGitsGroot** [Kyrodan/KeeAnywhere#300]
Operating System: Windows 10 20h2
Plugin Version: 2.0.3

Hello, let me start off by thanking you to create this beautiful  plugin for keepass.
I was trying to add a google account to the plugin but i couldnt because the time was synced.

i got this error:
![firefox_MORfRE903a](https://user-images.githubusercontent.com/61696358/123027400-109f2e00-d3de-11eb-80af-bd8727cf4ee9.png)
i fixed it by syncing the time.

**Comment by Kyrodan** [comment]
Thanks for sharing this.
This is not an issue I can fix, it works as designed.
