### ISSUE TITLE
Changelog opening on every startup

### ISSUE THREAD

**Issue by F-Lambda** [Kyrodan/KeeAnywhere#305]
Ever since updating to v2.0.3, the changelog is appearing at every startup instead of only on first run.

### OS:
64-bit
![uV3drwO 1](https://user-images.githubusercontent.com/21232805/125877546-4eb8dc83-fdef-4a36-99bb-81c1c917abfd.png)

### Version:
![L4Z4Dke 1](https://user-images.githubusercontent.com/21232805/125877413-9adef2f9-23c9-4e42-8f87-f6000e24bf26.png)

**Comment by Kyrodan** [comment]
Very old issue, maybe already fixed. => closed.
