### ISSUE TITLE
Win 7 / dropbox issue

### ISSUE THREAD

**Issue by rvansche** [Kyrodan/KeeAnywhere#307]
I tried to hook up to dropbox, but I get an unhandled exception error. Is there  a workaround. Running this on Win7 by the way.

![image](https://user-images.githubusercontent.com/4194315/129084738-6905c54e-7ac4-48ab-ac63-7442ac3379cf.png)

**Comment by ColtWMorris** [comment]
Have a look at issue #301. This looks like it could be another instance of the same thing.

**Comment by Kyrodan** [comment]
Closing this duplicate.
