### ISSUE TITLE
Windows 10 / Dropbox: webclient error

### ISSUE THREAD

**Issue by sychron** [Kyrodan/KeeAnywhere#308]
Trying to open my database from its standard dropbox location shows an error message:

"Faile to load the specific file! Ausnahmefehler während einer WebClient-Anforderung."
(Faild to load the specific file! Exception during a WebClient request.)

I used keeanywhere 1.6 before, so I thought this might be the source of that error.
I upgraded to version 2.0.3.0, but the error persists.

**Comment by AmahaShadow** [comment]
Same issue, worked until this morning, now fails to connect to Dropbox![IMG_20210830_085504.jpg](https://user-images.githubusercontent.com/66038459/131298170-318e6849-1d26-4144-b2bf-0a66e8431470.jpg)

**Comment by AmahaShadow** [comment]
Okay, so, I noticed KP had a new version available (2.49), so I decided to update it, remove keeAnywhere (+ clear cache + removed KeeAnywhere.Accounts.json), reinstalled the plugin, Recreated the dropbox connection, and it now works fine again.
