### ISSUE TITLE
Onedrive account connection impossible

### ISSUE THREAD

**Issue by priant45** [Kyrodan/KeeAnywhere#309]
At keepass launch, I have this error message:
![image](https://user-images.githubusercontent.com/12081340/131828215-b3043205-71ca-4fcf-9922-925835c65ca2.png)
or when I resynchronise the database : 
![image](https://user-images.githubusercontent.com/12081340/131829736-3cb9011b-31bc-40c1-807e-144ac03f70ae.png)
When I log me in on the Microsoft login page, I am redirected to this page and the connection is refused.
![image](https://user-images.githubusercontent.com/12081340/131828358-b53869ac-e418-4f33-ab02-9d0b8b64f57c.png)
Here is the configuration :
![image](https://user-images.githubusercontent.com/12081340/131829265-43b947ac-b959-4516-8a86-dfd9ddbb5684.png)
![image](https://user-images.githubusercontent.com/12081340/131829874-92130267-7997-4f05-8d7b-a82a764446f7.png)

**Comment by Kyrodan** [comment]
Duplicate to #282 => closed
