### ISSUE TITLE
OneDrive problem when uploading bigger Databases ( >10 MB)

### ISSUE THREAD

**Issue by criker1** [Kyrodan/KeeAnywhere#312]
When I try to save my database, which includes some pictures, i get error messages that the database couldn't be uploaded.
![Error_1](https://user-images.githubusercontent.com/55559981/133159827-796211fa-40f3-45a7-8ff5-1df29950e0a3.jpg)
![Error_2](https://user-images.githubusercontent.com/55559981/133159830-720cffd2-b7e6-45f3-b1f2-7daaa27b6e7a.jpg)

If you need a translation for the error messages, please let me know.

**Comment by Kyrodan** [comment]
Duplicate to #282 => closed
