### ISSUE TITLE
What version of Keepass is required?

### ISSUE THREAD

**Issue by alabamatoy** [Kyrodan/KeeAnywhere#314]
See: [https://sourceforge.net/p/keepass/discussion/329220/thread/17d1bd26/?page=5&limit=25#f7ab](https://sourceforge.net/p/keepass/discussion/329220/thread/17d1bd26/?page=5&limit=25#f7ab)

**Comment by Kyrodan** [comment]
Requirements are noted down in https://keeanywhere.de/use/installation
Additionally any change of prerequisites are noted down in change log.

Sidenote:
Currently KeeAnywhere does not work for Mono/Linux out of the box.

Am So., 3. Okt. 2021 um 16:08 Uhr schrieb alabamatoy <
***@***.***>:
