### ISSUE TITLE
Azure blob is not working

### ISSUE THREAD

**Issue by tolew1** [Kyrodan/KeeAnywhere#315]
How do you use the Azureblob storage? I have tried so many ways. I'm sorry to complain but the documentation is not thorough and even though the author said it's less technical than KeeCloud. I find KeeCloud easier and more simple to use. 

I'm using my Azure account name, Azure Access key and the URL as stated in the Docs.

![image](https://user-images.githubusercontent.com/3882817/136141355-7dc02e6b-ce2d-48a7-b447-489739544157.png)

Whenever I try this in the screen shot, it always says connection failed for the test.  Also don't understand this sentence from the docs.

> The {accountname} is the name of the account you can see in KeeAnywhere Settings` account list.

How can there be a list in settings if you haven't added an account yet because it won't accept it?

I'm at a loss on how to make this work.

**Comment by bihe** [comment]
@tolew1 -  It works this way:

**Account-Name**: The Storage account name, not the full URL; just the "host-part" of the storage account
**Access-Token**: The shared key (Key 1 or Key 2) - unfortunately no SAS token possible right now
**Blob-Path**: The container name - is like a directory, NOT the filename

![image](https://user-images.githubusercontent.com/635852/141750535-be19b89b-4ec6-425d-be5a-918827b85c86.png)

**Comment by pattisanta** [comment]
Hi I have the same issue. I have entered in all the information and getting failed when I hit test.  did anyone figure a solutions to this problem?

Regards,
Patti

**Comment by Kyrodan** [comment]
Very old issue, maybe already fixed. => closed.
