### ISSUE TITLE
Feature Request: Plans to add other services like Proton Drive?

### ISSUE THREAD

**Issue by RashiqAzhan** [Kyrodan/KeeAnywhere#317]
Are there plans to add more secure drive options like Proton Drive? Google, Microsoft, Amazon, like services, gives me the heebie-jeebies.

**Comment by Kyrodan** [comment]
Currently there are no plans to support ProtonDrive.

Reasons:
* still in Beta
* Poor development effort - as far as I can see
* But most-important: No API available, nor S3-Compatible: https://protonmail.uservoice.com/forums/932839-proton-drive/suggestions/43582125-protondrive-api

But the question regarding "more secure": You are uploading a password file to a cloud system, so you should treat the storage itself as public. The KeePass database itself has strong encryption (use a second factor!). So whether you store it on a secure or unsecure platform: it's in the internet!
