### ISSUE TITLE
KeeAnywhere on macOS

### ISSUE THREAD

**Issue by gobenoit06** [Kyrodan/KeeAnywhere#318]
Hello, I am going to migrate to macOS from Windows, is KeeAnywehre plugin working in the same way under macOS as on Windows? Especially regarding access to Googe Drive or OneDrive? No special permisisons preventing Cloud access on these platforms? Thanks for your feeback.

**Comment by Kyrodan** [comment]
No, currently it's not supported on MacOS and I don't plan to support it - see Question #18
