### ISSUE TITLE
Connection to Onedrive failed

### ISSUE THREAD

**Issue by raret** [Kyrodan/KeeAnywhere#319]
Since two days every 30 min i got the massage from KeePass that the Connection to Onedrive is lost:

"Connection to this account failed
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt
Try to re-authorize in next step"

After clicking ok, the brower opens and i have to sing in to my MS Account.
After that that massage appear: "Received verification code. You may now close this window. "

After pressing the check button again the start Massage appear again. 

I use 2.0.3 and the Newest KeePass version

**Comment by mikeych76** [comment]
I have the same issue. Maybe related to recent MS updates? I deleted onedrive credentials from keeanywhere and created new ones but that did not help...

**Comment by lsaudon** [comment]
Keepass 2.50
KeeAnywhere 2.0.3

**Comment by Pebberman** [comment]
Hello, 

cannot open my database on Onedrive. Same error as above. 
KeePass 2.5.7 64-bit Win10
KeeAnywhre 2.1.0

The problem still exists, only on Windows 10 or 11. The database can still be opened and edited on iOS and Android without errors.

Login renewed, everything ok, but that again “the object reference was not set to an object instance.”
