### ISSUE TITLE
Remote backup doesn't work on google drive in the root path

### ISSUE THREAD

**Issue by MauroG86** [Kyrodan/KeeAnywhere#327]
Hi,
I discovered the following issue. When I save the database in the root path of my google drive then backup files won't be created when I git the save button. But when I save the database in a subfolder it works correctly (as I set it up), for example in /keystore/database.kdbx.
Sounds like a bug or is it a feature?

Best regards,

Mauro

**Comment by amid0** [comment]
Hi @MauroG86 
Question.
Where are you changing this path, where to store backups on google drive?
I can't see such option. And backups doesn't work for me.
![image](https://user-images.githubusercontent.com/6542910/182850767-d5f8d768-18c4-4312-8018-a044d7519e86.png)

**Comment by MauroG86** [comment]
Hi @amid0,

when you save your database on the cloud you can choose the path.
File -> Save As -> Save to Cloud Drive...
Then a dialog pops up and you can choose where you want to save your database.
If you now choose the root path, then the backups won't be created when you save a change.

Best regards,

Mauro
