### ISSUE TITLE
automatic backup doesn't work

### ISSUE THREAD

**Issue by paymanz** [Kyrodan/KeeAnywhere#331]
i have checked the autonomic backup to remote and also to local but it doesn't seem to work, what is the frequency for it to happen?!

**Comment by MauroG86** [comment]
Hi @paymanz,

for me it works. When you hit the save button, a backup is created. It works locally and remotely.
I use gdrive as remote storage.

Best regards,

MauroG86

**Comment by Kyrodan** [comment]
Very old issue, maybe already fixed. => closed.
