### ISSUE TITLE
Feature Request: support Nutstore for Chinese Users

### ISSUE THREAD

**Issue by zhang-stephen** [Kyrodan/KeeAnywhere#334]
as title said, support Nutstore or allow users add cloud which supports webDAV protocol. As a Chinese user, Nutstore is the most available cloud service.

see [Nutstore](https://www.jianguoyun.com/).

**Comment by stark-zhang** [comment]
emmm...keepass2 support webDAV now, but I hope you could provide a more friendly interface of it.

**Comment by Kyrodan** [comment]
As all documention seems to be in chinese I cannot find any developer API or comaptibility information I am able to read :-/.
Maybe this provider is S3-Compatible, then you already can use this with KeeAnywhere.

**Comment by stark-zhang** [comment]
emmm... I don't think it's S3-Compatible, and I have not found any open APIs. I can mail to them to seek help. But I think it's hard to support Nutstore if I cannot get anything from developers of it.

wait for their reply. -_-||

**Comment by Kyrodan** [comment]
Closed due inactivity.
