### ISSUE TITLE
Feature Request: decentralized Clouds

### ISSUE THREAD

**Issue by NoCoderbutLovePC** [Kyrodan/KeeAnywhere#335]
Hi
Thanks for your efforts and really love the idea. 
I wanted to request to add clouds like storj.io and peergos if that's possible.

**Comment by Kyrodan** [comment]
Hi @NoCoderbutLovePC,

I understand the concept of decentralized clouds but I can't see a "standard" to support several providers. They all have their own API and I am not willing to implement several niche-providers. KeeAnywhere was implemented with a simple user interafce in mind to support the "big consumer ones". So your request is out of my scope.
 
But the good news for you is that storj.io is maybe *already supported* by KeeAnywhere:
KeeAnywhere supports S3-Compatible Services, and storj.io has a compatible API: https://docs.storj.io/dcs/api-reference/s3-compatible-gateway/

For PeerGOS I understand, that it is a frontend/"directory" for Objects and the *storage* itself needs to be handled seperately - per IPFS and/or S3-Compatible Object Space. So I do not understand the use-case to support this service.

I hope this helps you.
Regards,
Daniel

**Comment by Kyrodan** [comment]
Btw.: Maybe https://filebase.com/ is a solution for you - also S3-Compatible but End-User-Friendly
