### ISSUE TITLE
Authorization Failed: Error Validating token reponse... Lifetime validation failed (Google Drive)

### ISSUE THREAD

**Issue by josfire18** [Kyrodan/KeeAnywhere#336]
I am not sure if this has already been addressed and I am just unable to find anything about it, however after fresh install of windows, I went to install the newest version of KeePass (2.50) and KeeAnywhere (2.0.3) where I am met with an Authorization Failed error when trying to link google account to KeeAnywhere.

I saw something about having to create new accounts from 1.0 to 2.0 so I made an entirely new Google Drive account, pulled a copy of my kdbx to it, and tried to link that account, only to be met with the same error. 

Any insight on what I am missing here?

![KeeAnywhere_AuthorizationFailed](https://user-images.githubusercontent.com/22581489/164944359-68f0c5f2-6b40-4829-ae96-71193a60568f.png)

**Comment by josfire18** [comment]
Well that sucks. Mine is set automatically… and it’s not off at all.

Thank you,

Joey Rockwood

On Jun 14, 2022, at 2:08 PM, zawupf ***@***.***> wrote:

﻿

Had the same issue today and finally found out that the system clock was out of sync. 😳

**Comment by Kyrodan** [comment]
Cannot reproduce => closed.
