### ISSUE TITLE
HiDrive Authorization not longer working

### ISSUE THREAD

**Issue by MarkusLoyen** [Kyrodan/KeeAnywhere#338]
I store my KeePass-File in my HiDrive. After the Update of KeePass to Version 2.51.1 KeeAnywhere takes indefinite time to authorize as an App with HiDrive.

![image](https://user-images.githubusercontent.com/58221933/167819316-22fcf645-cb0e-4076-9265-f48d2f8c132e.png)

Browser opens, I get access to my HiDrive but nothing else happens....

So I deleted also the App-Access in the HiDrive Settings online
![image](https://user-images.githubusercontent.com/58221933/167818108-24d7dda6-22f6-4063-b9d4-01da2148f38a.png)

but unfortunately I cannot get it back working.

I also removed the existing settings for HiDrive in the KeeAnywhere-Settings under Accounts

![image](https://user-images.githubusercontent.com/58221933/167818353-7ef0f367-6aa5-43af-800c-cf022438e254.png)

as the re-authorization made KeePass to stop working (no timeout in the latest version?).

Hope this is just an API problem or something that can be easily solved...

Other storage providers work:

![image](https://user-images.githubusercontent.com/58221933/167819907-d5c77b5d-a5a4-4c95-9ae9-80f475f5322a.png)

**Comment by Kyrodan** [comment]
Strato changed the authorization Endpoint and wasn't informed about it. I
will fix it shortly.

Am Mi., 11. Mai 2022 um 11:37 Uhr schrieb MarkusLoyen <
***@***.***>:

**Comment by MarkusLoyen** [comment]
what about fixing? ;-)
