### ISSUE TITLE
Failed to load specific file

### ISSUE THREAD

**Issue by dxa2k22** [Kyrodan/KeeAnywhere#339]
![Screenshot 2022-05-18 11 42 48 PM](https://user-images.githubusercontent.com/105805691/169085180-250bf98e-4d3e-40ef-b2cc-b13c12410981.png)

Not sure why there is an error accessing the file, see the screenshot for the error.

**Comment by Jackabomb** [comment]
1. Is the file really there?
2. If you go to Tools->KeeAnywhere Settings, does your account appear in the list? If so, what happens when you click the "Check" button on that account?
3. What OS are you using? What versions of KeePass and KeeAnywhere?

**Comment by dxa2k22** [comment]
> 1. Is the file really there?
> 2. If you go to Tools->KeeAnywhere Settings, does your account appear in the list? If so, what happens when you click the "Check" button on that account?
> 3. What OS are you using? What versions of KeePass and KeeAnywhere?

Thanks for the reply Jacakbomb here are my inputs

1. Is the file really there? [dxa2k22] The keeAnywahere plugin was installed
2. If you go to Tools->KeeAnywhere Settings, does your account appear in the list? If so, what happens when you click the "Check" button on that account? [dxa2k22] Yes,  on the google drive, only mydrive is visible  ; shared drive is not visible. | Check  button retuned a successful result :  
(see attached pic)

3. What OS are you using? What versions of KeePass and KeeAnywhere?  [dxa2k22] Operating System: Windows 10 Enterprise 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)  ; Keepass : 2.49 (64 bit)  ; KeeAywhere : 2.03
![ss](https://user-images.githubusercontent.com/105805691/172388451-5f139d49-3979-4f7a-b6c4-53c486a3438a.png)

**Comment by tvanderelsen** [comment]
[Google have started to "simplify" folder structures](https://support.google.com/drive/answer/10864219), meaning if you had a shared folder in My Drive, you may find that it has been replaced by a shortcut:

![image](https://user-images.githubusercontent.com/15731644/188427636-0a0e98e0-679b-433e-b233-c620ce9c48d0.png)

If you use Google Drive in a browser and see that shortcut icon when beforehand it was a regular folder, that might be what has happened.

I don't yet have a solution though - I don't think KeeAnywhere handles Google Drive Shared Folders but I could well be mistaken.
