### ISSUE TITLE
In which path does KeeAnywhere store its backups on Google Drive?

### ISSUE THREAD

**Issue by chris-kwng** [Kyrodan/KeeAnywhere#343]
Hi,

in which path does KeeAnywhere store its backups on Google Drive?

The reason for the request is that I would like to access the current database with the app "Keepass2Android". This way I would always have the current database available on my smartphone.

Thanks and best regards,
Chris

**Comment by Jackabomb** [comment]
For me it saves the backups right alongside the main database file. The backups have name like MainFile_Backup_2022-09-06-06-45-30.kdbx.

**Comment by Kyrodan** [comment]
See https://keeanywhere.de/use/advanced_topics under "Automatic Backup"

Am Di., 6. Sept. 2022 um 22:57 Uhr schrieb Jackabomb <
***@***.***>:
