### ISSUE TITLE
Any plans to support Synology Drive in these cloud offerings?

### ISSUE THREAD

**Issue by DAE51D** [Kyrodan/KeeAnywhere#344]
Synology has a new feature of their DSM 7.x called "Drive" (https://www.synology.com/en-us/dsm/feature/drive) and acts like any of these other cloud services. It would be awesome if your plugin supported this so that I could keep my .kbdx file on my own NAS and have my KeePass use it transparently (as I do with Google Drive currently via this plugin: https://sourceforge.net/projects/kp-googlesync/ )

**Comment by Kyrodan** [comment]
If you use a Synology - as I do - you can use several other mechanisms that are already supported by KeePass (e.g. FTP/SFTP).
I two-way-sync my database from my Synology to a public cloud account (e.g. OneDrive) und use it from there.

So I don't think I would support any "vendor-special" private cloud.
