### ISSUE TITLE
Error when loading hubic drive tree

### ISSUE THREAD

**Issue by alphamax** [Kyrodan/KeeAnywhere#35]
Hello,

![errhubic](https://cloud.githubusercontent.com/assets/10722632/15388771/d81bf4cc-1db3-11e6-8646-281988e5d212.png)

It seems my hubic box can't be loaded. Any idea ? Can i provide you some log files ?

Regards,

**Comment by Kyrodan** [comment]
Same as #34: Please attach your log files there.
