### ISSUE TITLE
The browser with instructions doesn't open if I click "add" and Google Drive

### ISSUE THREAD

**Issue by Blacky0shii** [Kyrodan/KeeAnywhere#350]

**Comment by RSG-42** [comment]
Having the same Issue today. 25.08.2022

**Comment by Jackabomb** [comment]
Can you provide some more information? Versions for Windows, Keepass, and KeeAnywhere? When the browser is supposed to open, what happens instead?

**Comment by Kyrodan** [comment]
closed due inactivity.
