### ISSUE TITLE
Error saving to DropBox restricted

### ISSUE THREAD

**Issue by vovodroid** [Kyrodan/KeeAnywhere#352]
Recently saving or fails either takes a lot of times. I recreated account in KeeAnywere settings, but it didn't help.

![image](https://user-images.githubusercontent.com/8691781/182589391-3109fe81-eb65-43f7-8ce2-24fd7b561f6c.png)

Dropbox itself is accessible via browser.

**Comment by Kyrodan** [comment]
cannot reproduce.
