### ISSUE TITLE
New Google drive update has broken KeeAnywhere

### ISSUE THREAD

**Issue by HaydnHaines** [Kyrodan/KeeAnywhere#356]
Hi,

Recently Google has been rolling out a  change to google drive which seems to impact KeeAnywhere, an example reference https://www.droidwin.com/google-drive-replaces-files-folders-with-shortcuts/

This seems to have changed existing folder structures from "G:\My Drive\My Folder" to "G:\.shortcut-targets-by-id\XXXXXXXXXXX-XXXXXXXXXXXXXXX\My Folder" and they appear as shortcuts, not folders. This has the impact that ".shortcut-targets-by-id" doesn't appear in the file picker, possibly due to it being a shortcut or a file (shortcut) without a kdbx extension?

Thanks.

**Comment by Jackabomb** [comment]
It's a little unclear from your post. Are you using the Google Drive desktop app and KeePass's File->Open->"Open File" dialog? Or are you using the File->Open->"Open from Cloud Drive" dialog?

**Comment by HaydnHaines** [comment]
We're using "open from cloud drive". In the popup that is shown, I select my account (as it's setup under tools -> KeeAnywhere settings). Any folders that I have created and files in the root directory show fine, however as the shared folder we use is now a shortcut (due to the Google change linked above) it doesn't show in the list.

**Comment by HaydnHaines** [comment]
I believe to replicate this you'll need 2 Google users:

  - UserA creates a folder X in google drive with a sub folder containing a KeePass database.
  - UserA shares X with UserB.
  - If UserB views folder X in the drive web interface they should see "Original Folder" on the right with "Shortcut info" below it.
  - If UserB views folder X's parent in windows explorer via the drive desktop app they should see it listed as a shortcut (not file or folder).
  - Folder X will not show in KeeAnywhere's open dialog window when viewing it's parent's file list.

**Comment by Jackabomb** [comment]
Ah. This is a duplicate (or maybe superset) of #223. Your post adds a little more technical info. I'll collect my thoughts from the available info over there.
