### ISSUE TITLE
KeeAnywhere not working with dropbox exception error IP 162.125.70.19:443.

### ISSUE THREAD

**Issue by f1h0** [Kyrodan/KeeAnywhere#367]
An unhandled exception in the application. When you click Continue, the application will ignore the error and try to continue. When you click the "Exit" button, the application will exit immediately.

An attempt to establish a connection was unsuccessful because the required response was not received from another computer within the required time, or an already established connection was terminated due to an incorrect response from an already connected computer 162.125.70.19:443.

although before everything worked as it should without errors, what's the matter?.png)

![image](https://user-images.githubusercontent.com/1436880/210200963-b5b4273a-1803-4af4-8a58-47bafbc451ee.png)
![image](https://user-images.githubusercontent.com/1436880/210200966-23e6104d-9306-4987-ac7f-54e31448075e.png)

**Comment by Kyrodan** [comment]
incomplete report, can't reproduce.
