### ISSUE TITLE
.net version requirement

### ISSUE THREAD

**Issue by go4tidal** [Kyrodan/KeeAnywhere#37]
Does anyone know the .net version requirement for this plugin ?

I would like to use it in Win XP.

thanks

**Comment by Kyrodan** [comment]
Only Windows 7 or newer is supported. This is due to the requirements of
dotNET 4.5 on which this plugin relies.

go4tidal <notifications@github.com> schrieb am Mo., 6. Juni 2016, 18:04:

**Comment by go4tidal** [comment]
Thanks for your fast and clear reply.

Guess I'll have to upgrade my OS

On 06/06/2016 17:17, Daniel Bölts wrote:
> Only Windows 7 or newer is supported. This is due to the requirements of
> dotNET 4.5 on which this plugin relies.
>
> go4tidal <notifications@github.com> schrieb am Mo., 6. Juni 2016, 18:04:
>
>> Does anyone know the .net version requirement for this plugin ?
>>
>> I would like to use it in Win XP.
>>
>> thanks
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Kyrodan/KeeAnywhere/issues/37>, or mute the thread
>>
> <https://github.com/notifications/unsubscribe/AAVratuaesLigk-nA8poFnQbxNO8VFW0ks5qJEUjgaJpZM4IvDe_>
>> .
>>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kyrodan/KeeAnywhere/issues/37#issuecomment-224008724>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AS3XSZRu8HkuuLaKqk9mGeOvyh5cvy4gks5qJEgUgaJpZM4IvDe_>.
>

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by go4tidal** [comment]
I understand the issue with older .net version use, but one further comment.
It would have been great if Windows XP was supported, because Dropbox are stopping support for XP within weeks.  This makes it very inconvenient to use DBox hosted KeePass now.

**Comment by Kyrodan** [comment]
I don't think this would ever happen: This plugin heavily relies on .Net 4.5 features.
