### ISSUE TITLE
New google password

### ISSUE THREAD

**Issue by Thomase004** [Kyrodan/KeeAnywhere#373]
Hi, I put my KeePass database to gdrive. 

After changing my google password I need not update it in KeePass. Is this normal or did I set up something wrong?

**Comment by Kyrodan** [comment]
This is correct: KeeAnywhere does not save your username or Password. You authorize KeeAnywhere "behalf" of you. so changing your password does not require to reauthenticate in KeeAnywhere.
-------- Ursprüngliche Nachricht --------Von: Thomase004 ***@***.***> Datum: 13.03.23  21:00  (GMT+01:00) An: Kyrodan/KeeAnywhere ***@***.***> Cc: Subscribed ***@***.***> Betreff: [Kyrodan/KeeAnywhere] New google password (Issue #373) 
Hi, I put my KeePass database to gdrive.
After changing my google password I need not update it in KeePass. Is this normal or did I set up something wrong?
