### ISSUE TITLE
Feature Request: Onedrive oAuth Authentication Failure with @businessname.com 

### ISSUE THREAD

**Issue by OC-M** [Kyrodan/KeeAnywhere#374]
Hi, 

Feature request please:

Onedrive does not authenticate to business based login, e.g. test@yourbusinessname.com.

Plugin uses the following URL to authenticate to a Microsoft account - https://login.live.com/oauth20_authorize.srf?client_id=...

However, business type accounts authenticate on - https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=....

Please could i request support for this authentication method.

Many thanks

**Comment by Kyrodan** [comment]
OneDrive business is not supported.
