### ISSUE TITLE
KeeAnywhere "Upgrade your browser to use Dropbox"

### ISSUE THREAD

**Issue by extraternet** [Kyrodan/KeeAnywhere#378]
Hi !
I didn't find this problem one github so i try.

I'm using Keepass with keeAnywhere but, since some month, when i try to used it for Dropbox i recieve this message "Upgrade your browser to use Dropbox"

![image](https://github.com/Kyrodan/KeeAnywhere/assets/19513535/767ba9b8-8576-4893-82a1-a8c4fe5ba0c3)

same problem with Keepass 2.53.1 and Anywhere 1.6.0.0 and 2.0.3.0

Has anyone had the same problem ?

Best regard,

**Comment by penunze** [comment]
In my case it was probably a rights privilege problem.
After I opened KeePass with administrator rights, my cloud account could also be legitimized via the browser.
I have done this successfully with FireFox and Chrome on Windows.

**Comment by Kyrodan** [comment]
in KeeAnywhere the authorization flow was changed to use system browser.
Please try with latest version 2.1.0
