### ISSUE TITLE
new win 11 install Load key DB google Not Work

### ISSUE THREAD

**Issue by ops99** [Kyrodan/KeeAnywhere#386]
hi i install my pc neu i Open DB on google Drive Past my PW and Klick on OK See error who can fix 
![bug](https://github.com/Kyrodan/KeeAnywhere/assets/63524719/0e15104f-4423-4fb6-a4f9-3c6339d65f08)

**Comment by Kyrodan** [comment]
Re-AUthentication is required but cirrently it does not work due to #393
