### ISSUE TITLE
Proton drive support

### ISSUE THREAD

**Issue by Artem2030** [Kyrodan/KeeAnywhere#388]
Hi.
I propose to add support for ProtonDrive service to the plugin

**Comment by Firedan1176** [comment]
I think the issue might be that Proton Drive doesn't have APIs available currently, so there's no NuGet package. Looks like Proton Drive is highly prioritizing encryption/privacy so creating a public API [isn't currently on priority](https://www.reddit.com/r/ProtonDrive/comments/z1bofb/comment/ixdoj6j/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), but this post was a while ago.

**Comment by Artem2030** [comment]
Good afternoon

However, rclone does support proton drive.
https://rclone.org/protondrive/

Why not implement proton drive support in your plugin?

**Comment by Kyrodan** [comment]
as stated in #364 there is no public API. I will not "hack into" somethin unsupported and then have to support all the user problems if something changed. I will keep an eye on this.
