### ISSUE TITLE
Adding Google drive account fails

### ISSUE THREAD

**Issue by virtuosonic** [Kyrodan/KeeAnywhere#393]
Adding a new account fails
![image](https://github.com/Kyrodan/KeeAnywhere/assets/22582422/c999e198-04d3-4abe-86c6-dd2371206d18)

1. click add button 
2. click google drive
3. I select the desired account
4. click on Continue button
5. Click on allow button

After that the browser goes to http://127.0.0.1:49215/ but returns ERR_CONNECTION_REFUSED and KeePass show the messagebox of the screenshot

I was running KeePass 2.56 with KeeAnywhere 2.0.3 on Windows 10 but in my office's computer (Windows 11 ) it is working with older version (2.51.1) so I installed that version here, but get the same result

I also tried running as administrator but it made no difference

**Comment by virtuosonic** [comment]
Also tried disabling the firewall

**Comment by Jackabomb** [comment]
1. Does the issue persist if you try adding the account multiple times in a row?
2. If it does keep happening continually, can you check and see if KeePass's "Empty Response" message show up even before you finish going through the OAuth windows in your browser? You will need to switch back to KeePass to see if it has shown up. It would really be helpful to know exactly where in the sequence of clicks the KeePass error box pops up.
3. What browser are you using on the office computer, and on the computer with the problem?
5. Does the issue persist across machine restart?
5. Does the issue persist if you uninstall and reinstall KeePass and KeeAnywhere?

**Comment by ElizaZadura** [comment]
For me the error appears later, when adding Google drive on a new installation. There's not even the usual advanced - continue anyway link.
![drive_blocked](https://github.com/Kyrodan/KeeAnywhere/assets/13031630/6040bf9b-74b4-4735-8742-0ada3af8f866)

**Comment by Jackabomb** [comment]
@ElizaZadura
Back in KeeAnywhere, are you seeing the same error message that @virtuosonic is seeing, or a different one? You said the error "appears later" for you. Could you give some more detail about when/where your error appears?

**Comment by Jackabomb** [comment]
Oh. Uh. Hm. I went Googling around and tried some advice to go to https://myaccount.google.com/permissions and delete the KeeAnywhere entry there. All of a sudden, good news! I can reproduce @ElizaZadura 's issue. Hooray!

Bad news, I don't yet know how to fix it, and am now stuck in the same boat, unable to re-add my Google account to KeeAnywhere.
So, yeah, maybe _don't_ delete the entries under https://myaccount.google.com/permissions, especially if you still have another working system. Instead, try copying over "C:\Users\<YourUserName>\AppData\Roaming\KeePass\KeeAnywhere.Accounts.json" from the old computer to the new, and see if that helps.

For completeness, I do *not* get the same KeeAnywhere message that @virtuosonic saw. Instead, KeeAnywhere hangs out on the authorize loading bar forever (until I click cancel).
![image](https://github.com/Kyrodan/KeeAnywhere/assets/48334975/7155f1be-c858-4c3c-a7b1-bd6da106d613)

**Comment by Kyrodan** [comment]
Hi together,

sorry for your inconvenience but Google changed API usage restrictions. They announced it long-term but I haven't had the time to dig into it. So currently KeeAnywhere is blocked by Google and it's my own fault. Prevously registered/aconnected accounts continue working. 
I will try to circumvent it shortly.

Regards,
Daniel

**Comment by gobenoit06** [comment]
please correct it asap, otherwise many users of your plugin won't use it anymore....thanks, its' urgent !!!!!

**Comment by Kyrodan** [comment]
I requested an extension to handle granular permissions at Google. They approved my request, but it still does not work. So sad.
Trying to update the plugin shortly.

**Comment by Kyrodan** [comment]
Just released v2.1.0 with one "new" provider: gdrive-restricted, access GDrive with lower privileges.
Maybe give it a try: you can only open files created by KeeAnywhere. 
Disadvantages so far: open and save is only possible in root folder - currently KeeAnywhere cannot create folders.
Feedback welcome.

**Comment by ElizaZadura** [comment]
> @ElizaZadura Back in KeeAnywhere, are you seeing the same error message that @virtuosonic is seeing, or a different one? You said the error "appears later" for you. Could you give some more detail about when/where your error appears?

Sorry for the late reply! I see the error in browser, after choosing add account - google drive in KeeAnywhere settings, which then redirects me to finish auth in browser window. Let me know if you need any addition screenshots or info.

**Comment by ElizaZadura** [comment]
> Just released v2.1.0 with one "new" provider: gdrive-restricted, access GDrive with lower privileges. Maybe give it a try: you can only open files created by KeeAnywhere. Disadvantages so far: open and save is only possible in root folder - currently KeeAnywhere cannot create folders. Feedback welcome.

Thank you! Much appreciated to see a fix so quickly. I have tried it, but it didn't work at first, which probably was because I had missed the bit about root folder restrictions, will have another go with that in mind :)

**Comment by virtuosonic** [comment]
Right now it's working, I'm using the same version, keepass 2.5.1 and keeanywhere 2.0.3, it looks like the change is something on google's side

**Comment by electrofloat** [comment]
> Just released v2.1.0 with one "new" provider: gdrive-restricted, access GDrive with lower privileges. Maybe give it a try: you can only open files created by KeeAnywhere. Disadvantages so far: open and save is only possible in root folder - currently KeeAnywhere cannot create folders. Feedback welcome.

Sooo.. is there a way to get back the previous functionality? I really need to have the file in a specific dir, and also it was created before, so it is not created by KeeAnywhere.

**Comment by michalkochanowicz** [comment]
I switched to "restricted" on my laptop, but now my desktop is unable to open file created by laptop.

I tried to copy "C:\Users<YourUserName>\AppData\Roaming\KeePass\KeeAnywhere.Accounts.json" from my laptop to the desktop but this results with error:

Unable to parse the plugin's account configuration for the KeeAnywhere plugin from local secure store: Decryption of secret failed"

I also tried to copy entire "C:\Users<YourUserName>\AppData\Roaming\KeePass", with same result.

Is there a way to share keystore between two computers?

**Comment by Jackabomb** [comment]
> Sooo.. is there a way to get back the previous functionality? I really need to have the file in a specific dir, and also it was created before, so it is not created by KeeAnywhere.

@electrofloat No one has been able to find a workaround yet. I think this is just something Google and Kyrodan have to work out. If you find one, please post it here!
Well, I do know of one workaround (discovered by accident while I was doing test builds for an unrelated PR), but it's very tedious: If you pull the source code and build the plugin from source yourself, using your own OAuth2 ClientID and Secret (which you would have to setup with Google yourself), _and_ set your app status to "testing" with Google in their OAuth dashboard... then it works. You don't see the error. However, as a "testing" app, the OAuth tokens expire much sooner, I think weekly, so you're constantly having to re-authorize the account. They can only be used by accounts on a whitelist (again, arranged between you and Google) and are limited to 100 users.
So theoretically it works, but I think it's too complicated and too limited to have practical value as a workaround.

Personally, I've just been manually uploading/downloading the KeePass DB file with the Google Drive web UI for the time being.
You could also temporarily move your DB to a different cloud provider.

**Comment by Jackabomb** [comment]
> I switched to "Google Drive restricted" on my laptop, but now my desktop is unable to open file created by the laptop.
> 
> I tried to copy "C:\Users\AppData\Roaming\KeePass\KeeAnywhere.Accounts.json" from my laptop to the desktop but this results in error:
> 
> Unable to parse the plugin's account configuration for the KeeAnywhere plugin from local secure store: Decryption of secret failed"
> 
> I also tried to copy entire "C:\Users\AppData\Roaming\KeePass", with same result.
> 
> Is there a way to share keystore between two computers?

Oh, right. Of course that wouldn't work. I forgot that the tokens are, in fact, [encrypted](https://github.com/Kyrodan/KeeAnywhere/issues/348#issuecomment-2211207069) to your local machine.
There might still be a way, but it won't be as simple as copying the file like I suggested.

**Comment by electrofloat** [comment]
@Jackabomb Unfortunately I had to revert back to a rclone/triggers workflow which I was already using on Linux. It just works™.
 
This plugin was great and convenient but I have to move on with my life, I have to use keepass with GoogleDrive and I don't have the time to wait until this is fixed here.

But thanks for the plugin anyways, it was great!

**Comment by pascal69480** [comment]
> Had the same trouble with "The app is blocked" after trying to login to Google via backup-code ( :-( ). Found a posting (from another app) where they stated: simply delete the app-credentials from your Google-Account, delete the google-config from the app and re-register ... which did not work for KeeAnywhere. Here's how to get it working again with KeeAnywhere-v2.1.0:
> 
> * make a local copy of your KeePass-database ... KeeAnywhere does not see the "old" copy, even if it's in the root go Google-Drive
> * configure the "GoogleDrive restricted" account
> * load your local copy of the KeePass-database
> * do a SaveAs to Clouddrive using the GoogleDrive restricted account (well, another filename ... added _GC to be able to distinguish, don't think you can overwrite the original).
>   Still have to try out, if/how interaction with other apps will work.

Thanks a lot !!!!!

**Comment by ElizaZadura** [comment]
> Had the same trouble with "The app is blocked" after trying to login to Google via backup-code ( :-( ). Found a posting (from another app) where they stated: simply delete the app-credentials from your Google-Account, delete the google-config from the app and re-register ... which did not work for KeeAnywhere. Here's how to get it working again with KeeAnywhere-v2.1.0:
> 
>     * make a local copy of your KeePass-database ... KeeAnywhere does not see the "old" copy, even if it's in the root go Google-Drive
> 
>     * configure the "GoogleDrive restricted" account
> 
>     * load your local copy of the KeePass-database
> 
>     * do a SaveAs to Clouddrive using the GoogleDrive restricted account (well, another filename ... added _GC to be able to distinguish, don't think you can overwrite the original).
>       Still have to try out, if/how interaction with other apps will work.

I managed to get it to work using this method, even though the "Google drive restricted" didn't work on earlier attempts. Thank you!

**Comment by Hau-Hau** [comment]
I'm getting same error as @ElizaZadura.
KeeAnywhere has been removed from https://myaccount.google.com/permissions and I don't see it on the list...
When I'm trying re-authenticate with app, I'm getting error:
![image](https://github.com/user-attachments/assets/31d681be-a921-4005-a74a-6d10ef397806)

Is there any known solution/bypass for that issue?

**Comment by ElizaZadura** [comment]
> I'm getting same error as @ElizaZadura.
> KeeAnywhere has been removed from https://myaccount.google.com/permissions and I don't see it on the list...
> When I'm trying re-authenticate with app, I'm getting error:
> ![image](https://github.com/user-attachments/assets/31d681be-a921-4005-a74a-6d10ef397806)
> 
> Is there any known solution/bypass for that issue?
> 
Have you tried the solution posted by @KurtKrummbein ? That's the only one that's worked for me so far

**Comment by Hau-Hau** [comment]
@virtuosonic Why did you closed this issue? It is still occurring.

@ElizaZadura I've tried but there are two problems. First. I don't really understand what point "configure the 'GoogleDrive restricted' account" means.
And second, in my case it seems not related to file on GD.

**Comment by pascal69480** [comment]
> * load your local copy of the KeePass-database
> * do a SaveAs to Clouddrive using the GoogleDrive restricted account (well, another filename ... added _GC to be able to distinguish, don't think you can overwrite the original).
>   Still have to try out, if/how interaction with other apps will work.

Have you tried these steps ?

> load your local copy of the KeePass-database
> do a SaveAs to Clouddrive using the GoogleDrive restricted account (well, another filename ... added _GC to be able to distinguish, don't think you can overwrite the original).
> Still have to try out, if/how interaction with other apps will work.

**Comment by Hau-Hau** [comment]
I managed to configure restricted mode and indeed seems that it is working. 
Is there any chance it would support different directories than root?

**Comment by virtuosonic** [comment]
> @virtuosonic Why did you closed this issue? It is still occurring.
> 
> @Kyrodan I cannot select database in restricted mode. Is it known problem?

It suddenly started to work just a few days after I created the issue and I see others are confusing this one with different ones

**Comment by Jackabomb** [comment]
@michalkochanowicz I have created a pair of command line utilities that can decrypt the Secret on your functioning machine, then re-encrypt it on your new machine you are trying to setup: [Unprotect_and_Reprotect.zip](https://github.com/user-attachments/files/16700544/Unprotect_and_Reprotect.zip)

Usage:

1. Unzip on your old machine.
2. From the command line, run `Unprotect`. Copy and paste the base64 secret (without quotes) from KeeAnywhere.Accounts.json.
3. Press enter. `Unprotect` will spit out a new line with the (base64-encoded) plaintext.
4. Copy this onto a thumb drive or otherwise transfer it to your new machine.
5. *On your new machine*, run `Reprotect` from the command line. Copy and paste the base64 plaintext into it and press enter.
6. `Reprotect` will spit out a new line with the base64 secret, suitable for your new computer.
7. Copy and paste this into the secret field in KeeAnywhere.Accounts.json on the new computer.

Anyone else is welcome to try this too (and maybe report back). Note, this will only work if your "old machine" still has a working access token and is not getting the error message. If you're trying to set up a Google Drive account with KeeAnywhere for the first time, or if - like @Hau-Hau and me - you've deleted KeeAnywhere from https://myaccount.google.com/permissions , this trick will not help you.

**Comment by martin-shortall-nbi** [comment]
> @michalkochanowicz I have created a pair of command line utilities that can decrypt the Secret on your functioning machine, then re-encrypt it on your new machine you are trying to setup: [Unprotect_and_Reprotect.zip](https://github.com/user-attachments/files/16700544/Unprotect_and_Reprotect.zip)
> 
> 
> 
> 1. Unzip on your old machine.
> 2. From the command line, run `Unprotect`. Copy and paste the base64 secret (without quotes) from KeeAnywhere.Accounts.json.
> 3. Press enter. `Unprotect` will spit out a new line with the (base64-encoded) plaintext.
> 4. Copy this onto a thumb drive or otherwise transfer it to your new machine.

@Jackabom I tried this but got the following exception - my secret is long ~ 436 characters - is this correct? I pasted it without the quotes

`Unhandled exception. System.Security.Cryptography.CryptographicException: The parameter is incorrect.
   at System.Security.Cryptography.ProtectedData.ProtectOrUnprotect(Byte[] inputData, Byte[] optionalEntropy, DataProtectionScope scope, Boolean protect)
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Program.<Main>$(String[] args)`

**Comment by tbayart** [comment]
Google Drive restricted mode worked for me to authenticate but i'm unable to use it since I'm synching same kdbx databases with different machines (windows, android...)
Will be a nightmare for me to move the databases

> I have created a pair of command line utilities that can decrypt the Secret on your functioning machine, then re-encrypt it on your new machine you are trying to setup: [Unprotect_and_Reprotect.zip](https://github.com/user-attachments/files/16700544/Unprotect_and_Reprotect.zip)

Worked like a charm for me
Note : I did not removed keeAnywhere from my google account

**Comment by Jackabomb** [comment]
@michalkochanowicz Hm. My encrypted secret straight out of accounts.json is 324 bytes. Unprotect gives me 140 bytes of decrypted base64. Decoding the base64 gives me a final secret length of 103 bytes. The lengths might be different because I'm stuck on the restricted account now.
I cannot reproduce your error, but make sure you are running each program on the right PC. Unprotect must run on your "old" machine. Reprotect must run on your "new" machine.

**Comment by martin-shortall-nbi** [comment]
Thanks for your reply @Jackabomb 
I had another go and this time it worked!!  I had originally not followed the instructions correctly - I was using the correct computers (old and new) but I thought the instruction was, from cli.

`Unprotect.exe <paste secret here> [Enter]` 
Then copy and paste.... instead what I should have done was...

**`Unprotect.exe[Enter]`
`<paste secret here> [Enter]`**
...and copy,paste the result into the Reprotect command on new computer.

What I has originally done was pass the secret to unprotect on the same line as an argument and then pressed enter with no secret on the 2nd line where unprotect was expecting me to enter the secret. 

Great to have it working properly again as I sync database from google drive to android and Mac as well as Win11.... I should probably think about moving to a restricted account.

**Comment by buchfelder** [comment]
> Unhandled exception. System.Security.Cryptography.CryptographicException: The parameter is incorrect. at System.Security.Cryptography.ProtectedData.ProtectOrUnprotect(Byte[] inputData, Byte[] optiona

I have the same issue with a long secret. Please fix the unprotect / reprotect tools. Google Drive is blocked and Google Drive restricted is not working. I have to machines fully capable of Google Drive in KeeAnywhere 2.1.0

**Comment by Jackabomb** [comment]
> I have the same issue with a long secret. (Powershell and Terminal Console in Win11) . Please fix the unprotect / reprotect tools.

@buchfelder 
Are you pasting the secret in the right order? Don't paset your secret until [_after_ you have pressed enter](https://github.com/Kyrodan/KeeAnywhere/issues/393#issuecomment-2344334248). The tools expect the secrets/tokens/input on standard input, not on the command line.

Also, verify that you are running the [right tool](https://github.com/Kyrodan/KeeAnywhere/issues/393#issuecomment-2303114938) on the [right machine](https://github.com/Kyrodan/KeeAnywhere/issues/393#issuecomment-2344049556).
Unprotect has to run on your old, _currently-working_ machine. If you try to run Unprotect on a machine that is already having the access error, it is too late.
Reprotect has to run on the new machine.

**Comment by buchfelder** [comment]
> @buchfelder Are you pasting the secret in the right order? Don't paste your secret until [_after_ you have pressed enter](https://github.com/Kyrodan/KeeAnywhere/issues/393#issuecomment-2344334248). The tools expect the secrets/tokens/input on standard input, not on the command line.

@Jackabomb Oh, I used params instead of stdin. Thank you so much!!! It works like a charm  (as long as you preserve your Keeanywhere Permissions in Google).

**Comment by Jackabomb** [comment]
@YAMLcase 
Just uploaded it [here](https://github.com/Jackabomb/dotnet-protect-cli)

**Comment by TohnoCoding** [comment]
If you're having issues running @Jackabomb's CLI apps (like I was), y'all might want to try using these PowerShell scripts. The code is exactly the same as the CLI apps but in PS, preventing any kind of environment error or anything from DotNet being finnicky.

Unprotect.ps1
```
$input = Read-Host "Enter the Base64-encoded encrypted data from the source host:"
$decryptedData = [System.Security.Cryptography.ProtectedData]::Unprotect(
    [Convert]::FromBase64String($input),
    $null,
    [System.Security.Cryptography.DataProtectionScope]::CurrentUser
)
Write-Output "`nHere's your output encoded string:`n"
Write-Output ([Convert]::ToBase64String($decryptedData))
```

Reprotect.ps1
```
$input = Read-Host "Enter the Base64-encoded encrypted data for the target host:"
$decryptedData = [System.Security.Cryptography.ProtectedData]::Unprotect(
    [Convert]::FromBase64String($input),
    $null,
    [System.Security.Cryptography.DataProtectionScope]::CurrentUser
)
Write-Output "`nHere's your output encoded string:`n"
Write-Output ([Convert]::ToBase64String($decryptedData))
```

Logic stays the same: Unprotect runs on the source machine, Reprotect runs on the target machine. I was able to get my KeeAnywhere running without issues with this.

**Comment by buchfelder** [comment]
Thanks. After using unprotect+reprotect for a week today I found that my secret had changed in the meantime. Looks like it gets updated which renders this workaround useless i.e. copying secrets will only guarantee a few days of work I'm afraid.... Am I the only one facing this issue?

**Comment by Jackabomb** [comment]
@buchfelder would you open an issue in the source repo?

I think at this point all problems with unprotect and reprotect should have their own issue in the separate repo I made.

I don't think we should flood this thread with them, especially since there are turning out to be more issues than I expected.

**Comment by buchfelder** [comment]
> @buchfelder would you open an issue in the source repo?
yes, in keeanywhere or jackabombs cli ?

**Comment by buchfelder** [comment]
Another error ahead  
![grafik](https://github.com/user-attachments/assets/f55d09f5-bd0a-42d2-b012-5da167ebb8bd)
After re-initializing the Google Drive authorization I get the famous "this app is blocked" now on all devices (even those that worked before)

**Comment by RozJC** [comment]
Hello,

I tried to access my Google Drive-based database and I am also seeing the same error that buchfelder sees.

**Comment by jaykup26** [comment]
What worked for me:

Update the extension to the latest version (Tools -> Plugins -> Open Folder) by copying the KeeAnywhere-2.1.0.plgx from this github repository into that folder and deleting any old versions.  Close and re-open KeePass 2 so it reloads plugins.

Remove existing Google Drive and add back as "Google Drive Restricted" by going to Tools -> KeeAnywhere Settings.  Make sure to check the "See, edit, create, and delete only the specific Google Drive files you use with this app" on Google's authorization page that pops up.

Save an opened local database into Google Drive by going to File -> Save As -> Save to Cloud Drive.

NOTE: This will save the database to Google Drive's root directory.

**Comment by RozJC** [comment]
@jaykup26 that seems to have done the trick for me.

Didn't even realise there was a "restricted" version of Google Drive in the list.

Quick question though....is it possible to not save it to the root directory?

**Comment by tbayart** [comment]
> Thanks. After using unprotect+reprotect for a week today I found that my secret had changed in the meantime. Looks like it gets updated which renders this workaround useless i.e. copying secrets will only guarantee a few days of work I'm afraid.... Am I the only one facing this issue?

sept 11th it worked for me, since then I didn't changed anything and it's still working

**Comment by RolfSo** [comment]
> jaykup26

Thank you for the solution!
With your help it works again for me too.

**Comment by huttsMichael** [comment]
Jaykup26's explanation worked for me as well, thanks! 

Just to spell it out for anyone else who was a little confused when the new restricted GDrive connection showed an empty directry listing like myself, you won't see any existing files when you set up GDrive Restricted. If you had an existing setup DB in GDrive, download that file to your local system, open it with KeePass, then Save As -> Save to Cloud Drive. That will write it to your GDrive in a way that KeeAnywhere can see and access.

**Comment by jfandl325** [comment]
I was able to get that to work ONLY if you select the checkbox where you select what KeeAnywhere can access.  See, edit, create, etc.  If you do not check this box, you will not be able to authenticate to google.  I tried it multiple times and the process is repeatable every time.

![KeeAnywhere](https://github.com/user-attachments/assets/16246b4f-0219-478f-bae2-9a78504a58fb)

**Comment by hans-enders** [comment]
Kyrodan, thank you for chasing this with Gdrive, keep up the good work. I "purchased" KeePass and KeeAnywhere for my entire family of four several years ago, and eventually even my teens thanked me for helping them get it onto both their laptops and phones.  Lifesaver!  Enjoy those beers!

**Comment by tbayart** [comment]
> > Thanks. After using unprotect+reprotect for a week today I found that my secret had changed in the meantime. Looks like it gets updated which renders this workaround useless i.e. copying secrets will only guarantee a few days of work I'm afraid.... Am I the only one facing this issue?
> 
> sept 11th it worked for me, since then I didn't changed anything and it's still working

Spoke too quickly, stopped working monday 18th
Keeanywhere is no longer working for me and the _restricted mode_ is not an option
lack of time to search for a solution or an alternative

**Comment by m-horejsi** [comment]
> I was able to get that to work ONLY if you select the checkbox where you select what KeeAnywhere can access. See, edit, create, etc. If you do not check this box, you will not be able to authenticate to google. I tried it multiple times and the process is repeatable every time.
> 
> ![KeeAnywhere](https://private-user-images.githubusercontent.com/188882577/387729325-16246b4f-0219-478f-bae2-9a78504a58fb.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTY2MzUsIm5iZiI6MTczMjYxNjMzNSwicGF0aCI6Ii8xODg4ODI1NzcvMzg3NzI5MzI1LTE2MjQ2YjRmLTAyMTktNDc4Zi1iYWUyLTlhNzg1MDRhNThmYi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMDE4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDhmMDg5YzAxM2RlMWUzMTMxZWY2MzgwNDQzMDNjMzQ1YzY5Njc1ODc4YTA5ODJkNjIzMGQ2NmU5OWJmZjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zIJeR90ZZovOUzvmG-WCcgPa_Ic4rpZ1DcDuFP2wCuo)

You are lucky guy if you see the option. I can't see anything like this.. 
Restricted mode is not solution for me, so I hope the problem will be solved soon. Else I will have to take a look for another option/plugin
