### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by sn00py1310** [Kyrodan/KeeAnywhere#394]
I love the plugin for KeePass, but it seems there hasn't been any patche since 2021.
It's sad that such a great plugin isn't updated or fixed anymore.
So I suggest if there isn't positive response withing 1 week the community should create a fork.

This would be good because there some good PRs open like #376 or #377.

**Comment by brogers5** [comment]
The maintainer recently chimed in on this in a separate issue (https://github.com/Kyrodan/KeeAnywhere/issues/242#issuecomment-2039250418).

**Comment by Kyrodan** [comment]
I would say yes, just release 2.1.0 which includes the mentioned PR ;-)
