### ISSUE TITLE
App Lost Google Verification Status? aka Can't Add New Google Accounts

### ISSUE THREAD

**Issue by Jackabomb** [Kyrodan/KeeAnywhere#399]
It looks like there may be an issue with KeeAnywhere's App Verification status.
The error screen that @ElizaZadura and I encountered in #393 is almost identical to [this one that Google says you get](https://support.google.com/cloud/answer/7454865#unverified-app-user-cap) if an unverified app exceeds [100 users](https://support.google.com/cloud/answer/7454865#oauth-quota).
![image](https://lh3.googleusercontent.com/29JLsM6bC3fFQbHZZ8GpZ7vYS82DmReRSfSYF4VYOkyUpLiIU6KHjvDOTCieyRv0Grk=w895)

Plus, I had no problem re-authorizing an account I had already added, nor even removing and re-adding the account. But as soon as I deleted KeeAnywhere from my [Google Security dashboard](https://myaccount.google.com/permissions) I suddenly began having the same problem.

Googling the error message led to [this article](https://support.nylas.com/hc/en-us/articles/4486222402449-Receiving-The-App-is-Blocked-or-Google-hasn-t-verified-this-App-error-message-while-attempting-to-authenticate-Google-accounts), which supports the idea that the App is missing a verification.

This Google support page also supports the idea that KeeAnywhere would [require verification](https://support.google.com/cloud/answer/10311615#verification-status):

> Google verifies projects … if … Your project's OAuth clients request authorization of any sensitive or restricted scopes. …

More info here also:
https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes

Unfortunately, we use `drive`  (as discussed in #398 ), which is one of those [restricted scope](https://support.google.com/cloud/answer/13464325?ref_topic=13460882&sjid=14559507189252804093-NC#zippy=%2Cgoogle-drive-api).
https://github.com/Kyrodan/KeeAnywhere/blob/ebeb344177353ad663e1d0270920f7ca057b737c/KeeAnywhere/StorageProviders/GoogleDrive/GoogleDriveHelper.cs#L39
The official list of restricted scopes was not easy to find. I never did find the sensitive list.

I don't remember seeing [this screen](https://support.google.com/cloud/answer/7454865#unverified-app-screen) in the past, which makes me think this app _was_ verified in the past and has somehow lost that status?

Compiling my own copy, with my own test client_id and client_secret (and no other changes) made it so I did not get this issue.
It's also possible that the change suggested in #398, switching the scope to `drive.files` might help. Even though - as I said in the other issue - I prefer using `drive`, I admit that `drive.files` has a chance of working, because it is not in the restricted scopes list, and Google seems to take those extremely seriously.

**Comment by gobenoit06** [comment]
Hey Mister Keeanywhere, any news about this MAJOR PROBLEM ? this prevents to use your plugin, please do something asap otherwise I can tell you that your plugin is dead !!! wake up, now

**Comment by Kyrodan** [comment]
Duplicate to #393.
