### ISSUE TITLE
Unable to use Keeanywhere anymore on Google drive!!!

### ISSUE THREAD

**Issue by gobenoit06** [Kyrodan/KeeAnywhere#400]
hey Mister Bolts, please do something asap, as Google does not allow anymore to use keeanywhere with google drive.

scenario: migrate to any new version of Keepass (2.57, for example), install keeanywhere plugin: you cannot anymore connect to google drive.

if you do not do something, it means the plugin is dead...

**Comment by tclarke** [comment]
same problem here

**Comment by Kyrodan** [comment]
Duplicate to #393.

@gobenoit06:
It does not help to pollute the issues here. It won't fix this issue faster the more you reply. I maintain this plugin in my spare time. As statet several times: feel free to use this plugin as-is or use something else. I created this plugin and made it publically available in mind that it is maybe usefull to someone else. I don't agree, that I have any obligations to maintain this plugin in demand of others. Sadly I understand your point of view, but that's maybe the downside of using open source.
