### ISSUE TITLE
Syncing multiple accounts at the same time

### ISSUE THREAD

**Issue by tockar** [Kyrodan/KeeAnywhere#42]
When saving my local database, KeeAnywhere saves the database only on one cloud provider - the last one I've used with the "Save -> Save to Cloud Drive..." menu. Tested with KeePass 2.34 and KeeAnywhere 1.1.0.
I need to manually save the database on my other two cloud drives to have an up to date database on all my drives. I like multiple backups.

Is there a chance for syncing all/multiple accounts at the same time? Ideally there would be a option to select multiple accounts and include them in the syncing process with every database update.

**Comment by Kyrodan** [comment]
KeeAnywhere itself does not do any syncing. But if you like to keep multiple copies of you database on different cloud providers you can use KeePass's built-in synchronization features. For example you can use a trigger that saves you "master" database to some other providers. See details [here](http://keepass.info/help/v2/sync.html). For saving to a cloud drive you only need the complete "URL" to the (target) database, which you can get from the "Open from cloud drive"/"Save to cloud drive" window. Just use this URL for the synchronization action. You do not need to supply credentials for "IO Connection".

**Comment by Kyrodan** [comment]
By the way: another option is to use cloud mirroring service like http://mover.io which completely or partly backs up your cloud drives to another one.
