### ISSUE TITLE
KeeAnywhere not compatible with KeePass 2.34

### ISSUE THREAD

**Issue by philled** [Kyrodan/KeeAnywhere#43]
I've just upgraded to KeePass v2.34 after the constant nag screens when starting KeePass. Unfortunately that has now rendered KeePass inoperable because on startup I now get an error saying that KeeAnywhere "is incompatible with the current KeePass version".

![image](https://cloud.githubusercontent.com/assets/12024578/16402142/85ca4a4a-3d2d-11e6-9d22-87dbd6caa61b.png)

I'm running it on a Portable Apps USB drive. Is that correct that neither KeeAnywhere 1.0.0 nor 1.1.0 are compatible with KeePass v 2.34? If so, what is the highest KeePass version that it is compatible with?

**Comment by Kyrodan** [comment]
Hi @philled,

KeeAnywhere is completely compatible with KeePass 2.34. It seems that a file from KeePass distribution is missing: KeePass.exe.config. Please make sure this file exists and has the following content:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<startup>
		<supportedRuntime version="v4.0" />
		<supportedRuntime version="v2.0.50727" />
	</startup>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="KeePass"
					publicKeyToken="fed2ed7716aecf5c"
					culture="neutral" />
				<bindingRedirect oldVersion="2.0.9.0-2.34.0.0"
					newVersion="2.34.0.15991" />
			</dependentAssembly>
		</assemblyBinding>
		<enforceFIPSPolicy enabled="false" />
		<loadFromRemoteSources enabled="true" />
	</runtime>
	<appSettings>
		<add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
	</appSettings>
</configuration>
```
