### ISSUE TITLE
Sometimes can't load kdbx file (Dropbox, hubiC)

### ISSUE THREAD

**Issue by Kuannz** [Kyrodan/KeeAnywhere#44]
The plugin can't load kdbx file on Dropbox today.
Error: "The stream does not support writing"
http://i.imgur.com/6x9LT1M.png
Not sure if it's a problem with Dropbox or the plugin itself.
The sync function still works fine on my phone app Keepass2Android.

**Comment by Kyrodan** [comment]
Hi @Kuannz,

could you please try it again today? Currently I'm not able to reproduce this but I saw this error several times ago. 

Regards,
Daniel

**Comment by Kami1680** [comment]
same issue here :(
http://puu.sh/pMKeR/08112dbd9d.png

**Comment by ty2u** [comment]
I'm having the same issue. Can't figure out any reason for it.

**Comment by Kyrodan** [comment]
Hi @Kami1680 @Kuannz @ty2u,

which Version of KeeAnywhere are you using? 1.1.0? If not 1.1.0, please try it with this version and report back your result.
Is it possible, that you don't have write access to the database file?

**Comment by ty2u** [comment]
Hi there!

Yes I am using 1.1.0.

I believe I did have access to write to the file because I didn't change anything and it had worked before perfectly fine up until then. It wasn't the first time I tried using KeeAnywhere, I had been using it for awhile just great.

I don't really ever use Dropbox for anything else so I don't think it was something I did in there.

I too could also access it fine on my phone using Keepass2Android. However, I didn't even use Keepass2Android between the last successful use of KeeAnywhere and the first unsuccessful use.

I switched to using my local file for the day and just tried switching back to the dropbox url and it works fine again now. So I'm not entirely sure what the issue was.

**Comment by Kyrodan** [comment]
Hi again @Kami1680 @Kuannz @ty2u,

* what OS are you using? 
* Are you using PLGX-Distribution or (binary) DLL-Distribution? 
* Which KeePass version are you using?

Thanks again.

**Comment by ty2u** [comment]
- I am on Windows 8.1
- DLL
- KeePass 2.34
- Yes there is, KeePassHttp, KeePassRPC (both plgx)

I just realized another thing which maybe could have caused it. I also seem to have a few triggers set which do stuff to try and autosave when I make changes, sync on start, and sync on lock. Those seem like possible candidates for conflicts and I wonder if those could have somehow caused it. I guess if it happens again I will try disabling those and see if it fixes it. It seems odd it was fine all this time and for awhile I just couldn't do anything. It would be nice if there was a better way to do those things anyway as they seem like they may be buggy.

**Comment by Kami1680** [comment]
1. - Windows 10 64bit
2. - KeeAnywhere-1.1.0.plgx
3. - KeePass 2.34
4. - KeePassHttp is installed

i've changed to hubic works flawlessly ;D
i had favico downloader plugin before installed https://sourceforge.net/projects/keepass-favicon/

**Comment by Kuannz** [comment]
1. Windows 10 64-bit
2. PLGX-distribution
3. KeePass 2.34
4. No other plugins

**Comment by chirel** [comment]
Hi, Same problem here
1. Windows Seven
2. Dunno where to check
3. KeePass 2.34 / KeePassLibC 1.31 (0x0192)
4. KeeCloud (not working also with same error).

**Comment by Kyrodan** [comment]
Ok guys, 

I found the source of the problem and working on a fix. Please give me another few days as I maybe have to contact the author of KeePass.

**Comment by Kyrodan** [comment]
Waiting for response in KeePass Issue Tracker. See https://sourceforge.net/p/keepass/feature-requests/2160/

**Comment by Kyrodan** [comment]
Hi all,

here is a new preview snapshot. Please test it and give me feedback, whether this snapshot fixes this issue for you.
**THESE SNAPSHOTS SHOULD NOT BE USED PRODUCTIVE!**

https://dl.dropboxusercontent.com/u/68134839/KeeAnywhere-1.2.0-unstable.plgx
https://dl.dropboxusercontent.com/u/68134839/KeeAnywhere-1.2.0-unstable.zip

If feedback is positive I will release a new version very shortly.

Regards,
Daniel

**Comment by Kyrodan** [comment]
Hi @Kuannz @Kami1680 @ty2u @chirel,

no one has tried it?
> Please test it and give me feedback, whether this snapshot fixes this issue for you.

**Comment by Kuannz** [comment]
I just tested it. Loading and saving on Dropbox look all good now.
Thanks for the fix.
