### ISSUE TITLE
Cannot authorize Google Drive regular or restricted

### ISSUE THREAD

**Issue by penguinslovebananas** [Kyrodan/KeeAnywhere#440]
Today I wiped and reinstalled Windows on my Legion 5 pro 16ARH7H type 82RG laptop. Before the wipe I was able to use drive in the restricted mode, but now when I tried to set everything up I am unable to authorize drive with either option. I removed Keepass and deleted all settings/files/registry entries and reinstalled everything without success. I followed the same procedure for all combinations of Keepass 2.57.1 and 2.57 with Keyanywhere versions 2.1.0 and 2.0.2 and nothing worked. I consistently get the same error everytime. I have removed Keeanywhere from my google account and just about every other troubleshooting method I know and several from this site. Hopefully it is something easy to fix and I am just overlooking it. 

**To Reproduce**
Enter keeanywhere settings.
Add either Google Drive or Restricted
Browser opens
I select my Google account and log in
On the confirmation page i select the check box to limit access to files
Browser says "Received verification code. You may now close this window. "
Error Message

**Expected behavior**
I should be able to authorize, it has worked on this laptop before and it works with my other 3 computers. I have tried completely signing out of my Google account, authorizing in a private window and with different browsers, no luck.

![Screenshot 2024-11-18 145949](https://github.com/user-attachments/assets/42afec36-5066-4d29-a409-dc078f161227)

**Environment:**
Windows 11 Pro 24H2 26100.2033
Keepass 2.57.1 and 2.57
Keeanywhere 2.1.0 and 2.0.3

**Comment by Jackabomb** [comment]
Since it mentioned the token is expired, perhaps your system clock is slightly off?

**Comment by penguinslovebananas** [comment]
> Since it mentioned the token is expired, perhaps your system clock is slightly off?

You were spot on. It was my clock. I didn't even think to look at it. It seems like this catches me at least once a year, just long enough for me to forget about it. Thanks again.
