### ISSUE TITLE
hubic: can't load database

### ISSUE THREAD

**Issue by Kami1680** [Kyrodan/KeeAnywhere#46]
i just woke up and tried to load up my database, now i have exactly the same error like with Dropbox ( see https://github.com/Kyrodan/KeeAnywhere/issues/44 ) 
Screenshot http://puu.sh/q7WBu/255b2e0582.png
no new plugin(s) installed and no config/setup change.

**Comment by Kyrodan** [comment]
Closing this due to the same reason in #44. Please continue discussion there.
