### ISSUE TITLE
Open kdbx file from OneDrive with KeeAnywhere 1.2.0 and KeePass 2.34

### ISSUE THREAD

**Issue by alcoda1** [Kyrodan/KeeAnywhere#53]
Hi 
I try to my kdbx file from OneDrive. My OneDrive account seems properly configured in "KeeAnywhere Settings". The "check" button reports "Connecting to this account succeeded". 

The "Open from Cloud Drive" dialog reports "Error loading file list for account... / Exception: The method or operation is not implemented."

Best regards
Roman

**Comment by Kyrodan** [comment]
Please try newly released [Version 1.3.0](https://github.com/Kyrodan/KeeAnywhere/releases/tag/v1.3.0). 
If the problem continues to exist, please reopen this issue.
