### ISSUE TITLE
KeeAnywhere doesn't use specified KeePass Proxy

### ISSUE THREAD

**Issue by bhuddah** [Kyrodan/KeeAnywhere#55]
KeeAnywhere doesn't use specified KeePass Proxy

**Comment by Kyrodan** [comment]
@bhuddah,

could you please provide more details.
Especially:
* Which provider(s) does/do not work?
* What are settings in KeePass for your Proxy - please attach a screenshot
* Does an error message appear? If yes: please provide the detailed information (clicking on "Details" in KeePass' error dialog or create a snapshot of any other dialog)

The more infos you provide, the better I can find a possible problem.

**Comment by bhuddah** [comment]
Hi,

- all providers end up with the same error message. (see attached screenshot)
- see attached screenshot for proxy settings (as you can see the proxy is a local ssh forwarded tunnel to a remote squid proxy)

![proxy_settings](https://cloud.githubusercontent.com/assets/1134116/18625185/10fc9a4a-7e4d-11e6-8936-4bb721b40362.PNG)
![error_message](https://cloud.githubusercontent.com/assets/1134116/18625186/1102016a-7e4d-11e6-8e6e-5fc620a2d444.PNG)

**Comment by Kyrodan** [comment]
Ok,

For registering an account, KeeAnywhere embeds Internet Explorer in the authorization window. So you have to manage *system* proxy settings (in Control Panel - Internetoptions), too.

*After* successfully registering an account, this setting is no longer needed, as KeeAnywhere then uses it's own proxy settings (from KeePass).

This is a drawback, I know, but currently there is no simple alternative.

Does this information solves your problem?

**Comment by bhuddah** [comment]
Yes, indeed it does.
Thanks a lot!

**Comment by ilvetz** [comment]
I reopen the issue. I cannot open a kdbx file hosted on a Dropbox folder (restricted or not), with KeeAnywhere already configured.

KeeAnywhere seems to use system proxy settings or fails DNS resolutions, even if direct Internet connection is available and static routes are used only for private network resources.

![dropbox_proxy_error](https://user-images.githubusercontent.com/5400713/36098133-0f6aeaa8-0ffe-11e8-99fc-b3b15c898a4d.jpg)
