### ISSUE TITLE
Add support for Pydio (private cloud)

### ISSUE THREAD

**Issue by dnauck** [Kyrodan/KeeAnywhere#57]
[Pydio](http://www.pydio.com) is an open source private file sharing tool, like Dropbox.

**Comment by Kyrodan** [comment]
Hi @dnauck ,

the same answer for OwnCloud is also valid for Pydio:
1. Pydio supports WebDav, so there is no need for KeeAnywhere to access Pydio (I know: everyone likes the File Picker :-) maybe someone else writes a file picker for WebDav/FTP/etc. )
2. I don't like to implement private cloud (self-hosted) solutions. The reason: for development I have to manage one instance by my own. And that's to much effort for me.

I hope you respect my decision,
Daniel
