### ISSUE TITLE
Open GDrive file in CMD without cloud credentials prompt

### ISSUE THREAD

**Issue by Suncatcher** [Kyrodan/KeeAnywhere#59]
I want to implement such scenario: certain KeePass base should be opened via shortcut on system start or manually. I created shortcut with following command:

    "KeePass.exe" "gdrive:///[account_name]/[database_file].kdbx" -pw:[pass] -minimize`

However on start it shows me password prompt:

![default](https://cloud.githubusercontent.com/assets/6388034/19213909/07825c06-8d80-11e6-97b9-7af57e7fd784.png)

Even if I select "Remember" it has no effect on program behavior.
Is there any CMD syntax I can use to specify credentials of cloud account permanently in order not to type them every time?

**Comment by Kyrodan** [comment]
Hi @Suncatcher 

from KeePass documentation for CMD-Line-Options (http://keepass.info/help/base/cmdline.html):

> The -iocredfromrecent switch makes KeePass load file system credentials (not database key) from the most recently used files list. Alternatively, the file system credentials can be specified using the -iousername: and -iopassword: parameters. The optional -ioiscomplete switch tells KeePass that the path and file system credentials are complete (the 'Open URL' dialog will not be displayed then).

In my opinion you only need to add `-ioiscompleted` to you commandline to suppress this dialog.

Regards,
Daniel

**Comment by Suncatcher** [comment]
Thanks, this helped.

**Comment by fubar-coder** [comment]
Just want to add that it's `-ioiscomplete` (as stated in the original documentation).
