### ISSUE TITLE
Unable to grab password from keepass when trying to authenticate dropbox

### ISSUE THREAD

**Issue by UnBayleefable** [Kyrodan/KeeAnywhere#60]
plugin requires me to sign in to my dropbox account to authenticate but i could not access my password for dropbox which was stored inside keepass.

**Comment by Kyrodan** [comment]
Sorry, I cannot help you with this problem. Try to recover your Dropbox password via "Forgotten Password" function.

**Comment by UnBayleefable** [comment]
i dont need help with the problem as i had a work around, but maybe thinking about parent detection so you can use the login details stored in keepass when trying to authenticate through keepass which is what you designed the plugin to do.

**Comment by Kyrodan** [comment]
Ok, now I understand. I will think about it.
