### ISSUE TITLE
Allow pasting in the embedded browser

### ISSUE THREAD

**Issue by athoms** [Kyrodan/KeeAnywhere#62]
When authenticating in the embedded browser, I would like to be able to paste my very long Google password. Unfortunately this is not allowed (IsWebBrowserContextMenuEnabled = false).
Could this be enabled? Or maybe a simple context menu with only Copy / Paste functions could be attached to the WebBrowser control.

**Comment by arcooke** [comment]
Marked as fixed in November but I still cannot paste.. KeePass 2.35 with KeeAnywhere 1.3.1

Had to manually type in my crazy 48 character password.

**Comment by Kyrodan** [comment]
This issue is fixed in source code but has not been released yet. Please be patient.
