### ISSUE TITLE
Dropbox: can't authenticate after introduction of new Login Page

### ISSUE THREAD

**Issue by dinnouti** [Kyrodan/KeeAnywhere#67]
When I try to add Dropbox, I enter my dropbox login and then the dropbox file browser shows in the same window, I don't know what to do next. Please can you help?

**Comment by dzidao** [comment]
Hi, I have this problem too.

**Comment by Kyrodan** [comment]
This is a (mis)behavior of the new Dropbox login (with the possibility to use a Google Account). I'm working on a fix.

**Comment by Kyrodan** [comment]
Released v1.3.1
