### ISSUE TITLE
Improvement proposition - add OwnCloud support

### ISSUE THREAD

**Issue by NedkoHristov** [Kyrodan/KeeAnywhere#70]
Hi guys. Thanks a lot for this plugin.

I think that the cloud shared database of KeePass is reasonably a good feature. But all of the supported clouds are corporate (OneDrive too) so I think it will be great if you add an OwnCloud support.

Regards,
Nedko.

**Comment by Kyrodan** [comment]
Duplicate to #47.

Nevertheless I do not plan to support Private Clouds with installations on own servers (like OwnCloud, SeaFile, etc.) or Corporate Accounts as long as it is not supported in the respective SDKs without to pay for running it (like OneDrive Business for which I have to pay for).

Especially for OwnCloud: take a look at the Forks of KeeAnywhere - if I remember right, someone implemented it already.
