### ISSUE TITLE
Hardening security of KeeAnywhere

### ISSUE THREAD

**Issue by NedkoHristov** [Kyrodan/KeeAnywhere#71]
I didn't find anywhere in the documentation how you send the database file to the cloud.
* Do you encrypt it once more?
* Do you use secure connection?
* Or you rely on the KeePassX database encryption?

Regards,
Nedko.

**Comment by Kyrodan** [comment]
Hi @NedkoHristov,

these are good questions which I will add to the Wiki.
Just the short answers:
1. Encryption: I do not encrypt it - KeePass already has strong encryption. So there is no real improved security if I add some more encyption (obfuscating something is not more secure). You have to decide by yourself to keep a Database hidde/secret/private and *not* to use KeeAnywhere. Or you trust KeePass Database encryption (and use at least two seperated Encryption Keys) - for me Cloud Providers are all "possibly public". The brand new KeePas 2.35 introduces a new improved encryption with a new KDBX4-Database-Format.

2. I mainly use the SDKs of the cloud providers. They all use https for communication.

3. I do not use anything from `KeePassX`

**Comment by NedkoHristov** [comment]
Thanks for the detailed answer, @Kyrodan.
I'm closing the issue.
