### ISSUE TITLE
Unable to unlock using pw-enc

### ISSUE THREAD

**Issue by trajano** [Kyrodan/KeeAnywhere#75]
In http://keepass.info/help/base/cmdline.html it states that we can pass in a password along with the database file to automatically unlock

> The `-pw-enc:` parameter is similar to `-pw:`, but it requires the password to be encrypted. Encrypted passwords can be generated using the {PASSWORD_ENC} placeholder.

I tried both but it does not work when I use a file stored in DropBox.

**Comment by Kyrodan** [comment]
Does an error message appear? Please post your exact command line you tried.

**Comment by trajano** [comment]
There's no error message.  It pops up a dialog asking for the user name and password when I tried...

    KeePass.exe "dropbox:///xyz/passwordskdbx" -keyfile:C:\keyfile.txt
    KeePass.exe "dropbox:///xyz/passwordskdbx" -pw:mypassword
    KeePass.exe "dropbox:///xyz/passwordskdbx" -pw-enc:PASSWORD_ENCODED

Without the dropbox... it does not work either.

    KeePass.exe -pw-enc:PASSWORD_ENCODED

**Comment by Kyrodan** [comment]
Ah ok, please add `-ioiscomplete` to your command line. Does this help?

**Comment by trajano** [comment]
Nope 👎  still shows the password entry dialog. BUT it does not ask for the "dropbox" credentials dialog.

**Comment by Kyrodan** [comment]
Hmm, I tried it again and can't reproduce this in my latest development snapshot. Maybe this problem is related to #63 and #68 and is gone by fixing this issues. 

But just to make sure we didn't miss a thing:
* in your URL "xyz" is your real Dropbox account name?
* "passwordskdbx" is your database (without a extension and without a period)?
* your database resides in root of your Dropbox?

**Comment by trajano** [comment]
`xyz` is my dropbox account name well it is the one they had provided not necessarily my e-mail address.
`passwordkdbx` is `someFolder\MySecretFile.kdbx` (more or less) as such NOT in the root of my Dropbox, but I did have a path just wanted to simplify the example.

**Comment by trajano** [comment]
Dunno about those issues you provided and how they are related but I guess  I'll need to wait for 1.4.0 then,

**Comment by Kyrodan** [comment]
Ok, could you please try this *unstable* build just for testing this issue:
[KeeAnywhere-1.4.0-unstable.plgx.zip](https://github.com/Kyrodan/KeeAnywhere/files/929813/KeeAnywhere-1.4.0-unstable.plgx.zip)

Please remove ZIP-Extension of this file completely - it's only needed for GitHub to get it uploaded.
I do not recommend to use this build productive - it's not tested very well.

**Comment by Kyrodan** [comment]
@trajano: could you please try the unstable 1.4.0 from my last post?

**Comment by trajano** [comment]
I am getting this weird message when I extract the file ![2017-05-19](https://cloud.githubusercontent.com/assets/110627/26245387/e1d31d88-3c61-11e7-9bdf-d01b98ffc8ff.png)

**Comment by Kyrodan** [comment]
Do not extract the ZIP - just remove ZIP-Extension: I just added something, so GitHub accepts this upload.

**Comment by trajano** [comment]
Doh okay sorry too early in the AM :)

**Comment by trajano** [comment]
`KeePass.exe "dropbox:///XXXX/Keys/XXXX.kdbx" -pw:XXXX -ioiscomplete`

Still locked but the password field is prefilled

**Comment by Kyrodan** [comment]
In first case: if the password is prefilled: could you open the database, if you confirm the open dialog without changinging something in it?

**Comment by trajano** [comment]
Yes the password is correct. It will Unlock.

**Comment by dhrv** [comment]
Actually it works and the "-ioiscomplete" parameter is necessary. I had the same problem like @trajano and after re-autotyping the encrypted password for the new database (as the DB was now opened from Google Drive) it worked. If you save the encrypted pw in your environment variables like described in some tutorials then be sure to reboot after updating the envvar.

**Comment by Kyrodan** [comment]
It is working now, I think. If not, please reopen this issue.
