### ISSUE TITLE
Google Drive: can't auth with ActiveDirectory and G Suite

### ISSUE THREAD

**Issue by jekking** [Kyrodan/KeeAnywhere#76]
Hi,

I have my organization working with G Suite but the authentication is against our AD FS.
When i try to add the username it works, but when this is done, then there is a redirection to our AD FS to autheticate and this does not work, because the AD FS page is not shown.

Thanks and regards

**Comment by Kyrodan** [comment]
I will take a look on it.

**Comment by jekking** [comment]
Thanks, if you need me for run some tests, just ask 👍

**Comment by Kyrodan** [comment]
Very old issue - closed for cleanup-reason. Feel free to reopen, if it is still valid in latest version 2.1.0
