### ISSUE TITLE
Unable to open from Cloud Drive any Dropbox account

### ISSUE THREAD

**Issue by Yghdrazill** [Kyrodan/KeeAnywhere#81]
Hi, 
I'm unable to enter my Dropbox credentials (for either type of Dropboxes) : page is pixellised, and only 2 buttons work : the upper left box, going to register page ; and the 'forgot password' button, going to a complete broken page.

Brief: can't click on 'connect with google' nor 'connect' so i can't do anything.

KeePass 2.35
KeePassLibC 1.32
KeeAnywhere 1.3.1

Thanks for your work ! :)

**Comment by Kyrodan** [comment]
Could you please attach a screenshot of this misbehavior?

**Comment by Kyrodan** [comment]
Cloing due to inactivity
