### ISSUE TITLE
Can't load dropbox database if offline, even though the file is synced.

### ISSUE THREAD

**Issue by yannou38** [Kyrodan/KeeAnywhere#82]
Hello,
It seems Keeanywhere won't allow me to load my dropbox-synced database if i'm not connected to the internet, even though it's locally there. 

Could a tweak in your code / my configuration allow people to use local file if internet request fail ? that would be very helpful when on the go :)

**Comment by Kyrodan** [comment]
Hi @yannou38 

just to clearify: KeeAnywhere does *not* use the regular Dropbox Client installed on your PC. So it doesn't matter whether the are locally synced or not with this client. KeeAnywhere uses it's own "direct" access to dropbox (a linked App). So if there is no internet connection, you cannot access your database.

Now you have three options:
* Use the locally synced Database from your Dropbox folder (not the best solution; KeeAnywhere has been built to circumvent this)
* Use the documented KeePass-Sync with Triggers from http://keepass.info/help/v2/sync.html and http://keepass.info/help/kb/trigger_examples.html#dbsync (this is completely OK, but has a more complicated initial setup)
* wait for Version 1.4 which has built-in support for your demand, see issue #5 (my preferred may, works out of the box)

Regards, 
Daniel
