### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by bryceschober** [Kyrodan/KeeAnywhere#83]
Error dialog:
---------------------------
KeePass - Fatal Error
---------------------------
A fatal error has occurred!

An extended error report has been copied to the clipboard.

Authentication failed!
---------------------------
OK   
---------------------------

How can I get more information about the error? Pasting from the clipboard at the time of the message contains only "Authentication failed!"

**Comment by kade-robertson** [comment]
Looks like the error is being thrown by `TryAuthenticate()` in the OAuth2Flow.cs file. I am getting the same issue, particularly with trying to add my Google Drive account (somehow my configuration was deleted and now I can't re-authenticate).

**Comment by Kyrodan** [comment]
If you are using Google Drive: duplicate to #74
