### ISSUE TITLE
BOX - Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown

### ISSUE THREAD

**Issue by VeryBaddude** [Kyrodan/KeeAnywhere#84]
First, thank you for putting this plugin together!

The message "Error loading file list.  Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown" is displayed when I do a check on the Box account that I had previously created.  But let me back up to where I think the problem really starts.

I can setup the access to the Box account fine and retrieve the KeePass database, work on it, save back to Box - no problem.  As soon as I minimize KeePass, I can no longer bring it back.  Right-clicking on it brings up a menu with all options greyed-out.  I have to kill KeePass with task manager.  When I tried to File | Open | Open from cloud drive I get the same error message as above.  

I'm on the lastest KeePass (2.35).

Thanks!

**Comment by Kyrodan** [comment]
I'm sorry for your inconvenience: it's an impact of #63.
I'm going to release 1.4.0 very soon - please be patient.
