### ISSUE TITLE
Authentication failed with Google drive

### ISSUE THREAD

**Issue by chauffch** [Kyrodan/KeeAnywhere#87]
Hi Daniel,
Thank you for your good product. 

my problem:
I have updated Keeanywhere from 1.3 to 1.4 and my authentication to Google drive does not work.

message: 
A fatal Error has occured!
An extended report has been copied to the clipboard.
Authentication failed!

in the clipboard:
Authentication failed!

some info:
 Keepass: v2.35
 Keeanywhere: 1.4
 authentication to dropbox works
 proxy system used
 Windows7
 same problem when default browser is internet explorer or chrome.

any idea ?
Christophe

**Comment by chauffch** [comment]
it appears when I try to add a new google drive account.

to be complete:
 - Tools / Keyannywhere setting
 - click on Add, select google Drive
 - on authorize to google drive screen, I see myslef and can enter my google password
 - on authorize to google drive 2nd screen, I click on blue button 'Autoriser' (french)
 - then appears popup message: 
A fatal Error has occured!
An extended report has been copied to the clipboard.
Authentication failed!

Hope I'm complete
Christophe

**Comment by Kyrodan** [comment]
Is your proxy configured corretly in KeePass? Please see #74. In the first half of this issue a similar problem could be solved.

**Comment by Kyrodan** [comment]
Another question: was Versionb 1.3.1 working for you (when adding a Google Drive account)?

**Comment by chauffch** [comment]
I think proxy is configured properly
 - the authentication works with dropbox.
 - keepass / options / Advances / proxy... / server = Use system proxy settings, authentication = default credentials

yes, it worked with keeanywhere 1.3.1

BR/CC

**Comment by Kyrodan** [comment]
Ok, I now have an idea of a possible problem. Let me dig deeper into it.

**Comment by Kyrodan** [comment]
Bug #74 is not completely fixed.
The root case is, that Google deprecated "WebView Authentication" in the end of 2016 and starts removing it's functionality by the end of April 2017.

Sources:
* https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
* https://developers.google.com/identity/protocols/OAuth2InstalledApp (Option 4, Programmatic Extraction)

I will implement a workaround for this problem in next (Hotfix) release 1.4.1 and re-implement authentication in a later version (see #89).

**Comment by Kyrodan** [comment]
Hi @chauffch ,

could you please try this development snapshot and report back your result:
[KeeAnywhere-1.4.1-unstable.plgx.zip](https://github.com/Kyrodan/KeeAnywhere/files/1044578/KeeAnywhere-1.4.1-unstable.plgx.zip)

**Comment by chauffch** [comment]
Daniel

you are the best.
works like a charm

thanks. I keep the unstable 1.4.1 version until you release it

BR/CC
