### ISSUE TITLE
Reimplement Account Authentication not using internal Web Browser

### ISSUE THREAD

**Issue by Kyrodan** [Kyrodan/KeeAnywhere#89]
Completely reimplement account authentication:
* remove WebView in favor of using System's Default Web Browser
* use internal (loopback) server instead of "URL/Document Title catching" (where possible)

Reasons:
* Google deprecated "WebView Authentication" in the end of 2016 and starts removing it's functionality by the end of April 2017 (see #87)
   * https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
   * https://developers.google.com/identity/protocols/OAuth2InstalledApp (Option 4, Programmatic Extraction)
* removing platform dependencies to support Mono/Linux (see #18)
* WinForms WebBrowser control uses outdated compatibility mode of Internet Explorer, which ist not supported by many platforms anymore

**Comment by BurningEnlightenment** [comment]
FYI there is an ietf draft regarding oauth2 in native applications which might be helpful: https://tools.ietf.org/html/draft-ietf-oauth-native-apps-11#page-2
There is also a netstandard1.4 implementation of said draft: https://github.com/IdentityModel/IdentityModel.OidcClient2
HTH

**Comment by univerio** [comment]
@Kyrodan Here's an idea: what if we have a trampoline page hosted on an SSL domain, that just uses JS to redirect to a localhost URL, effectively bypassing all of the SSL, port, and URL fragment restrictions?

**Comment by BurningEnlightenment** [comment]
@Kyrodan have you begun implementing this feature? If yes, can I help speeding things up in some way? If not, would you mind if I start implementing?

**Comment by Kyrodan** [comment]
Hi @BurningEnlightenment I haven't begun with this issue.
A Pull Request for that is welcome.
But please be aware: Not all provides currently implement this RFC. So you have to check it for every provider.

**Comment by BurningEnlightenment** [comment]
Microsoft finally implemented the PKCE RFC in Azure AD via the v2 Endpoint 🎉 
* [docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code)
* [doc-update-diff](https://github.com/MicrosoftDocs/azure-docs/commit/15b4fb3444c9dc890531b612eeab6e3bb9932349#diff-dbfa7971695ba1270bc260cec7d85708)
* [azure feedback ticket](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15933874-add-pkce-extensions-to-the-oauth-2-0-authorization?tracking_code=4dd05ea577c84b872da62b7a794e984c)

**Comment by marcomsousa** [comment]
I wasn't able to add my Google Drive Account.
Using last version about both the plugin and the KeePass. and Windows 10 Last version.

I was able to put my username/password and TFA PIN, but when Google show the allow or denied button grayed-out I can't press them.
Maybe because of incompatible with Web Browser, or deprecated..

**Comment by marcomsousa** [comment]
To fix issue my suggestion is to implement the same way as Cyberduck application.

When you choose the Google Drive, it open the Google Authentication/Verification in the default browser (outside the Application).
When to complete Google will give you a code y Copy it.
![image](https://user-images.githubusercontent.com/1110889/74534475-17897700-4f34-11ea-9fa1-667f9704de1a.png)

This Google oauth2 is configured as a Native App, the url is:
https://accounts.google.com/o/oauth2/approval/v2/approvalnativeapp?auto=false&response=state

Inside the Application you have a Google Drive windows to past the code retrieve in the browser:
![image](https://user-images.githubusercontent.com/1110889/74534109-55d26680-4f33-11ea-968f-f4885b583bc7.png)

**Comment by Turiok** [comment]
#212

**Comment by alabamatoy** [comment]
I appear to be broken as well.

**Comment by Kyrodan** [comment]
Releases v2.0.0 today.
