### ISSUE TITLE
Please add "per cloud account" password protection

### ISSUE THREAD

**Issue by craige1** [Kyrodan/KeeAnywhere#94]
I know that sounds odd, but i have a use case for this.
I would like for each cloud account added to keeanywhere to have a password/pin, to protect the account from being used.

We have keepass setup on a shared pc in the living room, on a htpc setup connected to the tv. It autologs into the windows account and that windows account is setup to run a bunch of app automatically. Its a proper HTPC setup. For things like watching netflix, or just checking up on the internet, normal web browsing is used, and having keepass for logging into accounts is great, as non of the websites is set to "remember me" as it is a shared pc.

We all store our keepass databases in cloud accounts as its very useful, but using keeanywhere currently means that everyone can see "into" everyone's cloud accounts as part of the browsing for the keepass file. I know generally the idea would be to use different windows accounts to store the accounts, but that doesn't work with out autologin account setup. 

I know this is a niche use case, but we would be very grateful if each cloud account could be pin/password protected.

**Comment by Kyrodan** [comment]
Hmm,

I thought about it for some time now and I come to the end that I will not implement this kind of functionality.

I'm sorry,
Daniel
