### ISSUE TITLE
Can't save to dropbox

### ISSUE THREAD

**Issue by mzarglis** [Kyrodan/KeeAnywhere#97]
when trying to save to dropbox i get the following error... any ideas?
![screenshot_1](https://user-images.githubusercontent.com/994599/28951165-414ba584-7897-11e7-944a-a613a8851d89.png)

**Comment by Kyrodan** [comment]
Hi @mzarglis ,

could you please start KeePass with Parameter "-debug". The error message should then be slightly different with more details or a Temp-Filename with details. Could you please post the content of this file here?

Regrads,
Daniel

**Comment by slingshot27** [comment]
Some issue here since today.
I can not save to an existing database anymore.
I can save to a new file in dropbox.
But after that I can not save again to the database.

**Comment by pharaonic-faery** [comment]
I have the same issue. I discovered today that it happens when I choose "backup to remote" in general settings. And it doesn't if I don't.

**Comment by slingshot27** [comment]
Will this issue been fixed?

**Comment by Kyrodan** [comment]
I will take a Look at it.

**Comment by slingshot27** [comment]
Thanks!

Op 24 sep. 2017 10:54 schreef "Daniel Bölts" <notifications@github.com>:

> I will take a Look at it.
>

**Comment by xiixexe** [comment]
same here. in my case it url says **dropbox://[firstname] [lastname]/db.kdbx**
Maybe because of the space between my first name and last name in the URL?

**Comment by pharaonic-faery** [comment]
I don't think so. Because when I sync for example, it works, though there is that space

**Comment by slingshot27** [comment]
Hi Kyrodan did you find a solution because I still have to problem.

**Comment by Kyrodan** [comment]
I'm sorry, I'm still very busy. So I haven't had any time to dive into this
:-(

slingshot27 <notifications@github.com> schrieb am Fr., 13. Okt. 2017 um
11:07 Uhr:

**Comment by Silun** [comment]
I have this problem as well, but only for remote backups. I get the same error, and the backup gets created roughly 5 times.

To be more precise: I start with an otherwise empty folder, just containing 1 .kdbx.
I press save -> it saves the database as it should, but then creates ~5 backups. It won't obey the limit on backups, either.

This happened on both dropbox and onedrive. Local backup works just fine.

**Comment by rdolezel** [comment]
I use KeeAnywhere to export KDBX file to Dropbox which is a source repository for synchronization to my iOS devices. Unfortunately it seems KeePass 2.37 breaks something with KeeAnywhere. I downgraded back to KeePass 2.36 and everything works fine again.

**Comment by Kyrodan** [comment]
I will keep an eye on it.

**Comment by Kyrodan** [comment]
KeePass 2.37 is not the source problem as it seems this issue also hits other KeePass versions.

**Comment by CkA304HuK** [comment]
Hi.
Kyrodan, I think that the problem can be caused by a change in the logic or the protocols of the dropbox
I received an email saying that the dropbox team will make changes on September 28 that can affect synchronization using external connected applications.

**Comment by Faark** [comment]
I got such a message. It was caused by DropboxStorageProvider.RootPath not handling empty strings (""[0] causes an IndexOutOfRangeException). Worked again once i moved the database into a subdirectory, so a quick workaround seems to be to not save your database directly in the Dropbox root.

Here is an incomplete stack trace (fu async) with unreliable line numbers:

> `	KeeAnywhere.dll!KeeAnywhere.StorageProviders.Dropbox.DropboxStorageProvider.RootPath(string path) Line 108	C#	Symbols loaded.
>  	KeeAnywhere.dll!KeeAnywhere.StorageProviders.Dropbox.DropboxStorageProvider.GetChildrenByParentPath(string path) Line 95	C#	Symbols loaded.
>  	KeeAnywhere.dll!KeeAnywhere.StorageProviders.ProxyProvider.GetChildrenByParentPath(string path) Line 55	C#	Symbols loaded.
>  	KeeAnywhere.dll!KeeAnywhere.Backup.BackupProvider.RotateRemote(string path) Line 60	C#	Symbols loaded.
>  	KeeAnywhere.dll!KeeAnywhere.Backup.BackupProvider.Save(System.IO.Stream stream, string path) Line 48	C#	Symbols loaded.
>  	[Resuming Async Method]		Annotated Frame
> `

**Comment by lowrider2025** [comment]
Is Keeanywhere still being developed ? I still have same problem as OP. I can open files fine but save gives same error as OP. KP 2.39.1 KA 1.4.1

**Comment by Kyrodan** [comment]
I recently released v1.5.1. Could you please try to reproduce your issue with this version (an KeePass 2.40)?

**Comment by slingshot27** [comment]
Hi,

It works fine for me, thanks!

Cheers,

Johan


Op vr 19 okt. 2018 om 12:36 schreef Daniel Bölts <notifications@github.com>:

**Comment by slingshot27** [comment]
I don't have the error anymore.

**Comment by l0ser140** [comment]
I have two win10 1803 devices with that problem.
KA connected to app folder.
Both of them also have Dropbox client installed, but I tested delete it - not related to problem.

**Comment by opeeba** [comment]
I have been getting this error intermittently the past few weeks.

**Comment by Kyrodan** [comment]
Very old issue - closed for cleanup-reason. Feel free to reopen, if it is still valid in latest version 2.1.0
