### ISSUE TITLE
Automatic Backup doesn't work

### ISSUE THREAD

**Issue by jtcmedia** [Kyrodan/KeeAnywhere#98]
Seems simple enough but it doesn't do anything:
[![keeanywhere_settings.png](https://s1.postimg.org/s6m6g6qkf/keeanywhere_settings.png)](https://postimg.org/image/hwjrgy0or/)

Have those checked but doesn't backup to cloud or local. How is it triggered?

**Comment by ebekker** [comment]
It seems to work for me -- everytime you save your .kdbx file, it will make a backup of the previous copy, for example, I keep a Remote copy, and it creates the backups right next to my remote file:

```
PasswordFile.kdbx
PasswordFile_Backup_2017-07-29-17-06-34.kdbx
PasswordFile_Backup_2017-08-01-23-14-40.kdbx
```

**Comment by ebekker** [comment]
More details of the behavior are in #61.

**Comment by jtcmedia** [comment]
My bad, it is actually Backup **on** Remote not Backup **to** Remote.

**Comment by Kyrodan** [comment]
Thanks for pointing me to this unclear wording. I will improve documentation and/or wording for this.
